### ISSUE TITLE
gawk does not build with the newest commit

### ISSUE THREAD

**Issue by Csega** [redox-os/redox#1001]
**Reproduction**: use the latest bootstrap.sh, then cd redox, then make all

**Expected behavior**: build redox correctly

**Actual behavior**: gawk does not build

**Build information**: `rustc -V`: rustc 1.20.0-nightly (ae98ebfcb 2017-07-20)
                                    `git rev-parse HEAD`: c8d7b6d773a70170c312da7d21f2a506b578305b
                                    `qemu-i386 -version`: qemu-i386 version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.14), Copyright (c) 2003-2008 Fabrice Bellard
                                    `uname -a`: Linux csega-eos-loki 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Misc**: the exact output:
make[3]: Entering directory '/home/csega/redox/cookbook/recipes/gawk/build'
x86_64-elf-redox-gcc  -g -O2 -DNDEBUG   -o gawk array.o awkgram.o builtin.o cint_array.o command.o debug.o eval.o ext.o field.o floatcomp.o gawkapi.o gawkmisc.o int_array.o io.o main.o mpfr.o msg.o node.o profile.o re.o replace.o str_array.o symbol.o version.o support/libsupport.a      -lm 
main.o: In function `load_procinfo':
/home/csega/redox/cookbook/recipes/gawk/build/main.c:1003: undefined reference to `getppid'
collect2: error: ld returned 1 exit status
Makefile:648: recipe for target 'gawk' failed
make[3]: *** [gawk] Error 1
make[3]: Leaving directory '/home/csega/redox/cookbook/recipes/gawk/build'
Makefile:727: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/csega/redox/cookbook/recipes/gawk/build'
Makefile:552: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/csega/redox/cookbook/recipes/gawk/build'
./repo.sh failed.mk/filesystem.mk:2: recipe for target 'build/filesystem.bin' failed
make: *** [build/filesystem.bin] Error 1

------

**Comment by jackpot51** [comment]
Is your Redox cross compiler up to date?

**Comment by ids1024** [comment]
This error shouldn't occur if you have the latest Redox newlib (which changes a lot as C programs are ported, adding things like this).

**Comment by Csega** [comment]
How should I check it?

**Comment by ids1024** [comment]
You should install a new version of newlib however you installed the toolchain (from the .deb in https://static.redox-os.org/toolchain/apt/, from the Arch PKGBUILD in https://github.com/redox-os/libc, using the ./setup.sh script in that repo, etc.)

You should only need to update that, and not the rest of the toolchain.

**Comment by Csega** [comment]
Thanks, it works after I updated the libraries. Is there a way to upgrade these automatically (I mean using apt update && apt upgrade)?
