### ISSUE TITLE
xargo is missing in the dependencies

### ISSUE THREAD

**Issue by adrianbrink** [redox-os/redox#1036]
**Reproduction**: Run the installation script and then run `make all`

**Expected behavior**: Installs all dependencies and `make all` runs successfully.

**Actual behavior**: Throws error that `xargo` is missing.

**Solution**: Add `xargo` to dependencies.

**Comment by bcko** [comment]
I also had the same issue and had to type `cargo install xargo` and run `make all` again. Is anyone working on adding `xargo` to dependencies?

**Comment by blaiseli** [comment]
Same problem for me. `cargo install xargo` helped pass this step, but then I get other errors.

**Comment by sajattack** [comment]
Fixed in 3b145a3
