### ISSUE TITLE
Fork ffmpeg to fix pthread issue

### ISSUE THREAD

**Issue by jackpot51** [redox-os/redox#1055]
This commit is the last to build in the cookbook: https://github.com/FFmpeg/FFmpeg/tree/fde5c7dc79eb017790ba232442ad2a4eecea4bf1

This commit broke the build:
https://github.com/FFmpeg/FFmpeg/commit/83c12fefd22fc2326a000019e5c1a33e90a874e8

**Comment by xTibor** [comment]
It might worth a try to switch from the master to a release branch first instead of forking.

**Comment by jackpot51** [comment]
@xTibor good idea
