### ISSUE TITLE
Redox does not load with < 2GB RAM

### ISSUE THREAD

**Issue by dylanmtaylor** [redox-os/redox#1057]
When running Redox OS in a 1 GB RAM VirtualBox instance, it does not start. Bumping the RAM amount to > 2 GB fixes the issue.

**Comment by thetoxicarcade** [comment]
I'm just interested in figuring out what's technically doing this. Whether or not we should/shouldn't get rid of it.

**Comment by Pharaone** [comment]
+1

**Comment by Pharaone** [comment]
The same happens with real hardware

**Comment by jackpot51** [comment]
An inefficient method of doing live disks uses up the excess RAM.

**Comment by pftbest** [comment]
I've seen at least 3 people trying to run it in VirtualBox with 512M of ram, and then reporting that it doesn't work. And I kinda understand their point, since the ISO is only 40M in size, then a half a gig should be plenty, right?

**Comment by michaelbachner** [comment]
> An inefficient method of doing live disks uses up the excess RAM.

Could you elaborate on this? Is there a way to introduce a more efficient method?

**Comment by ids1024** [comment]
> Could you elaborate on this? Is there a way to introduce a more efficient method?

Redox currently only supports booting from a hard drive; so the ISO uses [MEMDISK](http://www.syslinux.org/wiki/index.php?title=MEMDISK) to load the hard disk image into RAM, which takes up as much RAM as the hard disk image (including unused space).

In the future it should be possible to improve this. In particular, a USB mass storage driver would allow read/write bootable USB drives, which would then be the preferred way of testing Redox on real hardware. Things like an equivalent of tmpfs, and union mounting might help with live CDs, but USB support is a higher priority.

For a virtual machine, it is better to use a virtual hard disk. The release includes a `.bin.gz` file that can be used for that; I'm not sure exactly how to set that up in VirtualBox, but you can look at the [Makefile](https://github.com/redox-os/redox/blob/master/mk/virtualbox.mk).

I recently added a sort section to [The Book](https://doc.redox-os.org/book/getting_started/try_vm.html) for this; VirtualBox instructions and such should really be added there.

**Comment by jackpot51** [comment]
Ok everybody. I am going to fix this, once and for all.

I will not have something like SquashFS yet, where the FS can be loaded from external media where needed.

I will instead make the current method of storing the filesystem in RAM more efficient. This involves:
- Preventing duplicate copies
- Not storing empty space
- Not preallocating kernel heap

**Comment by jackpot51** [comment]
Part one of the fix - https://github.com/redox-os/kernel/commit/d6b9768dc3e9cd967df0acf3eafb10d02c9f0ba6

**Comment by jackpot51** [comment]
Second part in https://github.com/redox-os/redox/commit/345c6bc4349d135c79fe20a6f5dcc3ea8c0e2349

Usage is now below 512 MB.

**Comment by jackpot51** [comment]
I will be releasing 0.3.3 with these changes.
