### ISSUE TITLE
Stuck on Redox Loader - Stage Two

### ISSUE THREAD

**Issue by theunkow** [redox-os/redox#1065]
**Reproduction**: Trying to boot and install Redox from redox_0.3.2.iso on bootable USB (done with Rufus). It always gets stuck on the line after Redox Loader - Stage Two saying "00000007#007F 0000:8A00".

**Expected behavior**: The booting/instalation process should continue to allow user control on a kind of a desktop environment.

**Actual behavior**: Keyboard control is frozen, reboot is only option. Only the "underline" is blinking as it expects some input. (not even ctrl+alt+delete works)

**Redox release**: redox_0.3.2.iso

**Misc**: Rufus was used to build the iso and may be source of the issue, it was built on fat32 filesystem.
Update: this was done on the following build (Core 2 Duo 7200, 9600GT, 6GB DDR 2 800HZ, JWP45D2-ULTRA) in case it helps

------

Thanks for the hard work so far, hope to see lots more of Rust in the future.

**Comment by Pharaone** [comment]
How many GBs of Ram do you have?

**Comment by theunkow** [comment]
6GB DDR2 800MHZ (it's in the **Misc:** part)

**Comment by jackpot51** [comment]
I do not believe Rufus correctly produces bootable Redox disks. The image must be written directly to a USB drive, FAT32 should not be involved at all. It should be an ISO9660 filesystem.

**Comment by theunkow** [comment]
Well sorry then, I will properly retry next time and reopen the issue if it still persists.

Thanks.
