### ISSUE TITLE
ISO won't load in VM

### ISSUE THREAD

**Issue by ThosV** [redox-os/redox#1069]
**Reproduction**: Attempt to boot Redox 0.3.2 iso in Oracle VM VirtualBox

**Expected behavior**: System should boot into desktop environment

**Actual behavior**: System produces a (s)ave/(y)es/(n)o query and then simply goes black. 

**Redox release**: 0.3.2

**Blocking/related**: Don't think so 

**Misc**: Doing all this on AntergOS Linux. Oracle VM VirtualBox 5.1.28 r117968. Followed all the settings in the First Release github page. 

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by jackpot51** [comment]
How much RAM did you provide the VM?

**Comment by ThosV** [comment]
1024 MB, per the instructions on the 0.0.3 release example configuration.

**Comment by jackpot51** [comment]
Try 2048 MB

**Comment by ThosV** [comment]
Yep, that worked, thanks?

Honest question: why does Redox need such a larger chunk of RAM? I've got a VM with Arch installed that runs fine on 1024.

**Comment by jackpot51** [comment]
The live session is implemented in an inefficient manner, the entire filesystem and free space is loaded into memory.

**Comment by leeoniya** [comment]
@jackpot51 this comes up pretty frequently, is there a timeline or any indication of where this falls in the priority queue?
