### ISSUE TITLE
Make events utilize URLs

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#107]

**Comment by jackpot51** [comment]
I did this once and it was too slow, but maybe now we can figure it out:

m:200/300/1 is a mouseclick
k:C/80/1 is a key press

**Comment by Ticki** [comment]
Why not just have a channel say input:kb and send the bytes of the keypresses? Instead of parsing it every time.

**Comment by jackpot51** [comment]
that's smart

**Comment by Ticki** [comment]
The same could be doen with the window manager. Because I'm not sure parsing it all the time would give very good performance.

**Comment by jackpot51** [comment]
That was why I removed it and went with the Event struct

**Comment by Ticki** [comment]
What's the state of this?
