### ISSUE TITLE
Can't install packages in Redox 0.3.4

### ISSUE THREAD

**Issue by pharaone** [redox-os/redox#1083]
I tried to install gcc but the installation fails, after that I tried to install some other package but it says that there isn't space in the drive "os error 28" (this isn't true, I have 19 GBs free in the virtual box disk)
![cattura2](https://user-images.githubusercontent.com/17162630/31582708-8af49d3a-b18b-11e7-8d42-59cfaeaa911d.PNG)
I have this problem since 0.3.3.

**Comment by sajattack** [comment]
The file system in the iso is only 256MB. To get a bigger filesystem on disk you have to compile from source.
