### ISSUE TITLE
Failure to build redox due to a missing branch in termion named "redox_termios"

### ISSUE THREAD

**Issue by meven** [redox-os/redox#1086]
- [x] I agree that I have searched opened and closed issues to prevent duplicates.

--------------------

## Description

When following the instructions the quick setup instruction of redox:

> $ cd path/to/your/projects/folder/
> 
> # Run bootstrap setup
> $ curl -sf https://raw.githubusercontent.com/redox-os/redox/master/bootstrap.sh -o bootstrap.sh && bash -e bootstrap.sh
> 
> #Change to project directory
> $ cd redox
> 
> # Build Redox
> $ make all

The build fails with a trace : 

> 
>      Updating git repository `https://github.com/redox-os/termion.git`
> error: failed to load source for a dependency on `termion`
> 
> Caused by:
>   Unable to update https://github.com/redox-os/termion.git?branch=redox_termios
> 
> To learn more, run the command again with --verbose.

Using --verbose option, I get 

> $ cargo update --manifest-path cookbook/pkgutils/Cargo.toml --verbose
>     Updating registry `https://github.com/rust-lang/crates.io-index`
>     Updating git repository `https://github.com/ids1024/pb`
>     Updating git repository `https://github.com/redox-os/tar-rs`
>     Updating git repository `https://github.com/libOctavo/octavo.git`
>     Updating git repository `https://github.com/redox-os/termion.git`
> error: failed to load source for a dependency on `termion`
> 
> Caused by:
>   Unable to update https://github.com/redox-os/termion.git?branch=redox_termios
> 
> Caused by:
>   failed to find branch `redox_termios`
> 
> Caused by:
>   [4/-3] cannot locate local branch 'redox_termios'

And indeed in https://github.com/redox-os/termion/branches we can see the branch redox_termios does not exist.

## Environment info

- Operating system:
Ubuntu 16.04 (kde-neon)
- `uname -a`:
Linux hostname 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- `rustc -V`:
rustc 1.22.0-nightly (f6d751454 2017-10-17)
- `git rev-parse HEAD`:
d1ddf63d20ebe4a85fdd94675822ff9a0ebd3718

## Steps to reproduce

1. Follow the quick setup instruction of https://github.com/redox-os/redox :
> $ cd path/to/your/projects/folder/
> 
> # Run bootstrap setup
> $ curl -sf https://raw.githubusercontent.com/redox-os/redox/master/bootstrap.sh -o bootstrap.sh && bash -e bootstrap.sh
> 
> #Change to project directory
> $ cd redox
> 
> # Build Redox
> $ make all # make command fails

## Behavior

- **Expected behavior**:
redox builds

- **Actual behavior**:
Build fails with last logs:
> cargo update --manifest-path cookbook/pkgutils/Cargo.toml
>     Updating registry `https://github.com/rust-lang/crates.io-index`
>     Updating git repository `https://github.com/ids1024/pb`
>     Updating git repository `https://github.com/redox-os/tar-rs`
>     Updating git repository `https://github.com/libOctavo/octavo.git`
>     Updating git repository `https://github.com/redox-os/termion.git`
> error: failed to load source for a dependency on `termion`
> 
> Caused by:
>   Unable to update https://github.com/redox-os/termion.git?branch=redox_termios
> 
> To learn more, run the command again with --verbose.

- **Proposed solution**:
Recreate the branch redox_termios in the termion repository or update the references in redox repositories to this branch to use master or another existing branch in the termion repository.

**Comment by jackpot51** [comment]
I have updated the pkgutils inside cookbook, so this should be fixed.

**Comment by liamnaddell** [comment]
I just got this issue as well:

```cook - extrautils build
    Updating git repository `https://github.com/redox-os/termion.git`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for a dependency on `termion`

Caused by:
  Unable to update https://github.com/redox-os/termion.git#88cba89b

Caused by:
  revspec '88cba89b23f2b8a18c14a5ca7cd8024be8d6f04d' not found; class=Reference (4); code=NotFound (-3)
./repo.sh failed.mk/filesystem.mk:2: recipe for target 'build/filesystem.bin' failed
make: *** [build/filesystem.bin] Error 1
```

```Uname -a = Linux localhost 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1 (2018-04-29) x86_64 GNU/Linux```

I used the Debian method of installing the toolchain.

I would be happy to provide any info needed. 

What I tried:

Running `make clean`, then running `make all` again

How  I cloned the repo down:

```git clone https://github.com/redox-os/redox.git --origin upstream --recursive && \
   cd redox && git submodule update --recursive --init```

What I tried: using the bootstrap script to pull down the repo instead of using the manual method
Result: same exact failure
What I tried: make clean
Result: same thing
What I tried: make clean pull
Result: same again

**Comment by liamnaddell** [comment]
My autoconf is version 2.69
My automake is version 1.15
My gcc is version 6.3.0
