### ISSUE TITLE
Redox on The Changelog!

### ISSUE THREAD

**Issue by jerodsanto** [redox-os/redox#1092]
Howdy from [The Changelog](https://changelog.com/podcast)!

_(Never heard of The Changelog? We've been interviewing the hackers, leaders, and innovators of open source and software development since '09.)_

We'd love to have you on the show sometime soon. @jackpot51 please join us to talk about Redox and all the cool stuff y'all are up to.

Interested? Please email editors@changelog.com to coordinate. 

Looking forward to it! 💚

**Comment by jackpot51** [comment]
This sounds pretty cool - send me an email at info@redox-os.org

**Comment by milkey-mouse** [comment]
I suppose this should be closed... https://changelog.com/podcast/280

**Comment by jackpot51** [comment]
Yeah, probably so
