### ISSUE TITLE
error: failed to load source for a dependency on `collections`

### ISSUE THREAD

**Issue by sajattack** [redox-os/redox#1093]
- [x] I agree that I have searched opened and closed issues to prevent duplicates.

--------------------

## Description

The error listed in the title occurs because libcollections was removed in the most recent commit to redox-os/rust

## Environment info

- Redox OS Release:
git 28e512c

- Operating system:
Arch Linux
- `uname -a`:
Linux P50-Arch 4.13.9-1-ARCH #1 SMP PREEMPT Sun Oct 22 09:07:32 CEST 2017 x86_64 GNU/Linu`
- `rustc -V`:
rustc 1.23.0-nightly (269cf5026 2017-10-28)
- `git rev-parse HEAD`:
28e512c98ab275cd39d475d7fcf13ae9921beb7b

- Replace me:
Replace me

## Steps to reproduce

1. git clone git@github.com:redox-os/redox
2. cd redox && make all

## Behavior

- **Expected behavior**:
Redox should compile

- **Actual behavior**:
The error in the title is printed

```
error: failed to load source for a dependency on `collections`

Caused by:
  Unable to update file:///home/paul/redox/redox/rust/src/libcollections

Caused by:
  failed to read `/home/paul/redox/redox/rust/src/libcollections/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
error: `"cargo" "build" "--release" "--manifest-path" "/tmp/xargo.rorUEekT8Yq4/Cargo.toml" "--target" "x86_64-unknown-none" "-p" "alloc"` failed with exit code: Some(101)
note: run with `RUST_BACKTRACE=1` for a backtrace
make: *** [mk/kernel.mk:6: build/libkernel.a] Error 1

```

- **Proposed solution**:
Remove dependencies on collections or revert the commit that removed it

## Optional references

Related to:
- #0000 Remove me
- Replace me
- ...

Blocked by:
- #0000 Remove me
- ...

## Optional extras

Replace me

**Comment by jackpot51** [comment]
This should be fixed with master now
