### ISSUE TITLE
documentation should list supported processor architectures

### ISSUE THREAD

**Issue by Trolldemorted** [redox-os/redox#1100]
- [x] I agree that I have searched opened and closed issues to prevent duplicates.

--------------------

I had a look at the documentation and the issues, and was unable to find hints about which processor architectures are supported. x86/x64 is obvious, but what about MIPS, ARM and others? I really would like to see redox instead of linux in action on safety and security-critical embedded devices like routers, so the redox book should tell me in the first chapter which platforms are currently supported, which are likely to be supported some time later, and which won't.

**Comment by cookie545445** [comment]
[The Book, chapter 1.1](https://doc.redox-os.org/book/overview/what_redox_is.html) lists the hardware that Redox supports. x86_64 is the only obvious supported arch because it is the only supported arch.

Nothing definitive can be said about future support at the moment.

**Comment by Trolldemorted** [comment]
That's what i get for skipping the first part, i guess - sorry for the inconvenience.

More supported architectures would be great, though.
