### ISSUE TITLE
/usr inappropriately soft-links to /: Results in infinite recursion with, "ls -lR /"

### ISSUE THREAD

**Issue by gbutler69** [redox-os/redox#1102]
- [ X] I agree that I have searched opened and closed issues to prevent duplicates.

--------------------

## Description

If you go to the root of the file-system in Redox and enter the command, `ls -lR` (or simply type, `ls -lR /` anywhere) it goes into infinite recursion showing files/folders in:

/usr/bin
/usr/usr/bin
/usr/usr/usr/bin
...
/usr/usr/usr/.........../usr/bin
etc.

## Environment info

Inside Redox OS running under QEMU following the proscribed procedures.

- Operating system:

Ubuntu 17.04 (Linux)

- `uname -a`:

`Linux butler-Leopard-Extreme 4.10.0-38-generic #42-Ubuntu SMP Tue Oct 10 13:24:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

- `rustc -V`:

`rustc 1.23.0-nightly (79cfce3d3 2017-11-12)`

- `git rev-parse HEAD`:

`5f7233417b7934604ac5e355989dd4613c1b64c5`

## Steps to reproduce

   1. Build Redox
   2. start it with, "make qemu"
   3. Login using "root/password"
   4. enter the following command, "ls -lR /"
   5. watch as it infinitely recurses into /usr, /usr/usr, /usr/usr/usr, ...

## Behavior

- **Expected behavior**:

   * lists all files/folders on the file-system without infinitely recursing

- **Actual behavior**:

    * infinite recursion into /usr, /usr/usr/, ...

- **Proposed solution**:

    Change /usr to be an actual folder and /usr/bin to be a soft-links to /bin  as follows:

````
rm /usr
mkdir /usr
chown root:root /usr
chmod 755 /usr
ln -s /bin /usr/bin
````

EDIT: Make the sub-folders of /usr that are soft-links correctly reflect the desired/current folders at the / level in RedoxOS

**Comment by xTibor** [comment]
Here's where the recursive symlink is defined:
https://github.com/redox-os/redox/blob/f9865f49d1e597f54beb61dbe456a0969396dc7a/filesystem.toml#L177-L180

**Comment by gbutler69** [comment]
I'm working on this. Already have a fix ready. Just working on submitting PR.
