### ISSUE TITLE
BUILD FAILURE: xz GitHub codeload "not having it"

### ISSUE THREAD

**Issue by MGageMorgan** [redox-os/redox#1107]
- [x] I agree that I have searched opened and closed issues to prevent duplicates.

--------------------

## Description

On compilation, the cookbook seems to give up. The following summarizes what happened, because apparently XZ couldn't be found, or a wrong URL somewhere or something.

## Environment info

- Operating system: 
Antergos Linux
- `uname -a`:
```Linux gages-ZAVINIA-pc 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux```
- `rustc -V`:
```rustc 1.23.0-nightly (d0f8e2913 2017-11-16)```
- `git rev-parse HEAD`:
```67e52e1c9db875358d2d322f6e8f8a422ecdd7b8```

- Arch Linux PKGBUILDS
I spent a considerable amount of time making sure these were installed properly. This seems to be an issue on the dev end of things, and I have no idea how to fix it.

If this gets fixed, is there a way to continue without screwing over the progress I've already made on the build?

## Steps to reproduce

1. Walk through the steps in Quick Start
2. The build won't be able to access a URL
3. Prosper (even though failure isn't prosperous lol) /s

## Behavior

- **Expected behavior**:
Gets to the end of compilation without failing so an ISO can be produced eventually.

- **Actual behavior**:
It got to the point where it needed something that did exist on the XZ GitHub mirror.

![screenshot from 2017-11-17 19-57-14](https://user-images.githubusercontent.com/13326489/32975098-e4c48b1c-cbd1-11e7-8866-44022b6919a1.png)

**Comment by MGageMorgan** [comment]
This:
https://codeload.github.com/xz-mirror/xz/archive/v5.2.3.tar.gz
Dead. Straight dead bruh.

I need to figure out an alt package and put it wherever the installer expects it to be...

**Comment by MGageMorgan** [comment]
This is what SHOULD be in the installer (I think????): https://github.com/xz-mirror/xz/archive/v5.2.3.tar.gz

Remove 'codeload' from the URL. If I figure out how to fix the files before anyone else, I'll submit a PR for the changes.

**Comment by MGageMorgan** [comment]
```redox/cookbook/recipes/xz/recipe.sh```

Get rid of the ```codeload``` tomfoolery, it breaks everything.

**Comment by MGageMorgan** [comment]
Progress Report: #62 (lets out loooooong groan):
After replacing URL to get said file, I get this beautiful prompt:

```
Create directory build/filesystem/
repo - coreutils up to date
repo - drivers up to date
repo - preparing extrautils
cook - extrautils prepare
~/redox/redox/cookbook ~/redox/redox/cookbook/recipes/extrautils
 - repreparing xz
cook - xz unprepare
cook - xz prepare
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -ru source/src/xz/file_io.c source-new/src/xz/file_io.c
|--- source/src/xz/file_io.c	2016-12-30 03:13:57.000000000 -0800
|+++ source-new/src/xz/file_io.c	2017-08-08 12:34:08.453700076 -0700
--------------------------
File to patch: ~/redox/redox/cookbook/recipes/xz/05_all_americans_rejected.patch
~/redox/redox/cookbook/recipes/xz/05_all_americans_rejected.patch: No such file or directory
Skip this patch? [y] n   
File to patch: /home/mgagemorgan/redox/redox/cookbook/recipes/xz/05_all_americans_rejected.patch                                            
patching file /home/mgagemorgan/redox/redox/cookbook/recipes/xz/05_all_americans_rejected.patch
Hunk #1 FAILED at 17.
Hunk #2 FAILED at 222.
Hunk #3 FAILED at 704.
Hunk #4 FAILED at 713.
Hunk #5 FAILED at 1127.
Hunk #6 FAILED at 1215.
6 out of 6 hunks FAILED -- saving rejects to file /home/mgagemorgan/redox/redox/cookbook/recipes/xz/05_all_americans_rejected.patch.rej
./repo.sh failed.make: *** [mk/filesystem.mk:12: build/filesystem.bin] Error 1
```

Buckets of fun!!!

So, let's take a look at the rejects of the day, in case anyone who can figure this out can. I got other stuff I need to do, so sadly I won't get any further than this:

```
--- src/xz/file_io.c	2016-12-30 03:13:57.000000000 -0800
+++ src/xz/file_io.c	2017-08-08 12:34:08.453700076 -0700
@@ -17,7 +17,7 @@
 #ifdef TUKLIB_DOSLIKE
 #	include <io.h>
 #else
-#	include <poll.h>
+//#	include <poll.h>
 static bool warn_fchown;
 #endif
 
@@ -222,7 +222,7 @@
 #endif // ENABLE_SANDBOX
 
 
-#ifndef TUKLIB_DOSLIKE
+#if 0
 /// \brief      Waits for input or output to become available or for a signal
 ///
 /// This uses the self-pipe trick to avoid a race condition that can occur
@@ -704,6 +704,7 @@
 	// If it is something else than a regular file, wait until
 	// there is input available. This way reading from FIFOs
 	// will work when open() is used with O_NONBLOCK.
+#if 0
 	if (!S_ISREG(pair->src_st.st_mode)) {
 		signals_unblock();
 		const io_wait_ret ret = io_wait(pair, -1, true);
@@ -713,6 +714,7 @@
 			goto error;
 	}
 #endif
+#endif
 
 #ifdef HAVE_POSIX_FADVISE
 	// It will fail with some special files like FIFOs but that is fine.
@@ -1127,7 +1129,7 @@
 				continue;
 			}
 
-#ifndef TUKLIB_DOSLIKE
+#if 0
 			if (IS_EAGAIN_OR_EWOULDBLOCK(errno)) {
 				const io_wait_ret ret = io_wait(pair,
 						mytime_get_flush_timeout(),
@@ -1215,7 +1217,7 @@
 				continue;
 			}
 
-#ifndef TUKLIB_DOSLIKE
+#if 0
 			if (IS_EAGAIN_OR_EWOULDBLOCK(errno)) {
 				if (io_wait(pair, -1, false) == IO_WAIT_MORE)
 					continue;
```

Good luck to anyone who knows what they're doing, because I sure as hell don't.

**Comment by jackpot51** [comment]
I think this is fixed now - please checkout and pull the cookbook

**Comment by MGageMorgan** [comment]
@jackpot51, could you update the submodule(s) to match the commits in the main repo? I tried pulling the cookbook fresh, but it wouldn't work with me. It fails when I try to use the new commit, and looks like it's because Git wants to make it (seem) more difficult than it really is.

**Comment by jackpot51** [comment]
The Redox submodule link is up to date now:
```
git pull
git submodule update --init --recursive
```

**Comment by MGageMorgan** [comment]
Yup, it works now. This REALLY showcases how efficient Rust can be. God, I can run something like Ubuntu or Fedora in QEMU and it'll lag like a bitch - but this - THIS is amazing. My Galago didn't break a sweat during the 15 minutes I played with it. Great work, man. Whenever someone questions Rust's claim to fame of efficiency, this is probably the project they should be referred to.

Not to mention the build time was only half an hour....on a dual-core processor!!!!!!
