### ISSUE TITLE
[Docs] Missing documentation on debugging with qemu and gdb

### ISSUE THREAD

**Issue by dlrobertson** [redox-os/redox#1116]
## Description:
redox-os/redox#1114 makes debugging the kernel easier. Write up
some documentation on how to use `qemu` and `rust-gdb` to debug
the kernel.

## Open questions:
- Where should documentation like this exist?

## Optional references:
 - http://wiki.osdev.org/Kernel_Debugging

## Related to:
- redox-os/redox#1114
- redox-os/kernel#64

**Comment by jackpot51** [comment]
Perhaps it should be in the kernel's readme?

**Comment by dlrobertson** [comment]
Yeah, that seems reasonable.

**Comment by dlrobertson** [comment]
Fixed with redox-os/kernel#65
