### ISSUE TITLE
Cmake required by uutils

### ISSUE THREAD

**Issue by sajattack** [redox-os/redox#1119]
So we should either add it to bootstrap.sh or find a workaround. Thoughts @jackpot51 ?

**Comment by sajattack** [comment]
As an aside, can we unify the package list as much as possible in bootstrap.sh? Right now there are many places that need to be edited to add a package. I understand some platforms have different names but there should be a core group that's the same.

**Comment by jackpot51** [comment]
We need to add it. I imagine the things requiring it will only grow. Not sure about unifying the package lists - it is important to verify that each platform supported builds correctly with bootstrap.sh, and that makes it too easy to mess up another platform by adding something you think it has.
