### ISSUE TITLE
cook Logd not found.

### ISSUE THREAD

**Issue by BearzRobotics** [redox-os/redox#1142]
- [x ] I agree that I have searched opened and closed issues to prevent duplicates.

## Description
When I went to build redox I got an error:
repo - fetching logd
cook.sh: recipe 'logd' not found
./repo.sh failed.mk/filesystem.mk:2: recipe for target 'build/filesystem.bin' failed
make: *** [build/filesystem.bin] Error 1

## Environment info
- Operating system: Solus, with the docker container. 
uname -a : Linux d10639613af9 4.14.14-47.current #1 SMP Fri Jan 19 20:06:03 UTC 2018 x86_64 GNU/Linux

rustc -V: rustc 1.24.0-nightly (7eb64b86c 2017-12-20)

git rev-parse HEAD: 604c41ade2d7e9bb09a1eb00f57b34b33d5c068d

## Steps to reproduce
1. run docker in interactive mode (failed without docker as well)
2. make all
3. make qemu

- **Proposed solution**:
Add logd to the cookbook.

**Comment by zachlute** [comment]
I fixed this locally when trying to build for the first time, so I went ahead and created a PR.

**Comment by BearzRobotics** [comment]
So after coming back and checking I seen that @zachlute patch was merged. After updating the cookbook it building fine. So I'm going to close this.
