### ISSUE TITLE
Compile time error

### ISSUE THREAD

**Issue by BearzRobotics** [redox-os/redox#1145]
- [ x] I agree that I have searched opened and closed issues to prevent duplicates.

## Description
The compile fails on the xz recipes.

## Environment info
Ubuntu 16.04, fresh from github.
repo - preparing xz
cook - xz prepare
patching file src/xz/file_io.c
patching file src/common/tuklib_open_stdxxx.c
patching file src/xz/message.c
patching file src/xz/signals.c
patching file src/xz/file_io.c
repo - building xz
cook - xz build
+ autopoint -f
Copying file ABOUT-NLS
Copying file build-aux/config.rpath
Copying file m4/codeset.m4
Copying file m4/extern-inline.m4
Copying file m4/fcntl-o.m4
Copying file m4/gettext.m4
Copying file m4/glibc2.m4
Copying file m4/glibc21.m4
Copying file m4/iconv.m4
Copying file m4/intdiv0.m4
Copying file m4/intl.m4
Copying file m4/intldir.m4
Copying file m4/intlmacosx.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/inttypes_h.m4
Copying file m4/lcmessage.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/lock.m4
Copying file m4/longlong.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/printf-posix.m4
Copying file m4/progtest.m4
Copying file m4/size_max.m4
Copying file m4/stdint_h.m4
Copying file m4/threadlib.m4
Copying file m4/uintmax_t.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
+ libtoolize -c -f
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
+ aclocal -I m4
main::scan_file() called too early to check prototype at /usr/local/bin/aclocal line 644.
+ autoconf
+ autoheader
+ automake -acf --foreign
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/local/bin/automake line 4159.
configure.ac:537: require Automake 1.12, but have 1.11.6
./repo.sh failed.mk/filesystem.mk:2: recipe for target 'build/filesystem.bin' failed
make: *** [build/filesystem.bin] Error 1

Replace me
- Linux redox 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`Replace me`
- rustc 1.25.0-nightly (bd98fe0c0 2018-02-06)

## Steps to reproduce
1. git clone the repo
2. make all

**Comment by slump64** [comment]
Update your distribution.
Also there's plenty of automake versions, pick whichever you want that is higher than 1.12:
http://ftp.gnu.org/gnu/automake/

**Comment by BearzRobotics** [comment]
thanks that fixed it.
