### ISSUE TITLE
W^X for Redox-OS?

### ISSUE THREAD

**Issue by redox-questions** [redox-os/redox#1157]
https://en.wikipedia.org/wiki/W^X

W^X ("Write XOR Execute"; spoken as W xor X) is a security feature in operating systems and virtual machines. It is a memory protection policy whereby every page in a process's or kernel's address space may be either writable or executable, but not both. Without such protection, a program can write (as data) CPU instructions in an area of memory intended for data and then arrange to run (as executable) those instructions. This can be dangerous if the writer of the memory is malicious.

Will Redox OS use them by default & mandatory?

Thanks.

**Comment by jackpot51** [comment]
Redox already uses W^X: https://github.com/redox-os/kernel/blob/master/src/syscall/process.rs#L605
