### ISSUE TITLE
Never support PAM, use BSD Authentication instead

### ISSUE THREAD

**Issue by redox-questions** [redox-os/redox#1160]
"PAM is a pretty ugly set of hacks, frankly, and the Linux implementation is actually quite gross. "

Use BSD Authentication instead: 
https://en.wikipedia.org/wiki/BSD_Authentication
https://man.openbsd.org/authenticate.3

Will Redox OS use the safer BSD auth? 

Thanks.

**Comment by jackpot51** [comment]
We are not using either
