### ISSUE TITLE
Driver separation in Redox-OS?

### ISSUE THREAD

**Issue by redox-questions** [redox-os/redox#1163]
Examples for driver separations: 

- touchpad drivers shouldn't have to do anything with network access
- wireless drivers shouldn't be able to touch anything from ex.: /home
- graphics/wireless/sound/disk/etc. drivers shouldn't be able to get anything from keyboards
- microphones shouldn't have to do anything with network access

Since Redox is a microkernel, maybe it would be easier to implement this mitigation. 

Will Redox OS use it?

Thanks.

**Comment by xTibor** [comment]
They are already separated using a concept called null namespaces. The driver processes enter this namespace after they done their initialization, after that they are unable to open any new files on the system and they cannot leave this state.
