### ISSUE TITLE
Will Redox-OS use privilege separation by design? 

### ISSUE THREAD

**Issue by redox-questions** [redox-os/redox#1164]
https://en.wikipedia.org/wiki/Privilege_separation

In computer programming and computer security, privilege separation is a technique in which a program is divided into parts which are limited to the specific privileges they require in order to perform a specific task. This is used to mitigate the potential damage of a computer security vulnerability.

Privilege Separation examples: 
Qmail
Postfix
OpenSSH
And.... Chrome

Will Redox OS use it in general? 

Thanks.

**Comment by jackpot51** [comment]
It already has privilege seperation
