### ISSUE TITLE
Question: should reading from "rand:" care about a maximum number of fd's

### ISSUE THREAD

**Issue by pitdicker** [redox-os/redox#1172]
In [Rand](https://github.com/rust-lang-nursery/rand) we now store a single file descriptor to `/dev/urandom` in a global static, to avoid running out of file descriptors in some rare cases (encountered by Servo).

Now I tried to find information whether doing the same thing for Redox makes sense, but to be honest didn't spend more then an hour on it. Does Redox have a concept of maximum open file descriptors, and should we care about it when opening `rand:`?

**Comment by jackpot51** [comment]
Yes, this should be a concern. If not for hitting the open file limit, it should be a concern for wasting kernel and randd memory. Redox has an open file limit

**Comment by pitdicker** [comment]
Thank you!
