### ISSUE TITLE
How to Pronounce Redox

### ISSUE THREAD

**Issue by CleanCut** [redox-os/redox#1187]
I apologize if this is already documented somewhere and my searches missed it, but how is Redox pronounced?

I am giving both a [talk](https://conferences.oreilly.com/oscon/oscon-or/public/schedule/detail/67048) and a [half-day tutorial](https://conferences.oreilly.com/oscon/oscon-or/public/schedule/detail/67116) on Rust this summer, and I'm fairly confident I will be mentioning Redox at least once.  It would be nice if I could use the correct pronunciation, assuming there _is_ a canonically correct pronunciation.

So, is it `red ox` as in the [apparent mascot](https://github.com/redox-os/redox/pull/595) that is  red, or `reed ox` as in [oxidation-reduction](https://www.merriam-webster.com/dictionary/redox) from which the logo appears to be derived (more _punny_ but less guessable)?

**Comment by jackpot51** [comment]
reed ox is correct

**Comment by CleanCut** [comment]
👍 Thanks!
