### ISSUE TITLE
I think redox's softwares should be prefixed by 'r' alphabet

### ISSUE THREAD

**Issue by sackery** [redox-os/redox#129]
e.g.
rplayer  > media player
rmanager  > files manager
ruber  >

**Comment by hauleth** [comment]
I think not. Table of elements is big enough to cover all our needs.

**Comment by jackpot51** [comment]
Yeah, we should use the names of elements and molecules

I really don't think this would be accepted well

**Comment by hauleth** [comment]
And chemical prosesses (fire i. e.)

--
Łukasz Jan Niemier

Dnia 13 paź 2015 o godz. 15:17 Jackpot51 <notifications@github.com> napisał(a):
