### ISSUE TITLE
Redox naming

### ISSUE THREAD

**Issue by bubnenkoff** [redox-os/redox#138]
I thought about OS name. It's fine, but I think that the better name is possible. For example I like names like: RedOS (or something like this), because redOX-OS have at end "OX-OS" that for me looks not very good.

**Comment by stratact** [comment]
There is a reason why it's called [Redox](https://en.wikipedia.org/wiki/Redox), and apparently, it being a pun on the primary language's name (even though named after the Fungus, not the chemical reaction).

Also there is a reason why the official Redox software is named after chemicals and reactions, such `oxide`, `fired`, and `ion`. So changing the name would not be justifiable.

When you think about the term `redox` being a reaction of travelling electrons, what better name and metaphor to refer to digital computing in general? I'm sure the naming has been well thought out by @jackpot51.

**Comment by hauleth** [comment]
To be honest I almost never call it Redox OS, it is just Redox and everybody know what I mean (even my non-IT girlfriend). So I don't see this as an issue.

**Comment by stratact** [comment]
to add what @hauleth said, just like when you talk about Windows, people know you're talking about the OS, not actual windows.

**Comment by jackpot51** [comment]
*Redox* is the prefered name for the entire OS
