### ISSUE TITLE
KeyEvent::from_event().character is '\0' when it actually should be a unicode input code.

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#147]
Backspace -> '\0', even though it should be '\u{0008}'

Shift -> '\0', even though it should be '\u{000E}'.

etc.

**Comment by Ticki** [comment]
For the track, I'm writing a patch.

**Comment by Ticki** [comment]
Patch #148 fixes this.

**Comment by jackpot51** [comment]
There is a reason for this. KeyEvent.scancode has the code for non-printable characters, and character is set to \0.

K_BKSP and K_SHIFT are the values that scancode will be set to.

**Comment by Ticki** [comment]
The thing is that it would structure the code more. Also, they might not be printable but that have a char.

**Comment by jackpot51** [comment]
Seperating the control characters and printable characters allows an app to not have to process all control characters.

match event.character {
   '\0' => //Process control characters
   _ => //Append printable character
}

**Comment by Ticki** [comment]
I see. I like the idea.

**Comment by jackpot51** [comment]
http://www.computer-engineering.org/ps2keyboard/scancodes1.html

This is where the scancodes are defined.

**Comment by Ticki** [comment]
I'm convinced. :)
