### ISSUE TITLE
Support green threads

### ISSUE THREAD

**Issue by zonyitoo** [redox-os/redox#149]
Rust does not support green threads officially, and the `std::io` and `std::net` are built for blocking I/O. But green threads should be an implementation detail, so it is possible to just switch the `libstd` (let `rustc` link another `libstd`) and make it uses green threads under the hood. Then that Rust application will run with green threads without modifying anything.

Green threads are very helpful to build I/O bound applications, such as servers. Although you can always build an application by writing a state machine, or using callback style APIs. But the first method is hard to manage and it is not an easy job to do it well, and the second one will cause callback hell, your code will be teared apart into small pieces.

Green threads will not help to boost performance, but it is very helpful to build an I/O bound application. The simplest server model is one thread per connection. But because of using native threads are too heavy, we cannot do that in almost all realistic use cases, and green threads could help to solve this problem instead.

Things need to be done in the kernel:

1. Non-blocking I/O, including async file I/O and non-blocking socket I/O. It would be better if they have unified APIs.
2. I/O multiplexer (Eventloop). Something like Epoll, Kqueue or IOCP.

Things need to be done in the user-space:

1. Basic supports of green threads, including context-switch, channels (lock-free queues), Mutex, Condvar, `thread_local` (green thread local) and the others.
2. Green threads' non-preemptive scheduler. This scheduler should be able to use multiple CPU cores with M:N model.
3. A special version of `libstd`, which will make all I/O calls to be handled by the green thread library. `thread::spawn` will spawn a green thread instead of a native thread.

**Comment by Ticki** [comment]
:+1:

**Comment by ambaxter** [comment]
I really like the idea. 

However, my main concern remains that a special version of libstd, monkey-patched in at runtime, is probably not the best way to go. I've been bitten by similar situations and I'm loath to introduce that particular bit of insanity as a standard feature.

**Comment by zonyitoo** [comment]
I think it is the only way to make all dependencies to use green threads without changing anything. What's the problem when you are using that in your lib? Could it possible to bypass or be fixed?

**Comment by ambaxter** [comment]
Monkey-patching changes expected behaviors in ways that applications and their dependencies do not account for. In cases where some underlying library is changed out from underneath the application, subtle bugs inevitably creep in.

**Comment by zonyitoo** [comment]
I see. In that case, users should not use green threads because that will break their application. Or they have to change their code to make it work...
