### ISSUE TITLE
Getting started with redox-os

### ISSUE THREAD

**Issue by NobbZ** [redox-os/redox#150]
Since I wanted to contribute somehow as a practical sideproject to the upcomming "building operating systems"-lectures this semester, I wanted to checkout redox-os, take a look at it, play around and perhaps contribute.

But one of the biggest problems is the following:

After building with ``windows/make all`` and then starting with ``windows/make virtualbox`` I do only see the following in my VirtualBox:

![redox-desktop](https://cloud.githubusercontent.com/assets/58951/10564511/a0dd685a-75b7-11e5-8741-beb12a610bd5.png)

When I hit CTRL-F1, I come back to the startup output and see the following content:

![redox-bootscreen](https://cloud.githubusercontent.com/assets/58951/10564515/bad973a2-75b7-11e5-8a51-6df95ad789fa.png)

From the first screen, I can move the mouse around, but nothing else happens, even after an hour of waiting. How can I get at least to the stage of a usable desktop as shown in the Screenshot from the README.md?

![https://github.com/redox-os/redox/raw/master/img/screenshots/Desktop.png](https://github.com/redox-os/redox/raw/master/img/screenshots/Desktop.png)

**Comment by jackpot51** [comment]
Make sure your git newlines are \n and not \r\n

**Comment by jackpot51** [comment]
See #111

**Comment by NobbZ** [comment]
Yeah, following the advice in #111 I was able to compile and run. I hunted the issue down a bit and found about the possibility to configure this behaviour via ``.gitattributes``-file, so I sent a PR with an appropriate ``.gitattributes``.
