### ISSUE TITLE
build fails on Mac OS X El Capitan

### ISSUE THREAD

**Issue by sumproxy** [redox-os/redox#165]
Here's the output log:
```
mkdir -p build/x86_64
rustc --target=x86_64-unknown-redox.json -C no-prepopulate-passes -C no-vectorize-loops -C no-vectorize-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A deprecated -L build/x86_64 -C ar=x86_64-elf-ar -C linker=x86_64-elf-linker -o build/x86_64/libcore.rlib rust/libcore/lib.rs
error: could not exec `x86_64-elf-ar`: No such file or directory (os error 2)
make: *** [build/x86_64/libcore.rlib] Error 101
```

**Comment by Lacaranian** [comment]
Does the build work correctly with ARCH=i386 set in the makefile?

It seems that the archive utility specified for the rust compiler to use is set by the following snippet from the makefile `-C ar=$(ARCH)-elf-ar`, which depends on the architecture set early on.

**Comment by sumproxy** [comment]
Well I get a bunch of warnings, but it does work. Do you still plan to get the x86_64 build working?

**Comment by ambaxter** [comment]
I was playing around with this earlier this week. There is an up-to-date x64 elf-ar out there, but that repo doesn't have a working i386. I'm going to fork the repos this weekend to have both.

**Comment by esell** [comment]
if you are using homebrew and building for x86_64 you can use the following:

        brew tap sevki/homebrew-gcc_cross_compilers
        brew install sevki/gcc_cross_compilers/x86_64-elf-binutils

if you have the i386-elf stuff installed you'll likely have to manually link/unlink. i'll see if i can come up with a scriptable solution that allows building i386 AND x86_64 via homebrew...

**Comment by sumproxy** [comment]
```
make all
mkdir -p build/x86_64
rustc --target=x86_64-unknown-redox.json -C no-prepopulate-passes -C no-vectorize-loops -C no-vectorize-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A deprecated -L build/x86_64 -C ar=x86_64-elf-ar -C linker=x86_64-elf-linker -o build/x86_64/libcore.rlib rust/libcore/lib.rs
rust/libcore/nonzero.rs:58:20: 58:25 error: expected one of `extern` or `fn`, found `const`
rust/libcore/nonzero.rs:58         pub unsafe const fn new(inner: T) -> NonZero<T> {
                                              ^~~~~
make: *** [build/x86_64/libcore.rlib] Error 101
```
That's what I'm getting now with 1.4 rust after installing x86_64-elf-binutils

**Comment by NobbZ** [comment]
Redox does only compile using rust nightly builds, so you need to install 1.6 either as [64 Bit](https://static.rust-lang.org/dist/rust-nightly-x86_64-apple-darwin.pkg) or [32 Bit](https://static.rust-lang.org/dist/rust-nightly-i686-apple-darwin.pkg) variant, whichever suits you best (probably the first one; just linking both for future reference and mac users).

**Comment by sumproxy** [comment]
```
~/Projects/rust/redox> make all
mkdir -p build/x86_64
rustc --target=x86_64-unknown-redox.json -C no-prepopulate-passes -C no-vectorize-loops -C no-vectorize-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A deprecated -L build/x86_64 -C ar=x86_64-elf-ar -C linker=x86_64-elf-linker -o build/x86_64/libcore.rlib rust/libcore/lib.rs
rust/libcore/nonzero.rs:58:20: 58:25 error: expected one of `extern` or `fn`, found `const`
rust/libcore/nonzero.rs:58         pub unsafe const fn new(inner: T) -> NonZero<T> {
                                              ^~~~~
make: *** [build/x86_64/libcore.rlib] Error 101
~/Projects/rust/redox> rustc --version
rustc 1.6.0-nightly (2e07996a9 2015-10-29)
~/Projects/rust/redox> 
```
Same output with nightly

**Comment by NobbZ** [comment]
I hade the same issue with an older nightly about a week ago, after
upgrading it worked. But that was windows. Don't have a mac at hands.

Sum Proxy <notifications@github.com> schrieb am Fr., 30. Okt. 2015 14:53:

**Comment by sumproxy** [comment]
The nightly I used is only one day old (2015-10-29, see above), so I have no clue what to think.

**Comment by jackpot51** [comment]
Are you sure you are up to date with master?

**Comment by sumproxy** [comment]
Yeah, that was it.
