### ISSUE TITLE
A proposal for Redox configuration system

### ISSUE THREAD

**Issue by tennix** [redox-os/redox#172]
Traditional *nix system has config files everywhere and in different formats. That's a headache for users. For simplicity I think Redox should have a central place to store configs and in a transparent format, that is it should be easy for users to find their configs and read/write easily without special tools.

Due to everything is a URL in Redox, and inspired by [Etcd](https://github.com/coreos/etcd). I think Redox can have following URLs to config the whole system.

system config `config://pkg-name/version/system/key/value`
user config `config://pkg-name/version/username/key/value`

for example _git_ config should be organized as following:

```
config://git/2.3.8/system/core.editor/vim
config://git/2.3.8/tennix/core.editor/emacs
```

That way it's easy to read and set a configuration item. For example if we serve configs as http resource, we can use curl to get and set an item just like in etcd.

But the problem is that we can no longer comment our configurations for documentation purpose.

For this we have two solutions:
- make doc as a key in configuration

```
config://pkg-name/version/system/doc/index.html
config://pkg-name/version/username/doc/index.html
```
- make doc as a new scheme

```
doc://pkg-name/version/system/index.html
doc://pkg-name/version/username/index.html
```

Either way docs are normal text files but rendered as html for better read. Redox can provide some basic converters to convert common markup doc like rst/md to html, and users can provide their own doc converters if needed.

Since everything is URL, we can easily get all configurations and render them in a webpage. And what's more, we can even config our system in a web browser just like Firefox's _about://config_ and Chrome's _chrome://settings_

For compatibility with current *nix software, we can map these urls to their current file config. Or just specify the config file path as a key in the url like `config://git/2.3.8/tennix/configpath//home/tennix/.gitconfig`

Of course the file path `/home/tennix/.gitconfig` should be encoded as safe url here, but that's not the main point here.

Besides with proper permissions, we can share our configuration to others. And if we want, we can even import other systems' configuration in the same network. Just like mount a remote filesystem to local machine, we "mount" remote system's settings as local settings.

Some problems:
- How to sync comment with config?
- A proper permission model
- ...

**Comment by Ticki** [comment]
I'm against encoding all the data in the URL. I would rather send the data to the URL to prevent parsing it multiple times.

**Comment by ambaxter** [comment]
I've a few ideas:

1) It shouldn't be a hive file, like the Windows Registry. On the file system, these should just be plain text files. If one of them happens to get vaporized, everything should continue as normal. In fact, I think it'd be important that any file locks be dropped as quickly as possible. Blowing away a bad configuration file is sometimes the only recourse to fixing an application.

2) What happens when we need to back-up the config file? Version it? On the file system I'd just copy the file somewhere else. What about here?

3) What recourse does the user have when the config service goes down? Is the entirety of the userspace borked?

**Comment by layered-esell** [comment]
The idea at a high level sounds cool but I tend to be afraid of needing another app/system to make something core to the OS work, `curl` in this example. Yes you typically need a text editor to update configs on a *nix system but in a pinch you can use something like `echo >>`.

Would it make sense to have some kind of lightweight config management tool that worked similar to curl but was more redox specific (permissions support, import/export features, etc)?

My other fear is how much overhead comes with having this system work with existing tools. Something like the Apache HTTP server comes to mind where there are multiple levels of subdirectories under the root in /etc, not to mention the symlinks and what not that are used to enable sides and modules.

**Comment by stratact** [comment]
Well, I had the idea of separating other OS configuration files in their own parent directory for compatibility support, such as:
```
config://linux/system/* <-- Linux-specific global configs like `/etc`
config://freebsd/system/* <-- FreeBSD-specific, same idea as above.
config://linux/user/foo/* <-- Linux-specific user configs (but can override the config://linux/system)
config://freebsd/user/foo/* <-- FreeBSD-specifc, same idea as above.

```
to be separated from Redox configs
```
config://system/*
config://user/foo/*
```

**Comment by ambaxter** [comment]
In theory, applications shouldn't know about the operating system. How would this look like from the application perspective?

**Comment by NobbZ** [comment]
> In theory, applications shouldn't know about the operating system.

In practice we can never get to that. An Application already needs to know if it is windows or linux, just to know if it has to put its stuff to `$HOME` or `%APPDATA%`. Even worse, under Windows the path `/foo/bar` can mean something different, depending on which drive was active when calling that program. The program even should know about something about the OS when naming files... Writing to "Config" and reading from "config" might work under some OSs.

Most of this stuff can already decided by compiletime, still the programmer needs to know about these differences. We can make life easier by providing some wrappers, but it will be impossible to serve the whole world in a way that it is satisfied, so lets try it our way.

**Comment by imp** [comment]
I am all n favor of leaving configuration files behind and migrating toward programmable configuration. Consider, for example, REST-like interface to change and query (no less important!) configuration. etcd is fantastic example of what can be achieved in this realm. Too bad it is in go.

**Comment by jawbonegroove** [comment]
I like this idea, and also am generally in agreement with @ambaxter and @ticki here. I think...

application programmers should be potentially even able to pull configs from other apps; this makes importing simple and things like intuitive ui settings more feasible. give the system admin (even just at compile time) versatile control over a system-wide default or standard (more consistent than *nix) with flexible user control (not a registry). in the end though, configs are 100% at the mercy of the application programmer. they can be anywhere from ascertained at run time or hidden in a binary blob. I think it may cut down on convoluted coding to offer/encourage app devs as much (read) acess to other configs as securely possible. for writing configs, a redundant or original backup, or last known good config, is up to the dev...they should have a secure place to put those (i.e. @stratact's example); the sysadmin should be able copy one of those out to "public" config:// domain in case of oops.

I don't like the idea of a running config service or cache. it seems like needless overhead and might just open loopholes. if an app needs configs cached, the app can handle that. if it needs access to potentially sensitive system configs, let the sysadmin punch holes for it more or less explicitly...again, maybe even just as a compile time macro.

**Comment by jawbonegroove** [comment]
(afterthought)

when an app is installed it gets a config:// which it may or may not use. like so...

[CODE]config://foo/1.23-4/
config://foo/doc/
config://foo/private/
config://foo/private/secure/
config://foo/private/secure/keyfile[/CODE]

where a key is generated for read access to files in private/ (not descending, would follow that there would be a unique key for each subdir) ; that key may then be imported to, say, config://bar/private/secure/keyfile so that the bar app can read defaults/backups from config://foo/private/ as well as config://foo/

now, the contents of each of these directories should be symlinks/pointers/somesuch to individual files in the app's data dir, which other apps should have no direct access to.

also, Freud says I like the idea of putting docs in config:// land.

**Comment by jackpot51** [comment]
I prefer the traditional use of files in file:/etc/

**Comment by stratact** [comment]
@jackpot51 could we rename it to `file:/config/` instead? I really find the use of `etc` to be archaic and not as meaningful.

**Comment by jackpot51** [comment]
@stratact Sure thing. I prefer something in the filesystem is all

**Comment by joehillen** [comment]
@stratact I do configuration management for a living, please don't change stuff for the sack of changing it. My job is hard enough as it is.

**Comment by jackpot51** [comment]
To anyone who would like to discuss this, I propose creating an RFC here: https://github.com/redox-os/rfcs

We will be trying to move these kinds of issues, which are more theoretical and require a lot of discussion, to RFCs
