### ISSUE TITLE
A proposal for strongly typed resource identifier (draft)

### ISSUE THREAD

**Issue by zonyitoo** [redox-os/redox#180]
Redox is outstanding because it introduces the concept of "Everything is an URL". But because URL is a well known word, which particularly refer to IANA URL, so would be better to use a different protocol with different name, refer to #175 .

But CURIE is actually a String, which makes it impossible to validate in compile time. So to make use of type checking, I propose to use a strongly typed resource identifier.

## Key Points

1. Use CURIE as a stringify method of the resource identifier.
2. Resource identifier and transfer protocol is strongly typed.
3. Make good use of Rust's type system.

## Proposed Resource Identifier

**NOTE: This may be completely wrong, please just stick to the key points.**

Let's name this Resource Identifier as `Ri` (abbreviation of Resource Identifier), and it could be defined as

```rust
trait Ri<'a>: Curie {
    type Provider: Resource + CurieScheme;
    type Reference: CurieReference;
    type Parameter: CurieQueryString;
    type Fragment: CurieFragment;

    type Input: Sized;
    type Output: Sized;

    type Error: Sized;

    fn provider(&'a self) -> &'a Self::Provider;
    fn reference&'a self) -> &'a Self::Reference;
    fn parameter(&'a self) -> &'a Self::Parameter;
    fn fragment(&'a self) -> &'a Self::Fragment;

    fn read(&mut self) -> ReaderIter<Input>;
    fn write(&mut self, output: Self::Output) -> Result<(), Self::Error>;

    fn from_curie<'a>(curie: &Curie<'a>) -> Self;
    fn to_curie(&self) -> CurieBuf;

    // Compact serialization
    fn serialize(&self, w: Write) -> io::Result<()>;
    fn deserialize(r: Read) -> io::Result<Self>;
}
```

### Could be converted from/to CURIE formatted string

The definition matches the definition of CURIE syntax

```
provider:reference?param1=1&param2#fragment
```

so `Ri` could always be serialize/deserialize to/from CURIE formatted string.

Also it is a good way to provide FFI interface for other languages to call.

### Resource Protocol

All resources have a well defined **provider**, so the data transfer protocol is already defined by the **provider**. Such as the `file` provider could `read` and `write` a `[u8]`, `http` provider could `read` a `HttpRequest` and `write` a `HttpResponse`.

So the author of that resource provider will need to restrict the input and output protocol by defining `Input` and `Output` data structure.

## Note

This is just a draft propoal, implementation detail should be discussed further.

There are at least the following problems to be solved

1. Performace. Using strongly typed definition may involve performance issue, it needs to be designed properly.
2. FFI compatible. Because Redox is an OS, so the APIs will be called from various programming languages, but strongly typed APIs in Rust will become an obstacle for the other languages.

**Comment by Ticki** [comment]
:+1:

**Comment by Ticki** [comment]
My idea is that we use a dual model which (de)serialises URLs to two formats (defined via a trait), respectively:

1) A readable format, namely CURIEs. This format allows the user to be able to read and write requests by hand. On the other side, only using this gives a quite big drawback, namely performance. There are two reasons for this: 1) redundancies: nearly every URL contain redundancies, given that these greatly expands the size of the data (which have to be passed across threads and processes!). 2) parsing: this gives quite a big overhead, due to constantly having to reparse the URLs (for example, paths or other data contained in the URL). Because of these drawbacks, we need an internal representation:

2) A compact serialization: The internal representation is defined solely by the author of the scheme (the scheme provider). This is expected to be done highly efficient, but *not readable*. This internal representation is used by the kernel and IPC. In this way, we hopefully avoid overhead.

So what I suggest is a hybrid solution between readable and efficient representation.

**Comment by zonyitoo** [comment]
Some thoughts:

1. If we only got a CURIE formatted string, how could we construct the corresponding struct? For example:

```rust
let curie_string = "provider:somedata?p1=1&p2=2";
let resource_handle = ...;
```

How could we get the resource handler from the string?

2. If we programming in Rust, then

```rust
// This call may actually do under the hood
//     1. Ask the kernel who is the provider of "file" scheme
//     2. Construct a request struct with `reference`, `params`, `fragment`
//     3. Send it to that process (provider)
//     4. Wait for the reply, which will give me a handle of the resource
let open_file = FileResource::new(reference, params, fragment);

let mut buffer = [0u8; 1024];
open_file.read(&mut buffer).unwrap();
```

The problem here is step 4. The resource provider will gives back a handle of that requested resource, how to implement that?

**Comment by LazyOxen** [comment]
I also think we should have a dual system, but I was thinking about it differently.

I was thinking that CURIEs could be used to access things exposed by a certain scheme, and data is written to or read from those CURIEs. 

The data written would be in either a readable or compact serialization.

For example, say you have a window and you want to change it's width, you could do something along the lines of: 
```
window.write_text_to_url("/width", "345" )
// whatever binary data you want, the receiving path would interpret the data
window.write_to_url("/width", width_var) 
```

I think the readable format could be especially useful on the command line, or if somebody wants to do some quick code without worrying about efficiency. As @Ticki said, there's the overhead of parsing strings, so I don't see a way to get around that.
```
# let me see all the windows!
ls window:*
# make the window title "Cake!"
echo "Cake" | window:3/title
```

So essentially, you open a CURIE (basically like a file path) and then read/write either using text or binary data.

**Comment by zonyitoo** [comment]
@LazyOxen But CURIE also defines query strings and fragments. That maybe useful sometime.

```
# let me see all the windows which are created by chrome
ls window:*?created-by=chrome
# open a file and skip the first 10 bytes
cat file:/path/to/file#offset-10
```

But for the Rust programmers, they can get the resource handle in strongly typed Rust code instead of serializing it to a CURIE string (which is weakly typed), so that the overhead of parsing strings could be avoided.

```rust
let reference = WindowResRef::new(3, WindowElement::Title);
let handle = WindowResource::open(reference).unwrap(); // sends to the "window" provider
handle.write("Cake");

let res = HttpRes::new("reddit.com", "/r/rust");
let param = HttpParam::new(HttpVersion::20);
let handle = HttpResource::open(res, param).unwrap();
let request = HttpRequest::new(...);
handle.write(request);

let resp = handle.read().unwrap();
```

**Comment by Ticki** [comment]
@zonyitoo The trait should also provide methods to (de)serialize the readable strings.

**Comment by zonyitoo** [comment]
@Ticki Updated the definition

**Comment by stratact** [comment]
Since we already learned that syscalls are weakly typed by nature as quoted by @jackpot51 here:

> There is simply no way to go from ring 3 to ring 0 code without either the int or syscall asm instructions. These allow for passing things on the stack or in registers as pointers or pointer sized arguments. References are not possible, and strong typing is discouraged. URLs are currently passed as byte arrays containing UTF8 that terminates in 0, exactly as paths are passed in the Linux and BSD ABIs. The recommendation I have is that the minimal syscall code is heavily inspected, and that safety is established with minimal unsafe scope

and since we now have GetSlice, which does bounded slice abstraction (at runtime), so that there is no concern for panicking in kernel space, is there any need to keep this open?
