### ISSUE TITLE
Redox shell and Red

### ISSUE THREAD

**Issue by bubnenkoff** [redox-os/redox#196]
I think it would be good to try use as shell language Red http://www.red-lang.org/
it's much more powerful then bash, and have very low footprint

**Comment by Ticki** [comment]
We have agreed to use LuaJIT for scripting. Lua is also already ported to Redox.

**Comment by bubnenkoff** [comment]
But could you also look at Red? It have a lot very nice futures that makes its very good for shell

**Comment by jackpot51** [comment]
Taking a look at it now

**Comment by Ticki** [comment]
Personally, I don't think Red fits well for shell scripting. My biggest concern is that it's incomplete.

**Comment by Ticki** [comment]
(It lacks of ecosystem, and the language itself still needs lots of features: (link)[http://www.red-lang.org/p/roadmap.html])

**Comment by bubnenkoff** [comment]
@Ticki it's under active developing look it's github. One year ago Rust also was incomplete.

**Comment by Ticki** [comment]
Well, Rust were pretty complete one year ago, comparing it to Red. Red still lacks of:

- File I/O
- Network I/O

These are probably the most important things for a shell scripting language.

Futhermore, the GC is buggy and incomplete.

**Comment by hauleth** [comment]
One of reasons why Lua is that LuaJIT is one of fastest scripting language implementations available. Also I think that we should focus on our own Ion.

**Comment by stratact** [comment]
@hauleth also, wasn't the Fish shell the main inspiration for Ion, since it has the most modern features while being lightweight. Or did those plans change?

**Comment by Ticki** [comment]
In the #ion slack channel, we discussed the design of Ion. It's inspired mainly by fish, but also zsh.

**Comment by hauleth** [comment]
@stratact yeah, why do you asking?

**Comment by stratact** [comment]
Just for clarification on what's current.

**Comment by stratact** [comment]
I suppose this issue could be closed?

**Comment by Ticki** [comment]
@jackpot51 can you close this?
