### ISSUE TITLE
Window management: change position/size/title

### ISSUE THREAD

**Issue by nounoursheureux** [redox-os/redox#199]
AFAIK right now `orbital` cannot change the size/position/title of a window, only its content. What would be a good way to transmit the size and position of the window along with the pixels data ?
Maybe we could write commands to the file: 
`move x y`
`resize x y`
`set_title title`
`flush content`
But the kernel would have to parse it every time a window is updated so I don't know if this is a good solution.
What do you think ?

**Comment by jackpot51** [comment]
There is a packet protocol specified for orbital that would address this, https://github.com/redox-os/redox/wiki/Orbital
