### ISSUE TITLE
Move repo to organisation

### ISSUE THREAD

**Issue by hauleth** [redox-os/redox#21]
As you created organisation for Redox development, you could move that repo to it.

BTW this is great project and I really appreciate your invitation to became part of it.

**Comment by jackpot51** [comment]
It has been moved. Everyone is on read permissions until I figure out what the permissions mean. Changes can be submitted via pull request.

I need some suggestions about write access, it is usually very conflict-laden if a repo has more than one user pushing to the master.

**Comment by hauleth** [comment]
I have some knowledge. We can discuss it here, on IRC or via mail. Choose just write me.

BTW what you think about forum/mailing list to discuss project matters/designs?

**Comment by jackpot51** [comment]
Here is good. I will create a forum at redox-os.org soon, for now, designs can be discussed as github issues.

**Comment by jackpot51** [comment]
https://redox-os.org/forum/

**Comment by hauleth** [comment]
Why not [Discourse](https://www.discourse.org/) which Rust community use. It is quite modern platform with a lot of nice features. phpBB2 should vanish in darkness of history.

**Comment by jackpot51** [comment]
Sure, I didn't like phpbb, I had just used it before. It's coming down, bringing up discourse

**Comment by Ticki** [comment]
This issue can be closed.

**Comment by Ticki** [comment]
How do you close issues?

**Comment by hauleth** [comment]
It is my issue, so I can close it.

**Comment by Ticki** [comment]
I see.
