### ISSUE TITLE
Filesystem

### ISSUE THREAD

**Issue by jackpot51** [redox-os/redox#22]
This is a critical and massive piece of the system that has not been fully developed. At present, it has a single level node list, that contains the names and locations of every file. This entire list is loaded into memory when the system boots. The filesystem cannot be modified.

To fix this, there are a few options:
- Adopt another filesystem, and implement it.
- Fix the current filesystem by modifying the layout. This would likely involve:
 - Make the node list hierarchical
 - Add a free block list
 - Synchronize the filesystem with disk when a dirty flag is set
 - Online defragmentation

**Comment by hauleth** [comment]
I would vote for using existing file systems. I would try to choose between modern FSes, my list:

- [Btrfs](https://en.wikipedia.org/wiki/Btrfs)
- [ext4](https://en.wikipedia.org/wiki/Ext4)
- [ZFS](https://en.wikipedia.org/wiki/ZFS)

All aof them are quite modern FSes and provide a lot of nice features. I would vote for ZFS as is IMHO the best option for the future.

**Comment by stratact** [comment]
:+1: on ZFS support

**Comment by jackpot51** [comment]
One important thing about ZFS is that it is CDDL licensed. This license is compatible with MIT, which is Redox's license, but not GPL.

BTRFS has better support on Linux, ZFS has better features (at the moment)

**Comment by hauleth** [comment]
About Linux support I've created #25. As far as I can see Redox is MIT licensed and IMHO it is as it should be.

Also if we would implement ZFS from the ground then we can license it as we want. CDDL license is valid only for Sun implementation.

**Comment by jackpot51** [comment]
I agree with the MIT license. We are all developing on Linux systems, and if ZFS-FUSE is good enough for us to create the boot disks in Linux, I would completely support implementing ZFS as the default filesystem in Redox.

**Comment by hauleth** [comment]
More FSes could be added in the future, but IMHO ZFS as the first default FS would gather us a lot of attention which is what we need now.

**Comment by jackpot51** [comment]
Choosing ZFS and moving discussion to #26
