### ISSUE TITLE
Has Redox been run on bare metal yet?

### ISSUE THREAD

**Issue by RobertWHurst** [redox-os/redox#221]
This looks like a very exciting project. I'm really impressed with the speed Redox seems to be evolving at. I'm curious, has Redox been run on bare metal yet?

**Comment by jackpot51** [comment]
It sure has, read about my test rig here: http://dictator.redox-os.org/index.php?controller=post&action=view&id_post=5

**Comment by RobertWHurst** [comment]
@jackpot51 That's very exciting. I'll have a read :)

**Comment by Ticki** [comment]
@RobertWHurst, you can actually try this yourself. Do make all, then go to `build/i386/`, and do `dd if=harddrive.bin of=/dev/sdc`. Change `/dev/sdc` to your usb.

**Comment by RobertWHurst** [comment]
@Ticki Very cool. I'll do that :)
