### ISSUE TITLE
Build Fails On Windows

### ISSUE THREAD

**Issue by iluxonchik** [redox-os/redox#228]
When running `windows/make.exe virtualbox` the build fails, with the following errors:

```
windows/mkdir -p build/i386
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json -C no-prepopulate-passes -C no-vectorize-loops -C no-vectorize-s
lp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead_code -A deprecated -L build/i386 -o build/i386/libcore.rl
ib rust/libcore/lib.rs
rust/libcore\nonzero.rs:58:19: 58:25 error: expected identifier, found keyword `unsafe`
rust/libcore\nonzero.rs:58         pub const unsafe fn new(inner: T) -> NonZero<T> {
                                             ^~~~~~
rust/libcore\nonzero.rs:58:26: 58:28 error: expected `:`, found `fn`
rust/libcore\nonzero.rs:58         pub const unsafe fn new(inner: T) -> NonZero<T> {
                                                    ^~
make.exe": *** [build/i386/libcore.rlib] Error 101
```

**Comment by stratact** [comment]
Do you update your compiler to the latest nightly?

**Comment by iluxonchik** [comment]
@stratact thank you! Should've checked that in the first place. `rustc` wasn't pointing to the nightly build, so what I did is hardcoded the `rustc.exe`'s path in the `Makefile`:

```
RUSTC=RUST_BACKTRACE=1 "C:\Program Files (x86)\Rust nightly 1.6\bin\rustc.exe"

```
Now everything works great.

**Comment by NobbZ** [comment]
You should preferably install multirust and make sure it's executables are
the only rust ones in path, then add an appropriate override for redox
ffolderand revert changes to Makefile. This way you ensure that it will
work for 1.7 out of the box, also you don't have a dirty Makefile then.

ILUXONCHIK <notifications@github.com> schrieb am Di., 3. Nov. 2015 22:32:

**Comment by iluxonchik** [comment]
@NobbZ thank you
