### ISSUE TITLE
String URL parsing vs Types?

### ISSUE THREAD

**Issue by james-darkfox** [redox-os/redox#231]
URLs everywhere! Strings? Not ideal for performance. Has anyone considered using builders? If the usage is the concern, then builder macros can also be used.

If various schemes need to be accepted, then a trait may be used and implemented over the respective types. (This can also be used to restrict inputs with marker traits. I.e. Only accept a context [file, remote, hardware, etc])

One limitation of the sample macro I'm providing here is that we cannot use `//` due to comments.

```rust
let server: Tcp = url!(Tcp:"10.0.0.1"/80);
takes_url(server); // Tcp implements Url
takes_tcp(server);
```

This sample code does not implement full URL parsing but it is a start demonstrating the idea. https://play.rust-lang.org/?gist=af1d8867e0a10feddaaa&version=nightly

Enums could be used to accept different types. I.e. `10.0.0.1 = Ipv4([0u8;4])`, `"hostname" = Host(&'a str)`, `aa:bb:cc:dd:ee:ff = Mac([u8; 6])`, etc.

Files **COULD** be parsed by identifiers; namely. `url!(File:file)` `url!(File:/foo/bar)` but this would limit the dirs/files to having names that are valid identifiers. Alternatively an expression `"/foo/bar-baz"` could be an option too (if not the only option).

**Comment by Ticki** [comment]
This has been discussed *many* ties. We have not reached a full consensus, and we still frequently discuss this subject. Just for the record, we have a number of proposals:

- Using macros as constructers proposed here (earlier proposed in an old issue by me)
- @zonytoo's proposal on typed CURIEs.
- My proposal on two types of serialization, compact and readable.

Just to sum up: The URL does not have any knowledge about parser (it once had, but I rewrote the URL parser), so now everything after the `:` is left to the provider. Thus, we use a weakly typed string, but it has *no extra overhead* if the provider implements it correctly. However, it's often implemented with readable over performance in mind.

On performance, it isn't really that important as URLs are only parsed when the scheme connection are initialized. As such, there'll not be any overhead in sending and recieving messages, when the parsing is done.

cc @jackpot51 
cc @zonytoo
cc @stratact

**Comment by james-darkfox** [comment]
As for the macros; the provider handling the rest of the parsing is trivial. Here `ethernet` `ip` `tcp` and `udp` can share the same parser. Builder tagged structs can also exist to keep the namespaces for the relevant types clean. (I.e. `new` `host` `port` exist on the builder as setters; and may exist as getters on the final object)

```rust
macro_rules! url {
  (tcp: $($tt:tt)*) => { network_url!(Tcp: $($tt)*) };
  (http: $($tt:tt)*) => { http_url!(Http: $($tt)*) };
  (file: $($tt:tt)*) => { path_url!(File: $($tt)*) };
}
```

**Comment by zonyitoo** [comment]
So it is impossible for users to define a custom scheme? Because all possible schemes are defined in the `url` macro.

**Comment by james-darkfox** [comment]
@zonyitoo I already mentioned for traits and trait markers. Specifically for functions taking these schemes. The `url` macro can work with custom schemes. I.e. `($custom_scheme:ident: $($tt:tt)*)` however, I'd opt for the url macro to only know the official schemes. Any user defined schemes can have their own macro. (Which can still use the existing parsers; just like the http one will likely use the path parser internally)

**Comment by stratact** [comment]
> however, I'd opt for the url macro to only know the official schemes.

It's already been decided we won't: #92

And for every scheme, it doesn't make practical sense to stick with `//` just because it's what people are familiar with.

Might as well have the macro which allows user-defined scheme for the appropriate URL/CURIE.

**Comment by james-darkfox** [comment]
@stratact Okay so that would likely be `($custom_scheme:ident: $($tt:tt)*) => { $custom_scheme!($($tt)*) }`

**Comment by jackpot51** [comment]
The design is to use C strings at the syscall level, for language portability.

Any use of macros would be userspace only
