### ISSUE TITLE
Documentation is not up to date

### ISSUE THREAD

**Issue by nounoursheureux** [redox-os/redox#237]
The [docs](https://ticki.github.io/redocs/redox/) that the README points to are not up to date, for example I noticed that `fs::read_dir` or `QuitEvent` are missing (they are quite recent additions).

**Comment by Ticki** [comment]
Will update 'em ASAP.

**Comment by Ticki** [comment]
They're updated now. You can close this.

**Comment by nounoursheureux** [comment]
Thanks ! :+1:
