### ISSUE TITLE
Mouse tracking leaks to applications not in focus

### ISSUE THREAD

**Issue by james-darkfox** [redox-os/redox#244]
When moving the mouse over two instances of the file browser, both overlapping in position this can be observed.

In my testing. The foreground file browser (navigated to `file:/apps/zfs`) lags heavily behind for the mouse focus while the file manager behind it (navigated to `file:/apps`) responds much faster.

I would think that the background window shouldn't know where the position of the mouse is located.

Considering lag with the `file:/apps/zfs`, as an uneducated guess... It looks like the math being calculated to figure out if any items have the mouse hovering over them is more expensive than it should be. I hope that it isn't scanning over all the boundaries for every motion event from the mouse driver?

On a slightly interesting sidenote. You can now open several files at once - just align your selections and double click on them all at once! (Quick stress test **at once**)

**Comment by Ticki** [comment]
Fixed by #359
