### ISSUE TITLE
Rethink Linux compatibility

### ISSUE THREAD

**Issue by hauleth** [redox-os/redox#25]
As I think that we should provide most of Linux system calls I think that we should base more on BSD and Plan9 systems. Their design is IMHO better and are more resistant to breaking changes. I think that Redox should be new well-designed OS but with some flexibility inside.

Breaking 1-1 compatibility should let us to create more modern OS. We should be like Rust itself. Keep some compatibility where it is needed, but throw away thinks that are bargain of our past.

**Comment by jackpot51** [comment]
Plan 9 was the original inspiration. One thing to note is that the syscalls I have implemented have the same numbers on BSD, but the calling API is different. On BSD, the calls are done like so:

syscall:
   int 0x80 or sysenter

push 2 //File descriptor 2
push 6 //Close
call syscall

On Linux, like so:
mov eax, 6
mov ebx, 2
int 0x80

This change is nice, and would need some touches in libc/newlib-redox/......./syscall.c and src/syscalls/call.rs and src/syscalls/handle.rs

**Comment by jackpot51** [comment]
As a side note, FreeBSD supports the linux syscall interface when running an ELF file, which allows for some level of binary portability. The most *major* reason for doing Linux compatible syscalls was to test the behavior of Redox compared to Linux, to see if the implementation was correct.

**Comment by hauleth** [comment]
This could be also simplified if we drop x86_32 support. As it's market share is dropping we should focus on future, which mean that we should focus on x86_64 - main architecture used in modern PCs. Other architectures should be added in the future.

**Comment by jackpot51** [comment]
I have written a 64 bit operating system in assembler, and the benefits of being in 64-bit are pretty huge. However, some of the real hardware that I test on is 32 bit, and it has been instrumental in developing drivers for Redox. At this point in time, if the kernel were to be switched to 64-bit, it would not run on any real hardware.

There are a few things missing, that must be dealt with before being able to switch:
- AHCI support - so that SATA can be used for the root filesystem
- EHCI support, USB support, and support for USB mass storage - so that the root filesystem can be booted from a USB stick

There are some other things that would be nice to have in long mode:
- APIC and IOAPIC support
- ACPI multi-processor table support

**Comment by alexchandel** [comment]
For reference, the elegant [syscalls](http://aiju.de/misc/plan9-syscalls) of Plan 9. Given Plan 9's filesystem-based [API](http://man.cat-v.org/plan_9/4/), especially the audio/video/input [devices](http://man.cat-v.org/plan_9/3/), I can't imagine the need for more than their ~38 syscalls. Their fork() is so flexible they don't need threads.

**Comment by chc4** [comment]
Supporting rumpkernel hypercalls would be interesting, too. Then redox would be able to automatically use OpenBSD's system drivers without programming its own, while still keeping the Rust security by the drivers being in userspace.

**Comment by hauleth** [comment]
@alexchandel it is AWESOME. I would vote for that. We could build Linux-compatible syscalls on top of that.

**Comment by jackpot51** [comment]
Guys, we have most of the plan 9 syscalls implemented. I think it is a more canonical implementation than plan 9 is, so far

**Comment by alexchandel** [comment]
@hauleth The nice thing is, you very rarely see Linux programs directly making syscalls (except for libraries like libc, of course), so source compatibility could be achieved by linking with some "Linux/Posix emulation layer", similar to Plan 9's APE.

**Comment by alexchandel** [comment]
@jackpot51 

> I think it is a more canonical implementation than plan 9 is, so far

That's not really true, given the sys_brk/sys_alloc/sys_realloc/sys_realloc_inplace/sys_unalloc where a generic `segattach()` would do (or better yet `/proc/*/segment`), or the various URLs where simple file systems would do, or the sys_gettimeofday/sys_time where `/dev/bintime` would do, or the sys_yield where `sleep(0)` would work, or sys_exit where the more generic `exits()` would do, or perhaps most un-9-like, `window://` where Plan 9 simply has `/dev/draw`. I'd recommend studying the design of the [plumber](http://man.cat-v.org/plan_9/4/plumber) for an example of how something more flexible than URLs can be implemented in the filesystem in userspace.
