### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by k0pernicus** [redox-os/redox#255]
Hi!
I wanted to try redox, but I can't currently build the system.

Actually, when I try ```make all```, it returns to me:
```
rust/libcore/ptr.rs:514:19: 514:25 error: expected identifier, found keyword `unsafe`
rust/libcore/ptr.rs:514         pub const unsafe fn new(ptr: *mut T) -> Unique<T> {
                                          ^~~~~~
rust/libcore/ptr.rs:514:26: 514:28 error: expected `:`, found `fn`
rust/libcore/ptr.rs:514         pub const unsafe fn new(ptr: *mut T) -> Unique<T> {
```

It seems like a problem in ```libcore```, and I would like to know which version of Rust to run please?
Currently, my compiler's version is 1.4 (stable).

Thank you!

**Comment by Ticki** [comment]
You need to use the latest nightly.

**Comment by Ticki** [comment]
This can be closed.

**Comment by k0pernicus** [comment]
Ok, thanks.
