### ISSUE TITLE
Migrate web page to GitHub pages

### ISSUE THREAD

**Issue by hauleth** [redox-os/redox#28]
It would be much easier to manage content. I suggest [Hugo](http://gohugo.io) as an engine. If you want me to setup that call me on IRC and I can take care of it.

**Comment by jackpot51** [comment]
I have to get to my day job, I think I would move the blog to redox-os.org/blog, the forum would be at redox-os.org/forum, and I would completely support a site that would go at redox-os.org/ that would have links to those two, and the github (like the Rust website)

I am giving you write access to push gh-pages. I can IRC after work.

Thanks!

**Comment by hauleth** [comment]
I would rather need 2 repos: `redox-os/blog` and `redox-os/redox-os.github.io`. After that there will be need to make some changes in DNS server and it will all work from GH.

PS you cannot run Discourse in subfolder. You will need to create subdomain like https://discourse.redox-os.org (just like Rust site).

**Comment by jackpot51** [comment]
That is good. I would just name it redox-os/website for simplicity, but you can choose any name for now

I can setup the rules in apache so that these redirects happen, thanks.

**Comment by jackpot51** [comment]
Also will do a mail server, I usually use postfix and dovecot but any easier alternatives to postfix for the discourse SMTP are good

**Comment by hauleth** [comment]
It can be named `redox-os/website`.

About domains I think it will be much easier to use http://www.redox-os.org for site and blog, and run Discourse in subdomain. It will remove almost all system management from us. Believe me, it is much easier to achieve than strange mixes with Apache (sic!) or Nginx.
