### ISSUE TITLE
IO Cleanup

### ISSUE THREAD

**Issue by jackpot51** [redox-os/redox#29]
Replace the old C-style I/O with Rust-style I/O

This entails finding and replacing the inX/outX calls with PIOX structs. This will cleanup a large number of bugs in register access in drivers.

**Comment by hauleth** [comment]
Don't you think that async IO is what Redox should provide by default? To be honest this is what should be expected when making OS where everything is URI.

**Comment by jackpot51** [comment]
I tried async I/O a long time ago, and while it is an interesting concept, keeping track of the callbacks and managing object lifetimes was pretty messy and nasty.

I had an async version of each call that schemes could implement, if they wanted too:

open
open_async
read
read_async
write
write_async

**Comment by jackpot51** [comment]
This regex will yield the violations, the two spaces at the beginning are important!:
```
  ((in|out)[bwd]|(read|write|volatile_store|volatile_load))\(
```
