### ISSUE TITLE
Invalid ELF format or freeze after XHCI output

### ISSUE THREAD

**Issue by yohanesu75** [redox-os/redox#291]
Hi
Host is Arch Linux 64bit. I tried both qemu and vbox, 32/64bit build but after XHCI memory mapped output I only get repeated "Invalid ELF format" and "No data" or no output at all, just freeze.

**Comment by robfinner** [comment]
I'm also having invalid ELF format under windows7/virtualbox.

**Comment by Ticki** [comment]
Have you tried the (https://github.com/redox-os/redox#help-redox-wont-compile)[instructions I wrote]?

**Comment by robfinner** [comment]
well I must admit that I've been using the 11/15 master dev branch of rustc 1.6.0.dev. I compiled it probably as 64 bit. Maybe the elf was built as 64 bit and won't load because of that?
Is redox only 32 bit or support on 32bit ELF?

Thanks!

**Comment by jackpot51** [comment]
64 bit doesnt work yet

**Comment by Findeton** [comment]
I'm having this problem on Ubuntu 15.10 64 bits. Redox itself is being cross-compiled to 32bits by the nightly rustc that was installed using Ticki's instructions, but when virtualbox tries to load Redox, it gives the "invalid ELF, no data" error. 

Interestingly enough, I installed Ubuntu 15.10 32 bits on a virtualbox machine and tried compiling and inside that VM it works, I'm able to get to the desktop environment (pressing F2). Although I have to say it's not very usable that way either, I had problems with the mouse, but I don't know if it's a virtualbox issue. Also, I don't like having to do Inception, a VM inside another VM, to get it somehow working.

This is the pastebin with the output from the 64bits Ubuntu 15.10 host machine:
http://pastebin.com/zSBVXvRV

A picture of the Invalid ELF Format error:
http://i.imgur.com/BRWmFXB.png

**Comment by Ticki** [comment]
@Findeton: I wonder, what happens if you run `git clean` and then rebuild.

**Comment by Findeton** [comment]
Hi @Ticki I run git clean -f and make all && make virtualbox and it still gives the same error. Afterwards I also run make clean and rebuilt and the problem is still there. 

Here is the output of the git clean -f / rebuild
http://pastebin.com/D486YGHZ

**Comment by Ticki** [comment]
Interesting. Does the error differ on qemu?

**Comment by Findeton** [comment]
Mmm, I've tried on qemu, and it works! Also I have no issues with the mouse on qemu. Maybe this is a virtualbox related issue? This is the output I get when I run make qemu:

http://pastebin.com/sQCMenaZ

**Comment by polymetric1** [comment]
@Findeton Quick tip: put ` backticks around things like commands e.g. `git clean -X -f -d`, `make virtualbox`, `make qemu`.

**Comment by henrikhodne** [comment]
I am also able to reproduce this. With qemu everything works, and with VirtualBox I get "Invalid ELF Format":

![2015-12-30-02-12-40_1611x1204](https://cloud.githubusercontent.com/assets/24421/12044961/d597c808-ae9a-11e5-9f0f-10d56fe599aa.png)

**Comment by henrikhodne** [comment]
Adding a little more debugging I found that this happens when trying to load /schemes/orbital/main.bin, and the file begins with all zeroes instead of a valid ELF header:

![2015-12-30-02-33-36_1599x1201](https://cloud.githubusercontent.com/assets/24421/12045135/d0e29830-ae9d-11e5-8a27-8874777d91f8.png)

The actual file that is built looks correct, so it looks like something is going wrong in reading it from disk?

```
➜  redox git:(master) ✗ head -c5 filesystem/schemes/orbital/main.bin| xxd -p
7f454c4601
```

I'll continue to dig into this a bit more.

**Comment by jackpot51** [comment]
The IDE driver does not work correctly on Virtualbox in DMA mode. In kernel/schemes/file.rs, PIO (on line 28) can be set to true to alleviate this (at a grave detriment to performance)

**Comment by ambaxter** [comment]
Tried enabling PIO and it booted alright, but I still had mouse problems.

**Comment by ambaxter** [comment]
Works in Qemu. However, when PIO is set to false again, I started having mouse problems with Qemu, too. It might be a problem with no KVM on OS X, however.

**Comment by Ticki** [comment]
I'm not sure why VirtualBox is broken, but Qemu works just fine with upstream/master.

**Comment by jackpot51** [comment]
Fixed after DMA driver rewrite
