### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by timp3289** [redox-os/redox#316]
Hi,
Build is failing for me from the latest source straight from Git.
I have the latest Rust version:
>$rustc -V                                                                                
>rustc 1.6.0-dev (edf2198f5 2015-11-25)

The Git repo is unmodified and up to date

>$git status
>On branch master
>Your branch is up-to-date with 'origin/master'.
>nothing to commit, working directory clean

I ran make clean first
>$make clean                                                                              
>rm -rf build filesystem/*.bin filesystem/*.list filesystem/apps/*/*.bin filesystem/apps/*/*.list filesystem/schemes/*/*.bin filesystem/schemes/*/*.list

Running make virtualbox or make qemu gives the same result
This error is repeated several times:

>rust/librustc_unicode/u_str.rs:132:1: 132:74 error: The attribute `deprecated` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)

Log files from make, along with compiler errors, are attached.
[make_virtualbox_log.txt](https://github.com/redox-os/redox/files/43792/make_virtualbox_log.txt)
[make_qemu_log.txt](https://github.com/redox-os/redox/files/43793/make_qemu_log.txt)

**Comment by Ticki** [comment]
You need rustc nightly.

**Comment by Ticki** [comment]
This can be closed.

**Comment by jackpot51** [comment]
Ticki, this happens with the latest nightly. rustc_unicode needs to be updated

**Comment by haved** [comment]
I'm also having this issue, only I'm on Windows using minGW. Don't know enough about rust to fix it myself, I'm afraid. Please tell me if there is a workaround.

**Comment by timp3289** [comment]
@Ticki I have the latest rust nightly. (read lines 3-5)

**Comment by Ticki** [comment]
Sorry about that. It's also broken to me after updating rust. It seems to be a intrinsic change that makes us unable to use following attributes:

- deprecated
- unstable
- stable
- rustc_deprecated

I believe, currently the only solution is to comment out these.

**Comment by Ticki** [comment]
Libcollections is also broken, and possibly also libcore.

**Comment by Ticki** [comment]
Fixed by #328

**Comment by jackpot51** [comment]
This should be fixed more permanently in master now, rust is a submodule

**Comment by Ticki** [comment]
Cool!
