### ISSUE TITLE
Build status in README.

### ISSUE THREAD

**Issue by skylerberg** [redox-os/redox#324]
If we had a build status in the README then people could spend less time troubleshooting when they first start using redox. I checked it out for the first time today, went to build and got errors. After checking around the issues I see that the build is broken by changes in rust nightly. It would be great to have a badge in the README that indicates the build status so that people joining the project can know that it isn't their system that is the issue if things don't work.

**Comment by Ticki** [comment]
Fixed by #326

**Comment by skylerberg** [comment]
Excellent! Thanks.
