### ISSUE TITLE
Create a command line editor for the shell

### ISSUE THREAD

**Issue by skylerberg** [redox-os/redox#346]
Shells like bash and zsh have line editors that make them far more usable. For example here are some features provided by GNU Readline used in bash:

* Tab completion
* Up arrow for previous command
* Reverse search (ctrl-r)

Readline is kind of the standard for line readers, but it is under a GPL license. It would be nice to have our own line editor written in Rust that can be used by our shell.

**Comment by Ticki** [comment]
I don't think line editor is the correct name for this. Line editor means "line-by-line editor", doing computation on lines as a unit. The right term here is prompt editor. You might want to change the title. :)

**Comment by Ticki** [comment]
But :+1: we definitely need this. I especially like the zsh prompt editor with vi-like bindings (and possiblity for remapping them).

**Comment by skylerberg** [comment]
The name line editor is used to refer to command line editors (e.g., [zsh-line-editor](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html)), however this does collide with the other meaning of line editor (programs like `ed`). Readline and edit line both refer to what they do as "line editing" but do not explicitly call themselves line editors. I changed the title for clarity.

**Comment by Ticki** [comment]
Well, TIL. I'm just used to calling them prompt editor. *shrugs*

**Comment by skylerberg** [comment]
I moved this to the ion repo, so I will close this here.

New issue can be found at: https://github.com/redox-os/ion/issues/3.
