### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#350]
We should consider adding a code of conducts. Examples to consider:

- https://www.rust-lang.org/conduct.html
- http://todogroup.org/opencodeofconduct/ (for criticism of this one see http://dancerscode.com/blog/why-the-open-code-of-conduct-isnt-for-me/)
- https://swift.org/community/#code-of-conduct (mostly pratical stuff)

I believe that some sort of CoC is needed to prevent getting a toxic community.

**Comment by jackpot51** [comment]
No, I don't want one of these

**Comment by jackpot51** [comment]
A code of conduct has nothing, absolutely nothing to do with making quality sotware. I don't want to see this show up again

**Comment by jackpot51** [comment]
In my opinion, a toxic community is one that focuses on how people *feel* as opposed to how the software **works**. The internet is anonymous, my advice is that if you don't want your religion, gender, race, nationality, whatever made fun of, don't tell anyone! BTW I am a white male American atheist anarcho-capitalist who is 23 years old, has red hair, and wears contacts, go ahead and make fun of me, I can take it! **It isn't relevant to developing an operating system anyways!**

The **only** thing that matters in joining an open-source software project is one's ability to write and use the software, and discuss its design. I am completely not in favor of turning this into a padded cell, straight jacket wearing *nursery* for people who are too easy to offend!

**Adding something like a "Code of Conduct" completely violates the principles of software development, that this project is about the source code and what it compiles to! Everything that is not related to the software should be done only when absolutely necessary, and as minimally as possible. See the MIT license for an example.**

https://www.youtube.com/watch?v=JZ017D_JOPY

**Comment by Krak-n** [comment]
@jackpot51 nailed it.

A CoC should not be needed in any project. If a comment / issue / pull request has nothing to do with the project, it doesn't belong in the project. Trolls will be trolls, report them to GitHub / Admins of a mailing list / etc (The people who SHOULD be handling trolls) and move on with your life.

**Comment by Ticki** [comment]
> A code of conduct has nothing, absolutely nothing to do with making quality software.

True, it does not. But it does have something to do with the community. The community is important too.

This altititude makes me sad.

Sure, we shouldn't take OCoC because it's focusing too little on the technical site. But having some kind of CoC, I believe, is something, we should have.

> https://www.youtube.com/watch?v=JZ017D_JOPY

What he says is true, but disrespect should be earned too.

Sure, a CoC **should** focus on the technical aspect, and **should not** take the social situation too far. I don't agree fully with any of the ones I posted here. They were merely for example.

**Comment by Ticki** [comment]
Obviously, I do not want a situation like the "retard" takedown or the Swift slave/master debate. I just want a freindly and helpful community.
