### ISSUE TITLE
Consider using existing package manager

### ISSUE THREAD

**Issue by Havvy** [redox-os/redox#36]
Gonna leave the issue title as general as possible for now.

Writing a package manager means spending less time writing the OS. Other package managers exist out there, some with similar goals to Redox. These package managers should be considered and have good reasons to be not considered before attempting to write your own.

Of the package managers that I know of, Nix (https://nixos.org/) looks to be the one most aligned to your goals.

**Comment by Ticki** [comment]
Package management is important, especially because this isn't a Linux distro, so I think a custom package manager is inevitable.

**Comment by hauleth** [comment]
I am thinking about creating new packaging manager for Redox. I don't came up with name yet, but I want it to be modern system with some new features. Beware of what is going to emerge from that.

For now I want focus on fired - init system for Redox.

**Comment by Ticki** [comment]
Oxide? Also, should it be a binary or compiled package manager?

**Comment by hauleth** [comment]
This is the same name that I came up with. I was thinking about binary package manager with distributed repositories (BitTorrent + HTTP fallback). Probably with some state management. 

--
Łukasz Jan Niemier

Dnia 2 paź 2015 o godz. 10:25 Ticki <notifications@github.com> napisał(a):

**Comment by Ticki** [comment]
Why not compiled? I mean that gives more customizability. Or hybrid, maybe?

**Comment by stratact** [comment]
For me, I'm interested in a primary source-based package management with binary packages as secondary. Since I use Funtoo, I was thinking about porting the emerge tool to Rust just for fun, a while ago, as another project before I discovered Redox. I like the ideas that drobbins had made to make it easier for users to customize their systems without the hassle of knowing to how mess around with build scripts.

**Comment by hauleth** [comment]
Hybrid seems the best option. Purely compiled isn't IMHO good option as then Redox would be like Gentoo - psychofan with enormous free time. I would like it to be binary with option to compile if wanted/needed. 

--
Łukasz Jan Niemier

Dnia 2 paź 2015 o godz. 11:52 Ticki <notifications@github.com> napisał(a):

**Comment by hauleth** [comment]
Second argument for binary based is that it will provide more stability. It is IMHO desired as we should target server cases, not bearded IT maniacs. Otherwise we'll end like Inferno or Haiku.

We should target market where currently CoreOS is. URL based structure fit perfectly that use case. So stabillity should be our primary goal. Just like Rust. 

--
Łukasz Jan Niemier

Dnia 2 paź 2015 o godz. 12:19 stratact <notifications@github.com> napisał(a):

**Comment by mkpankov** [comment]
@hauleth I'd rather not insult Gentoo users like that, if this community is to stay sensible and not degrade to Linux-style passive-aggressive communication.

**Comment by jackpot51** [comment]
I had some thoughts on this here: https://github.com/redox-os/redox/wiki/Package-Management

I am happy to see this discussed, I think both approaches are valid, just as long as the name of the package manager is short!

And why not let users choose to get the source for a version, but have the binary be default? You could also switch to compiling from source as a default if you choose.

PS ox and nix are short :-)

**Comment by Ticki** [comment]
`ox get firefox`

**Comment by jackpot51** [comment]
We need to avoid fragmentation on this issue, so I have created a team for this @redox-os/package-management 

I think we should strongly consider drafting an example package manager in Redox for the following reasons:

- To identify missing Redox functionality necessary for package management
- To identify where packages will be stored (which is going to be an issue with any package manager)
- To have more incentives to create a native build chain

This example package manager, ox is a good name, would enumerate the necessary features to populate the filesystem/apps/ directory and the filesystem/schemes/ directory (which still needs to be discussed)

We should work together on this. If you want nix to be used, then formulate the example to demonstrate how that would work.

**Comment by stryan** [comment]
What about a BSD/Slackware style situation where core and standard distribution packages are binary but then there is also a repository of source packages with compilation scripts? This seems to have worked before and while I like @jackpot51's idea of choosing either source or binary IMHO that might make dependency resolution difficult (e.g foo depends on bar being compiled with option baz, which is how the binaries are but user has bar custom compiled without baz. Does ox assume that all custom compiled packages don't work? etc).

**Comment by Ticki** [comment]
Why not have a source reposotory and compile it making binary available to the user without he or she have to compile it? In this way dependency resolution is the same for source and binary installation.

**Comment by stryan** [comment]
@Ticki 
Like how Guix uses Hydra for CI?

**Comment by jackpot51** [comment]
@Ticki :+1:  :+1:  :+1:  :+1: 

The same code for generating the distribution binaries from source, could be used by the user if they choose to compile from source distribution

**Comment by jackpot51** [comment]
@stryan For custom packages, I would give them a version that marks them as user compiled. The "standard" could always be retrieved, if desired

**Comment by tedsta** [comment]
My project for OS class this semester is actually a package manager. I haven't started yet, but I have some ideas.

- I think we should support both binary and source packages
- I think packages should be versioned, and we should allow setting up multiple package environments so the user could have different versions of the same packages installed simultaneously in different install groups/environments/whatever you want to call it. Like virtualenv, except for all software.

I have another idea that I want to experiment with too. Turning the package manager into a kind of internet infrastructure. Over the years, websites have been becoming more and more app-like. We have things like websockets and webgl now. Websites are the epitome of accessible software. Meanwhile, cross platform development is getting easier and easier. Wouldn't it be nice if you could develop websites/apps without be bound to HTML/CSS/JavaScript? You could even write them as native apps! Imagine how much smoother Google docs would run as a native app.

A simple markdown "website" example package manifest:

    [package]
    name = foobar
    launch = render-md foobar.md
    
    [dependencies]
    render-md = 2.*

And you might host your app like this:

ox host foobar.tgz

If your server's URL was "foobar.com", you would install the app as follows:

ox install foobar.com/foobar

But "websites" wouldn't be installed normally, there would be a package browser to view them in. The browser would organize the user's open tabs just like a web browser does. Browsed packages could be cached for faster access next time or simply deleted to prevent clutter, it'd be up to the user. It kind of doubles as an internet infrastructure and a package manager.

I realize it'd be quite an undertaking to make it secure. It's running arbitrary executables after all. But jackpot51 mentioned sandboxing everything similar to how mobile apps are sandboxed. I picture this being the apps have to ask for permission for anything they use, like sockets or files or a window.

Anyway, the crazy second part would just be a temporary side experiment for me.

**Comment by hauleth** [comment]
I would rather go Arch way where most of packages are compiled and there is community based repository for custom packages with compiled/binary packages. This would allow us to create main stable repo, but also allow to create custom packages in easy and user-friendly way. This is IMHO the best way to achieve stability without sacrificing flexibility.

@Havvy mentioned Nix. It would be great to go that way, but this would require binary only packages. I would rather avoid that.

@mkpankov it wasn't meant as an insult. Gentoo is nice distribution but not for servers or user station. It is for people who want to know their system from the ground. I want Redox to be OS for normal people, not only people with deep knowledge. Gentoo is for small group of people, not for everyone. And especially is not for servers.

@jackpot51 @tedsta I was thinking about BitTorrent/Bitcoin package manager. Each user is also the seeder of package (if possible). It allow to fetch package faster and in more reliable way (main server malfunction would not break whole system).

About using websites as a packages there is one problem - it would need full understanding of application code. Instead we should simplify creating packages using [Electron](https://github.com/atom/electron) or [NW.js](http://nwjs.io/).

**Comment by Havvy** [comment]
NixOS is quasi-source based. Everything is built by source, but the channels can cache those as binary packages. Binary only packages are not required.

**Comment by Ticki** [comment]
@tedsta I agree! Decentralisation of package management would be awesome. On security, people should be able to make "repos" containing hashes of secure packages. Then I can choose to trust a given repo.

On the HTTP proposal, I would rather prefer git. Because git allows the user to install an older version, providing more stability. Git does also allow the user to use a git hosting provider, making hosting easy.

On the security of this approach: `ox` should warn when somebody are installing a package which isn't in the repo (or if the hashsum isn't the same).

**Comment by hauleth** [comment]
@Ticki the issue whit Git is that it is much harder to setup service. IMHO HTTPS is easiest and safest way to create "main" repo. Also it shouldn't warn but should fail to install if package isn't signed with trusted key or hashsum isn't valid. Also we should allow only SHA2 and SHA3 hash functions. No MD* and SHA1. We could think about using Whirpool, BLAKE and/or Tiger but I think that SHA2/3 functions will be enough.

**Comment by hauleth** [comment]
Another reason against Git is there are developers that doesn't use Git. There are other alternatives (Mercurial, Monotone, Darcs, BitKeeper, etc.) and restricting to only one isn't nice in my opinion.

**Comment by Ticki** [comment]
Git is easy to set up. Just set up a SSH with `git shell` (preinstalled with git). I will say that it's just as easy as setting up a HTTP server.

**Comment by Ticki** [comment]
(Also note that git also supports HTTPS)

**Comment by hauleth** [comment]
Yes, but you will need a server with installed Git. It isn't as easy as crate AWS S3 instance, push files, done. It is much more complicated. I still think that raw HTTPS is much easier to serve binaries (also Git is known to have problems with binary data (check Git LFS)). When serving code it doesn't matter as Ox could install required tools as build deps (whether it is Hg or Git).

**Comment by Ticki** [comment]
If we want a hybrid package manager we need a way to store source code too.

**Comment by jackpot51** [comment]
I was going to tarball the source and packages on HTTP to start. This is not the end goal, but I think developing protocol support is a seperate issue.

Why?
- No need to develop or port crypto libs
- No need to handle complicated protocols
- Would allow us to get something that works quickly, which could then be improved upon in the future.
- Ox should just open the package maintainers URL for source, and complain if not supported.

If you want https:// or svn:// or git:// then we need to get to work on the protocol support!

KIS!

**Comment by jackpot51** [comment]
Whatever we do, including Nix, we will need DNS support, write support, and a place to put packages.

**Comment by hauleth** [comment]
I think that source-only packages aren't issue as we can fetch code using existing tools (as I've described above). The binary packages are issue as they are trouble. We cannot have have source-only package manager as compiling GCC or Rust would take forever, and that is thing that would be required by anything. I think that we should made something like Yaourt for Arch.

@jackpot51 if we use HTTP(S) as a base then we can use GitHub, Amazon S3, Dropbox or anything that serve raw files via HTTP(S). This should be the easiest.

**Comment by sackery** [comment]
a core manager for soft compiled by rust based on redox.
and The other use pacman like.

**Comment by hauleth** [comment]
There won't be "soft compiled by rust based on redox". Our main target is to provide full compatibility for libstd and libc in our system, so all software will be "normal Rust" (that mean Ion, Oxide maybe even fired).

**Comment by Ticki** [comment]
The oxide implementation is started, so this can be closed.

**Comment by diogovk** [comment]
@Havvy I still haven't used Nix yet, but from what I read in the manual it looks pretty cool.
Even if redox were not to used it, I think it's a cool place to get ideas from.
