### ISSUE TITLE
On design and organisation

### ISSUE THREAD

**Issue by gpyh** [redox-os/redox#361]
I'm very interested in Redox. I read a lot about language design and OS design, so when I heard of Redox I was all excited.
However, something annoys me: I can't find anything of substance about Redox design, process of thoughts, process of making decisions, areas to contribute etc... Sure, there is updated news on the website, and some sparse info in the Wiki.

But where do you guys discuss your thoughts before implementing them? Who's thinking the big picture and taking time to lay it out on paper for all to see, criticize, and use as a reference when coding? Is there something similar as the RFCs so people can discuss changes and agree on them (or not) before starting working? Do you have any academic literature to back up your design choices?

To illustrate my point: I saw there is a (soon-to-be if I understood right) shell and a package manager, called Ion and Oxide, but very little is written about them. Also, what's your architecture? Is Redox' kernel monolithic or is it a micro-kernel? Such informations should be easily accessible.

Maybe there are, at least in part, answers to my questions and I haven't really searched well enough. I that case I apologize and urge you to point toward them.
Maybe there aren't but the project is too young and too light to require such a heavy organization and serious model of thought. I don't know...

My point is just that it's very hard for me, and I think for anyone, to take an interest on something when I don't actually know how to contribute and what it's all about. Not that I want any part in making decisions ; I just love to learn about cool new shiny stuff and apart from "it's written in Rust and there's URL all over the place", you don't give me much to eat.

Sorry if I sound harsh and negative. I actually think that what your doing is *awesome*. Building an OS is a daunting task and you'll need every help you can get to make it beautiful. It would be easier to get such help if you'd document your design choices and your process in general. Obviously, only someone very involved in the project and possessing the right skills can do such a thing.

If none of this has been thought out, would a platform of discussion on technical matters be of any help?

**Comment by Ticki** [comment]
The technical discussion happens to places:

- Github issues and PRs
- Slack (chat)

I'm sure @jackpot51 will give you a invite to slack, so you can come join the discussion :smiley:

**Comment by polymetric1** [comment]
I'm interested in Oxide and Ion especially, but the slack channels for those have been dead for weeks, even months. I understand the main OS is still in very early development, but it wouldn't be too hard to implement some of the higher level stuff now. anyway, @gpyh I recommend you read [CONTRIBUTING.md](https://github.com/redox-os/redox/blob/master/CONTRIBUTING.md) which will help you with the basics. I'm still working on improving it, to provide a welcoming experience to new contributors, as I've been quite in the dark about this sort of thing in other repositories. Glad you're interested in the project, I hope this helps.

**Comment by Ticki** [comment]
@polymetric1 We could restart the development of Oxide. I've not worked on it for about two weeks. I think we got a pretty good foundation of libraries to be able to go continue Oxide.

**Comment by polymetric1** [comment]
@Ticki alright cool! I think the Oxide client will probably be pretty simple, but I had some ideas. I might write them down in an issue in the Oxide repo.

**Comment by Ticki** [comment]
@polymetric1 Let's chat on slack.

**Comment by gpyh** [comment]
I'm glad for the answers. I'll send a request for the Slack chat immediately.

**Comment by Ericson2314** [comment]
Maybe put more design philosophy / architecture in the manifesto or a companion document?

**Comment by polymetric1** [comment]
I think the wiki should have more content.

**Comment by Ticki** [comment]
Sure. Overall we need more documentation. Maybe better docs in Redocs, the wiki, and a couple of blog posts?

**Comment by polymetric1** [comment]
Hah, redocs. Nice. But yeah, most lf the "documentation" is just restating the function/module/whatever name.

**Comment by Ticki** [comment]
> Hah, redocs. Nice. But yeah, most lf the "documentation" is just restating the function/module/whatever name.

Oh fuck, you found out what my secret is.

**Comment by polymetric1** [comment]
mauhuhahaha i am evil

**Comment by Ticki** [comment]
:smiling_imp:

**Comment by skylerberg** [comment]
I completely agree with @gpyh that it is challenging to figure out much about how redox is designed at this point. It is also hard to tell where most things are going.

First, I do think the manifesto needs a rewrite as it feels a lot like a placeholder at the moment. Right now it just idealizes Linus Torvalds and then has a meaningless riddle for the first half.

Second, I think it would be helpful to have some documentation that explains what the major parts are. For example, just some documentation on what each of the toplevel folders are would be helpful.

 Third, I didn't even realize we had a wik. We should probably put a link in the README so that people know to look there. A link from the redox-os website would be good too.

**Comment by gpyh** [comment]
Figured out http://dictator.redox-os.org/ has also a bit of info.

**Comment by Ticki** [comment]
Yeah, bdfl's blog is quite a good source of information.

**Comment by skylerberg** [comment]
http://dictator.redox-os.org/ is not discoverable enough at the moment. I did not know it existed until right now. It should be linked to on the website, probably in the blogs section. It could also be mentioned in our README.

**Comment by skylerberg** [comment]
@jackpot51 and @Ticki have put a lot of effort into organizing our information. We can close this generic issue. Now, when we have specific things that need to be documented, we should add them as issues in the relevant places (website/book repos).

**Comment by Ticki** [comment]
#525 is an more specific issue. To write down our current resources:

1. [The book](https://redox-os.org/redox/redox) - currently the most detailed source of information.
2. [The kernel docs](https://doc.redox-os.org/doc/kernel/) - the API documentation for the kernel.
3. [The blog](http://www.redox-os.org/news/)
4. [The wiki](https://github.com/redox-os/redox/wiki) - outdated, but still useful.
