### ISSUE TITLE
Did Redox actually boot up on a phone???

### ISSUE THREAD

**Issue by MSF-Jarvis** [redox-os/redox#367]
http://www.redox-os.org/news/this-week-in-redox-6/

A picture here shows Redox OS on a Lumia. Is that real???

**Comment by faddat** [comment]
![image](https://cloud.githubusercontent.com/assets/7142025/11763086/9f79b5f6-a12f-11e5-9626-88eca428a8b4.png)

**Comment by Ticki** [comment]
No it's just a joke. Sorry to disappoint you.

**Comment by Ticki** [comment]
It's a running joke we have in TWiRx.

**Comment by faddat** [comment]
..... and I thought that the ;) was just for cockiness....

@MSF-Jarvis you should have made this into a bet....

**Comment by MSF-Jarvis** [comment]
Ahhh, I wish I had.

**Comment by Ticki** [comment]
> Ahhh, I wish I had.

Me too.

**Comment by Ticki** [comment]
:smile:

**Comment by MSF-Jarvis** [comment]
BTW, me and @thewisenerd actually wanted it to be a joke.

**Comment by thewisenerd** [comment]
can't wait for the day it isn't :wink:

**Comment by Ticki** [comment]
We're invading the world!

**Comment by thewisenerd** [comment]
make sure you do invade our mars too :alien:

**Comment by stratact** [comment]
@Ticki we should change from using that `;)` emoji and make a section for these joke pictures, like with a heading of `Running Gag of the Week` or `Joke of the Week` just for the "lulz" and so that readers do know that's an explicit joke.

**Comment by Ticki** [comment]
Yeah, somebody on reddit too didn't got it.

**Comment by thewisenerd** [comment]
you guys even checked licensing before using the image :+1: 

https://www.pexels.com/photo/person-hands-woman-smartphone-4968/

**Comment by Ticki** [comment]
It's licensed under MIT, I've checked

**Comment by Ticki** [comment]
Those are just trying to sell it even though it's open and freely available.

**Comment by Ticki** [comment]
Oh, they're not trying to sell it, it's CC0.

**Comment by Ticki** [comment]
So no problem.

**Comment by kilidev** [comment]
I haven't even been able to get it to boot fully in virtualbox or qemu. It boots to the login screen but then there is no way to start the gui interface :(

**Comment by Ticki** [comment]
@kilidev Try F2

**Comment by Ticki** [comment]
GUI works fine.

**Comment by kilidev** [comment]
@Ticki Okay so fresh pull everything up to date, virtualbox, on Arch Linux. I pressed F2 and now it is frozen but the screen has not changed. It is frozen at the command line

**Comment by Ticki** [comment]
It compiles? @kilidev

**Comment by kilidev** [comment]
@Ticki Yep compiled just fine!

**Comment by Ticki** [comment]
Also the for loging in just press enter twice (the password is empty by default)

**Comment by kilidev** [comment]
Okay, login is fine i can get to the command line and run 'ls' 'help' 'man' etc. But still no GUI, when it first boots up it says EDID not supported and then something about screen resolution (640x480) Is this okay (y/y) and I just choose y. But still hangs on F2

**Comment by Ticki** [comment]
Interesting. Do the sysconsole show anything?

**Comment by Ticki** [comment]
Also, can you start a new issue?

**Comment by kilidev** [comment]
I can open a new issue, but I am not super familiar with the process :( could you help me? and sysconsole meaning the terminal where I run the 'make virtualbox'?

**Comment by Ticki** [comment]
The sysconsole is in your terminal when running make.

Check this section, https://github.com/redox-os/redox#help-redox-wont-compile, and then open a issue.

**Comment by Ticki** [comment]
Also, checkout this awesome guide: https://github.com/redox-os/redox/blob/master/CONTRIBUTING.md

**Comment by kilidev** [comment]
So I ran the make clean, the git clean, I know the nightly rust build is okay because I ran the binary.sh setup script a couple min ago. 'make all' succeeds, make virtualbox says that 'recipe for target virtualbox failed'  something about cannot remove hadrdrive.vdi but then runs redox with virtalbox anyway, in the same manner that I was describing earlier

**Comment by Ticki** [comment]
Could you open a new issue with a full dump of the output?

**Comment by kilidev** [comment]
@Ticki just did!

**Comment by Ticki** [comment]
Cool, looking at it.
