### ISSUE TITLE
Redox won't boot on VirtualBox

### ISSUE THREAD

**Issue by kilidev** [redox-os/redox#368]
Everything is up to date, followed the guide and then checked everything in the 'Help redox won't compile' section. 'make all' succeeds and below is the output of 'make virtualbox'

[makevirtualbox.txt](https://github.com/redox-os/redox/files/60226/makevirtualbox.txt)

Upon initial boot this is what the virtual machine says, I select y (and have also tried different sizes)

![edid](https://cloud.githubusercontent.com/assets/16260386/11763502/c3420162-a104-11e5-9fc9-cb99695060be.png)

Then I make it to this screen and can run commands etc, but when I press F2 nothing happens and I can no longer type anything it simply looks like the screen below. If I press F1 I can run commands again.
![frozen](https://cloud.githubusercontent.com/assets/16260386/11763505/c8116c32-a104-11e5-973f-0728f227b338.png)

I am not sure if I am doing something very wrong but I cannot seem to get the GUI to show up :(

**Comment by Ticki** [comment]
cc @jackpot51 @stratact

**Comment by Ticki** [comment]
What system is you running on? What's the output of `rustc -V`?

**Comment by kilidev** [comment]
uname -a:
`Linux vimcent 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux`
rustc --version:
`rustc 1.7.0-nightly (81dd3824f 2015-12-11)`

**Comment by Ticki** [comment]
We have the exact same output. Your system is up to date: `pacman -Syu`?

**Comment by kilidev** [comment]
So I just ran:
`sudo pacman -Syyu`
`make clean`
`make all`
`make virtualbox`
Same result.
Also tried it on OSX El Captin
getting a similar result

**Comment by Ticki** [comment]
That's odd. Do it work on Qemu? It boots fine for me on Qemu.

**Comment by Ticki** [comment]
`pacman -S qemu; make qemu`

**Comment by kilidev** [comment]
Works on qemu!

**Comment by Ticki** [comment]
Interesting. Do you mind changeing the title to "Redox won't boot on VirtualBox"

**Comment by kilidev** [comment]
Yep sorry, like i said new to this issue/git stuff

**Comment by Ticki** [comment]
No problem :)

**Comment by kilidev** [comment]
Is the virtualbox working for you?

**Comment by Ticki** [comment]
I've not tried using VB. I've always used Qemu.

**Comment by polymetric1** [comment]
VirtualBox does not work well with Redox currently. Qemu works _better_, but still nowhere near perfect. If you encounter any problems and i mean any, it will not hurt to submit an issue,

**Comment by Ticki** [comment]
@polymetric1 A while back, VB worked better than Qemu with Redox.

**Comment by mhink** [comment]
@polymetric1 @Ticki fwiw, I'm having the same problems with VirtualBox. I dropped some traces in, and the kernel seems to be having trouble reading "file:/schemes/orbital/main.bin"- when reading the file into a Vec<U8>, all that vec seems to contain is zeroes.

**Comment by RustJason** [comment]
Having the same problems too
![image](https://cloud.githubusercontent.com/assets/4018764/11830184/84129dae-a3dd-11e5-822d-a66dfe44b5d4.png)

**Comment by jackpot51** [comment]
This should be temporarily fixed in master, it will boot slower because the disk driver uses PIO instead of DMA
