### ISSUE TITLE
redox won't build with rust nightly

### ISSUE THREAD

**Issue by fischmax** [redox-os/redox#374]
Hi,

after my last pull request got merged (thank you for that \o/), I went on to implement support for the right alt key (altgr), which can already be reviewed at my branch. However, I am currently unable to build redox. With rustc-1.6.0-nightly I got an error about compiler intrinsics in feature flags #[rustc_foo] and with rustc-1.7.0-nightly rust complains about undefined macros:

```
rust/src/libcollections/vec.rs:1353:1: 1353:17 error: macro undefined: '__impl_slice_eq1!'
rust/src/libcollections/vec.rs:1353 __impl_slice_eq1! { Vec<A>, Vec<B> }
```

Unfortunately I am at a complete loss here at what to do. When I find the time I will try it again with rustc-stable, but my hopes on that working aren't very high tbqh )-:

**Comment by Ticki** [comment]
Fixed by https://github.com/redox-os/rust/pull/2

**Comment by jackpot51** [comment]
Ticki, you also have to update the submodule

**Comment by jackpot51** [comment]
This is fixed now
