### ISSUE TITLE
Does redox just use identity paging on x86?

### ISSUE THREAD

**Issue by iankronquist** [redox-os/redox#378]
I was searching through the source and found that redox seems to use an [identity paging scheme](https://github.com/redox-os/redox/blob/f6506dc2766d55aeb550cfdd8bba655c20ed1d57/kernel/common/paging-i386.rs#L27) on x86. Is there interest in building a more robust scheme with a physical memory allocator, or does such a thing already exist and I just can't find it?

**Comment by iankronquist** [comment]
Also, is there a better place to ask this question? Your Mozilla IRC channel is pretty quite.

**Comment by skylerberg** [comment]
I don't have the details on the paging scheme, but the best place to ask something like this is on our slack channel. See our CONTRIBUTING.md file for more details: https://github.com/redox-os/redox/blob/master/CONTRIBUTING.md#slack.

**Comment by jackpot51** [comment]
It identity maps for the kernel, not for userspace. It already has an allocator
