### ISSUE TITLE
Add a requirement about doing git rebase -i before sending a PR

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#387]
For Contributing.md

**Comment by polymetric1** [comment]
Will do. Like, rebase -i out any possible useless merge commits?

**Comment by Ticki** [comment]
And for commits like "sdfgjkgxcvbn" and "fix".

**Comment by Ticki** [comment]
https://xkcd.com/1296/

**Comment by Ticki** [comment]
Fixed by #389
