### ISSUE TITLE
Use less usize in libraries

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#388]
For example: both the position and size of a window is given as isize, usize respectively. These are both given as u32 in X-org and Wayland.

**Comment by hauleth** [comment]
:+1: less platfor dependant types = better.

**Comment by LazyOxen** [comment]
:+1:  This is something I've been wondering about for a while, good to know I'm not the only person to notice it.

**Comment by stratact** [comment]
Hmm, that serves the question. Should both the position and size of the window be set to `u32`? I mean this is about pixel count. Since monitors keep getting larger and larger in resolution size, so how would `u64` sound for both?

**Comment by jackpot51** [comment]
position should be i32, size u32

**Comment by jackpot51** [comment]
position has to be signed because windows can be dragged left of the screen

**Comment by stratact** [comment]
@jackpot51 but maybe the way X11 or Wayland does it, is that the origin (0, 0) is at the top-left corner while a matter of +x moves further right and +y moves further down from that point?

**Comment by polymetric1** [comment]
@stratact I think he means this can happen:
![wrwr](https://cloud.githubusercontent.com/assets/13613437/11909918/71680218-a5bb-11e5-9ca1-826d2024bda1.png)

**Comment by jackpot51** [comment]
x11 and wayland both used signed positions, to support the case @polymetric1 shows

**Comment by jackpot51** [comment]
They also use signed sizes http://tronche.com/gui/x/xlib/window-information/XGetWindowAttributes.html

**Comment by stratact** [comment]
I'm not sure if my patch completely closes this issue, since the issue is about looking at all of our crate/libraries? @Ticki just used liborbtk as an example.

**Comment by Ticki** [comment]
@stratact Yeah, they were just examples. Pointer sized integers are completely overused in the kernel, for example.

**Comment by Ticki** [comment]
For the reference: #389 makes liborbital use less sizes.
