### ISSUE TITLE
Linux emulation

### ISSUE THREAD

**Issue by suhr** [redox-os/redox#394]
Provide a program emulating linux environment.
For example, Plan 9 have linuxemu: http://plan9.bell-labs.com/wiki/plan9/Linux_emulation/index.html

**Comment by Ticki** [comment]
I don't think emulation is necessary. Linux and Redox is already quite similar in the syscalls and architecture. Maybe a API translation layer would be better?

**Comment by jackpot51** [comment]
This is probably not going to happen. Lots of software can be ported over without changes, I do not see a major benefit to running Linux binaries on Redox
