### ISSUE TITLE
Add tests to _everything_

### ISSUE THREAD

**Issue by ticki** [redox-os/redox#396]
They catch a suprisingly amount of bugs.

**Comment by polymetric1** [comment]
Unit should be a higher priority. Currently the "test" scripts `failure` and `success` just return `1` and `0` respectively.

**Comment by lygstate** [comment]
Sorry for the disturb. QEMU is to heavy to do a test. Is that possible to partially testing things? I means , some code can be running indpendetly

**Comment by polymetric1** [comment]
From what I understand, you mean adding tests to things that are testable, like libraries? (Orbital, orbtk, etc.)?

**Comment by Ticki** [comment]
Testing is hard, not because we run inside a VM, but because Redox is not a library, thus we cannot just automatically test all things.

**Comment by Ticki** [comment]
Orbital, orbtk, libredox, drivers, memory manager, and so on.

**Comment by Mouvedia** [comment]
You should probably add a script with a shortcut on the desktop with a minimal interface that could maybe output an error log if something goes wrong.

Testers won't be able to test everything thoroughly; you need to help them help you.

**Comment by jackpot51** [comment]
This is just common sense, I closed because I would rather see things like "add tests to the tcp scheme" rather than "test everything"
