### ISSUE TITLE
Generic block layer

### ISSUE THREAD

**Issue by imp** [redox-os/redox#399]
It is my understanding that at the moment redox lacks generic block layer. The only block device is IDE disk driver. If one would like to add another block device driver for, say SATA, SCSI, or NVMe device the whole new URL would be needed. And it will end up duplicating at least some code. And the upper layers would have to learn about each and every implementation. Having generic block layer with well defined traits will let us have simpler hardware specific drivers.

In case I am completely off with this assessment feel free to close this issue

**Comment by jackpot51** [comment]
This is somewhat done. AHCI and IDE can be used interchangeably, they both implement a Disk trait. Support for USB disks is coming soon as well
