### ISSUE TITLE
Make a "book" like IntermezzOS

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#403]
IntermezzOS got a pretty good MDbook: http://intermezzos.github.io/book/preface.html

**Comment by k0pernicus** [comment]
That's a good idea - can we create a repository in ```Redox``` which contains all sources?

**Comment by Ticki** [comment]
Looks like @Roxxik is working on this.

**Comment by Ticki** [comment]
https://github.com/Roxxik/redox-doc

**Comment by Ticki** [comment]
https://github.com/redox-os/redox/issues/525

**Comment by Ticki** [comment]
https://github.com/redox-os/book

**Comment by skylerberg** [comment]
We can close this too.
