### ISSUE TITLE
Joining Teams, Comment Here!

### ISSUE THREAD

**Issue by jackpot51** [redox-os/redox#41]
I have created teams for various projects, like @redox-os/package-management @redox-os/shell @redox-os/zfs  @redox-os/window-management 

If you want to join a team, or create a team, please comment here!

**Comment by hauleth** [comment]
I want to be part of @redox-os/package-management, @redox-os/zfs and @redox-os/shell. If it would be possible also to create @redox-os/init.

**Comment by hauleth** [comment]
Oh and @redox-os/docs. Also there will be need for some extra repos:

- `fired` - init system
- `webpage` and `redox-os.github.io` - webpage

**Comment by jackpot51** [comment]
I'm slightly in favor of doing the init system inside of the redox repo, I want to KIS for users who want to build Redox. If you object, let me know what you think

**Comment by stratact** [comment]
There are plently of light init systems to look at for designing Redox's init system, such as, [finit](http://troglobit.github.io/finit.html) or [s6](http://skarnet.org/software/s6/)

**Comment by esell** [comment]
I have zero rust experience but have ok knowledge with regards to java and go so I'd be open to helping out with any n00b tasks that come up. I realize at this stage those are probably few and far between though :)

**Comment by hauleth** [comment]
Personally I think that we should check if it is possible to use Cargo to build while system and split it into separate directories/crates. Each module should be independent repo that will be built via main OS repo.

@stratact of course we can use existing init systems, but:

- all of them are made for Linux which has different design
- we should establish consistent configuration format inside OS and I think that TOML is good enough
- we should use fact that "everything is URL" (systemd done right)

**Comment by TheNeikos** [comment]
As someone new to System Programming, but not to programming itself, is there anything I can do to help?

**Comment by mgattozzi** [comment]
I think we'll need some very good documentation done. A well written wiki etc. It's the thankless kinds of jobs that are always needed with projects. Tests as well. Lots of unit and integration tests. That way we can utilize things like Coveralls, but also the coding isn't done till the tests run.

I too agree with @hauleth about splitting some things up a bit more. Modularizing the code base can allow for more maintainable code and will achieve the goal of moving applications and things out of the kernel code itself.

**Comment by Zypeh** [comment]
I wish to join redox project, especially in @redox-os/package-management and @redox-os/shell. Just want to learn Rust through practical in use.

**Comment by ambaxter** [comment]
I'm interested in joining the project. I'd like to help with @redox-os/shell and @redox-os/init.

**Comment by tedsta** [comment]
Hey @Zypeh and @ambaxter 

For package management: https://github.com/redox-os/oxide
For shell: https://github.com/redox-os/ion
for init: https://github.com/redox-os/fired

Hop on irc.mozilla.org#redox to chat about stuff

**Comment by jackpot51** [comment]
You guys need to send an email to me jackpot51@gmail.com to get on slack, it is where most discussions take place

**Comment by tennix** [comment]
Hi, I'm very interested in this project. I'd like to help with redox-os/shell and redox-os/oxide

**Comment by LazyOxen** [comment]
Hey hey, I'm new to rust, and still have a bunch to learn about programming, but I'd like to help with @redox/shell

**Comment by TheNeikos** [comment]
After thinking about it I would to join @redox-os/init

**Comment by stratact** [comment]
Guys, just send an email to @jackpot51 and ask for invite into Slack. You don't need to say anything. Just hop on.

**Comment by hayathms** [comment]
I want to be part of @redox-os/package-management, @redox-os/zfs and @redox-os/shell. If it would be possible also to create @redox-os/init.

**Comment by hayathms** [comment]
@redox-os/window-management looks exciting too.

**Comment by stratact** [comment]
@jackpot51 are we still doing this team stuff? Basically it's just people joining on Slack and hanging out in their favorite channels to learn and contribute?

**Comment by jackpot51** [comment]
@stratact No, the github teams are not relevant. I have removed them. Please send me an email to join slack

**Comment by skylerberg** [comment]
Looks like this isn't used any more and has been replaced with slack channels. Perhaps we should close this thread and update the readme to tell interested people to email you to get added to slack.

**Comment by polymetric1** [comment]
Is help still needed with some of the higher-level stuff? I really like this project and I'd like to help, I'm just kinda new to low-level OS stuff, but I could probably help implement shell apps and stuff. Also, yeah I think there should be an in-depth CONTRIBUTING.md file or something for people that are interested in helping.

**Comment by stratact** [comment]
Everyone, please join the Slack chat. Anyone is welcomed. You can be part of any category of development that you want. Email @jackpot51 for an invitation.

@jackpot51 can we just close this and add to the readme on how to join?

**Comment by stratact** [comment]
@polymetric1 documentation improvements is always needed as an example of higher-level tasks to do. You can also do code cleanups as well. There is plenty you can do, but you got to get involved first, as why I do stress the need about joining Slack first.

**Comment by skylerberg** [comment]
@polymetric1 I like the idea of having a CONTRIBUTING.md so I opened an issue for it (#336). Also, it looks like there is a lot of work to be done on things like the shell. That is one project I am particularly interested in and it looks like there is a lot to do.

**Comment by skylerberg** [comment]
Let's close this. GitHub issues are not the right place for this any more.
