### ISSUE TITLE
Make Redox compile in debug mode

### ISSUE THREAD

**Issue by ticki** [redox-os/redox#436]

**Comment by genodeftest** [comment]
If this is done it would be interesting to have some make target for debugging redox using gdb or valgrind.

**Comment by Ticki** [comment]
Another interesting thing is debug assertion to strengthen security.

**Comment by jackpot51** [comment]
Redox can be compiled in either debug or release mode by modifying the Makefile - release mode is preferred (with live assert when absolutely necessary) for performance
