### ISSUE TITLE
add servo support in redox

### ISSUE THREAD

**Issue by lygstate** [redox-os/redox#448]

**Comment by Ticki** [comment]
That's not a small task. We don't even have libc or libstd yet. That should be higher priority.

**Comment by lygstate** [comment]
just for tracking， I am curious how hard it would be

**Comment by polymetric1** [comment]
For clarification what do you mean by "servo support"?

**Comment by Ticki** [comment]
Probably, something like porting the Servo to Redox, using their toy browser?

**Comment by polymetric1** [comment]
Okay, it's a browser engine.

**Comment by Ticki** [comment]
It _the_ browser engine.

**Comment by lygstate** [comment]
Is that a wayland support would be enough for servo engine running?

**Comment by Ticki** [comment]
No, it's not. It would require a lot of things: libc, mesa, wayland, libstd, cairo, and so on.

**Comment by lygstate** [comment]
That's really a lot of things.

**Comment by lygstate** [comment]
If redox could be able to running servo, then it's close to a usable os.

**Comment by polymetric1** [comment]
It looks like servo relies on alot of C based stuff. We don't have libc properly ported yet, so that's far off. We're working on the basic stuff first. We'll get to that eventually, but probably not anytime soon.

**Comment by polymetric1** [comment]
Unless we're going to leave this issue open forever until it's actually implemented, i believe this can be closed.

**Comment by Ticki** [comment]
> If redox could be able to running servo, then it's close to a usable os.

No, it is not. We need lots of things, not just Servo. The Redox kernel itself isn't even complete.

**Comment by jackpot51** [comment]
Servo is unlikely to be usable on Redox for a very long time. It is more likely that a much smaller browser engine, like NetSurf, will be ported first.

I also don't see it as a Redox issue to support Servo, rather a Servo issue to support Redox as a platform.
