### ISSUE TITLE
page fault when closing terminal window

### ISSUE THREAD

**Issue by dufresnep** [redox-os/redox#450]
got a page fault while playing around:

paul@arcturus:~/redox/redox$ make qemu kvm=no
find filesystem -not -path '*/\.*' -type f -o -type l | cut -d '/' -f2- | sort | awk '{printf("file %d,\"%s\"\n", NR, $0)}' > build/i386/filesystem.gen
nasm -f bin -o build/i386/harddrive.bin -D ARCH_i386 -ibuild/i386/ -ikernel/ -ifilesystem/ kernel/harddrive.asm
qemu-system-i386 -serial mon:stdio -m 1024 -d guest_errors -vga std -usb -device usb-tablet -drive file=build/i386/harddrive.bin,format=raw,index=0,media=disk -net nic,model=rtl8139 -net user -net dump,file=build/i386/network.pcap
Redox 32 bits
ACPI Table: FACP
ACPI Table: SSDT
ACPI Table: APIC
MADT: Unknown entry type: 4, length 6
ACPI Table: HPET
    Unknown Table
 * PCI 0, 0, 0: ID 12378086 CL 6000002
 * PCI 0, 1, 0: ID 70008086 CL 6010000
 * PCI 0, 1, 1: ID 70108086 CL 1018000 BAR4: C121 16
IDE on C120
Primary Master: Status: 58 Serial: QM00001 Firmware: 2.5+ Model: QEMUHARDDISK Size: 39 MB
Primary Slave: Status: 0
Secondary Master: Status: 41 Error: 2
Secondary Slave: Status: 0
 Redox Filesystem
 * PCI 0, 1, 2: ID 70208086 CL C030001 BAR4: C101 32
UHCI on: C100, IRQ: B
 CMD 00 to 00 to 00 STS 20 INTR 00 FRNUM 68 to 00 FLBASEADD 00 to B45000 CMD 00 to 01
 PORTSC1 83 to 0283 to 83
 Device Found 83 to 87
DeviceDescriptor {
    length: 18,
    descriptor_type: 1,
    usb_version: 512,
    class: 0,
    sub_class: 0,
    protocol: 0,
    max_packet_size: 8,
    vendor: 1575,
    product: 1,
    release: 0,
    manufacturer_string: 1,
    product_string: 3,
    serial_string: 5,
    configurations: 1
}
Manufacturer: QEMU
Product: QEMU USB Tablet
Serial: 42
ConfigDescriptor {
    length: 9,
    descriptor_type: 2,
    total_length: 34,
    interfaces: 1,
    number: 1,
    string: 7,
    attributes: 160,
    max_power: 50
}
Configuration: HID Tablet
InterfaceDescriptor {
    length: 9,
    descriptor_type: 4,
    number: 0,
    alternate: 0,
    endpoints: 1,
    class: 3,
    sub_class: 0,
    protocol: 2,
    string: 0
}
HIDDescriptor {
    length: 9,
    descriptor_type: 33,
    hid_version: 1,
    country_code: 0,
    descriptors: 1,
    sub_descriptor_type: 34,
    sub_descriptor_length: 74
}
EndpointDescriptor {
    length: 7,
    descriptor_type: 5,
    address: 129,
    attributes: 3,
    max_packet_size: 8,
    interval: 10
}
 PORTSC2 80 to 0280 to 80
 * PCI 0, 1, 3: ID 71138086 CL 6800003
 * PCI 0, 2, 0: ID 11111234 CL 3000002 BAR0: FD000008 16777216 BAR2: FEBD0000 4096
 * PCI 0, 3, 0: ID 813910EC CL 2000020 BAR0: C001 256 BAR1: FEBD1000 256
RTL8139 on: C000 port mapped IRQ: 0B MAC: 52.54.0.12.34.56 IMR: 05 CMD: 0D RCR: 9E TCR: 77800000
Starting HID driver
- Starting Orbital
    Console: Press F1
    Desktop: Press F2
redox login: PID 20: file:/apps/terminal/main.bin
  INT E: Page fault
    CS:  0000001B    IP:  0804A8C6    FLG: 00000216
    SS:  00000000    SP:  700FEDF0    BP:  700FFF20
    AX:  FFFFFFFF    BX:  080576A8    CX:  00000000    DX:  00000000
    DI:  083EA000    SI:  083EA000
    CR0: 80000013    CR2: 083EB004    CR3: 00200000    CR4: 00000600
    -480: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    -448: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    -416: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    -384: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    -352: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    -320: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    -288: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    -256: 00000000 0804B260 700FEEB0 00000000 00000000 00000000 00000000 00000000
    -224: 00000000 00000000 00000003 FFFFFFFF FFFFFFFF 00000240 00000190 00000008
    -192: 700FEE70 00000000 1DFFFFFF FA000002 3B000000 1D1D1D1D 1D1D1D1D 1D1D1D1D
    -160: 1D1D1D1D 1D1D1D1D 1D1D1D1D 1D1D1D1D 1D1D1D1D 1D1D1D1D 1D1D1D1D 00000020
    -128: 00000000 0804B080 700FFF08 00000004 00000003 00000006 00000005 00000000
    -96: 083EB000 083EB000 00000004 083EA000 1D1D1DD4 00000000 00000000 00000000
    -64: 00000000 00000000 0804E5D8 00000001 00000000 00000000 00000000 00000000
    -32: 0000000C 00000000 00000000 08049DD0 080576A8 00000000 00000000 00000000
      0: 00000000 0804A8C1 080576A8 083EA000 083EB000 00000000 08049FCE 700FFF20
     32: 080576A8 083EA010 00000000 083E9018 083E9018 00000000 00000000 0804A18E
     64: 080576A8 083EA000 083EA010 00000000 00000000 08063000 08063000 00000001
     96: 083EA000 00000048 00000190 00000000 00000019 00000190 FFFFFFFF 00000000
    128: 00000000 0804A849 080576A8 083EA000 08063000 08065000 0804B9AC 080576A8
    160: 083EA000 700FEDA8 00000010 FFFFFFFF 0000001E 0804B23A 080576A8 0000001E
    192: FFFFFFFF 0804B12A 0804FF0F 700FEDA8 00000000 700FED48 700FEDC8 0804DB92
    224: 080576A8 00000000 0804A3C3 700FEDA0 080576A8 0804FF0F 700FEDB0 0804A247
    256: 00000008 0804B4C5 080576A8 00000000 0804E5D8 00000000 00000000 700FED3C
    288: 080576A8 00000001 700FED48 00000000 00000000 0804A2E0 00000000 0804E5D8
    320: 700FEDE8 0804D36D 080576A8 00000000 0804AAB4 700FED04 080576A8 0804FF0F
    352: 00000000 00000000 00000000 00000011 0804E5A0 00000008 00000000 00000000
    384: 00000000 00000011 0804E5A0 00000011 0804FD90 0804E371 080576A8 00000011
    416: 0804E940 700FECA0 080576A8 0804E5D8 080576A8 00000001 700FED61 00000000
    448: 00000000 0804A247 080576A8 700FEDB8 00000000 00000000 00000000 0804C1C0
    480: 080576A8 700FEDB8 00000000 00000000 00000000 00000000 00000000 700FFEF0
    ERR: 00000007

**Comment by dufresnep** [comment]
It seems to do that every time I close Terminal (Desktop).

**Comment by Ticki** [comment]
Note: Orbital is being refactored/rewritten in the `orbital` branch, and this change will probably fix this bug.
