### ISSUE TITLE
Improve scheduling algorithm

### ISSUE THREAD

**Issue by jackpot51** [redox-os/redox#487]
Right now, the scheduling is round-robin, with no conception of blocked processes. Processes that are blocked should be skipped until the block is released

**Comment by Ticki** [comment]
Priority should also be taken into account.

**Comment by Ticki** [comment]
Can you assign me?

**Comment by jackpot51** [comment]
I can only assign myself

**Comment by jackpot51** [comment]
I have to add a user as a colaborator with read access to assign, very clunky and unnecessary

**Comment by jackpot51** [comment]
This issue has been fixed, now the major issue is ineffecient paging
