### ISSUE TITLE
Compiling libcore

### ISSUE THREAD

**Issue by Roxxik** [redox-os/redox#489]
I'm just looked into redox and wanted to get started by first getting it to run somehow and had a problem compiling redox. I followed the instructions in the readme and rustc threw an error.

    rust/src/libcore/intrinsics.rs:557:5: 557:58 error: intrinsic has wrong type: expected `unsafe extern "rust-intrinsic" fn(fn(*mut u8), *mut u8, *mut u8) -> i32`: incorrect number of function parameters [E0211]
    rust/src/libcore/intrinsics.rs:557     pub fn try(f: fn(*mut u8), data: *mut u8) -> *mut u8;

I suspect, this is because of a problem with the rustc version I'm using and because intrinsics aren't stable

    rustc 1.8.0-nightly (9a07087bc 2016-01-30)

the branches tell me you forked the current version some 3 months ago. 
And my question now is:

Is there an error in this version of libcore?

or

should i get an older nightly rust compiler and if so, which one?

for b) the documentation in the readme should get updated to contain another multirust override command

    multirust override nightly-2015-11-01

or some other compatible version

**Comment by Ticki** [comment]
You have to 1) Update to the **latest nightly**. 2) Pull the rust submodule. And it will work.

**Comment by Roxxik** [comment]
You're right, updating the rust repository fixed it. But I had to clone redox again without --recursive. Using recursive, all submodules were plain folders, without any git metadata. Therefor  I couldn't update them.

Without --recursive, right after checkign out, I just ran git submodule update --init and now i have a working copy of redox (in qemu :P )

**Comment by Roxxik** [comment]
just removing the --recursive fixes this. but in the current state the guide in the readme does not work, because the submodules are not properly initialized.

**Comment by Ticki** [comment]
This can be closed.

**Comment by Roxxik** [comment]
yup, someone just needs to change the readme

**Comment by Ticki** [comment]
I'm pretty sure it is already there.

**Comment by Ticki** [comment]
Oh, it seems that your issue was that we were using an outdated version of the Rust modules. That is fixed. See redox-os/rust.

**Comment by Roxxik** [comment]
i just retry the guide from the readme and report after cloning redox (takes ages)

**Comment by Ticki** [comment]
Sure thing!

**Comment by Roxxik** [comment]
uh now it works, last time i had some weird error message, telling me coreutils is not a git repository, when doing `submodule update` , now it works
