### ISSUE TITLE
Create redox-os/areweosyet for general information about OS development in rust.

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#49]
Like Are we ide yet? and Are we web yet?.

Can contain:

- Rust boot
- Redox
   - Screenshots
- Rustnomicon
- etc.

**Comment by hauleth** [comment]
I will add that to the webpage. I'm just started working on it.

**Comment by hauleth** [comment]
New webpage is still WIP but it looks like this:

https://redox-os.github.io

I will add info about usefulness of OS later.

**Comment by Ticki** [comment]
It's already done in flosse/rust-os-comparison, so I'll close this for now.
