### ISSUE TITLE
Start a `Gitter` chatroom.

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#50]

**Comment by hauleth** [comment]
I think that IRC channel is enough. To much fragmentation can kill us.

**Comment by esell** [comment]
or use slack with an irc gateway so users can connect either way. we use slack at my day job and really like it.

**Comment by jackpot51** [comment]
I'd like history so slack would be a good option. Just woke up, going to start commenting.

**Comment by tedsta** [comment]
+1 for slack. We also use it at work.

**Comment by stratact** [comment]
Whichever suits you guys. I would like to be able to communicate in real-time.

**Comment by cruelbob** [comment]
gitter + slack is good option

**Comment by jackpot51** [comment]
I decided to do gitter because I was curious. I also set up redox-os.slack.com

Let's just say that I haven't made up my mind yet. Gitter did make the invitations easy, though

**Comment by jackpot51** [comment]
@hauleth  is there a way to save IRC chat messages?

**Comment by tedsta** [comment]
@jackpot51 not sure how to set this up, but #rust-gamedev has this https://botbot.me/mozilla/rust-gamedev/

**Comment by jackpot51** [comment]
@redox-os/contributors I need emails to do slack, it has more features than gitter and IRC so I would like to use it by default.

You can email me at jackpot51@gmail.com or comment here, whichwver you prefer for security reasons

**Comment by Ticki** [comment]
Can't you just use our git emails?

**Comment by Ticki** [comment]
I'll PM mine over reddit.

**Comment by jackpot51** [comment]
I could, but I don't know an easy way and not everyone has committed
something to redox

**Comment by Ticki** [comment]
You are /u/jackpot51, right?

**Comment by jackpot51** [comment]
Yep

**Comment by jackpot51** [comment]
@hauleth The only reason I set up multiple chat systems is because I was not sure yet which one to standardize to. IRC is a bit barren, in my opinion, and gitter is not fully developed, so I think slack will be the best. I hope I can get all our 8 contributers on there, and if there are no objections, I will stop using the other services provided

**Comment by Ticki** [comment]
I don't seem to get an invitation over mail...

**Comment by hauleth** [comment]
Maybe Slack with IRC gateway like @esell said?

**Comment by jackpot51** [comment]
Yep, can do that

**Comment by Ticki** [comment]
I get the error:

> Apologies, we're having some trouble with your web socket connection.

Does this happens for anybody else?

**Comment by esell** [comment]
If you really want to see git commits and what not you can also integrate slack with github using the built-in integrations. There is also hubot for slack...

**Comment by jackpot51** [comment]
Yep, did that @esell. Did you send your email yet?

@Ticki what browser are you in?

**Comment by Ticki** [comment]
Firefox.

**Comment by jackpot51** [comment]
Which distro?

**Comment by Ticki** [comment]
Arch.

**Comment by Ticki** [comment]
Seems there are some errors in the console.

**Comment by jackpot51** [comment]
Interesting, what are they?

**Comment by Ticki** [comment]
Firefox can't establish a connection to the server at [server here].

I think I'll do a `pacman -Syu` and reboot. I'll be back in a minute.

**Comment by Ticki** [comment]
We have slack now. Closing.
