### ISSUE TITLE
Make redox select interpretter for executable scripts by checking shebang

### ISSUE THREAD

**Issue by skylerberg** [redox-os/redox#501]
IIRC, the way unix operating systems know how to run an executable file is that they look at the first 16 bits. If those bits are the characters `#!` (shebang) then the OS reads the rest of the line and figures out which interpreter to use to run the file.

**Comment by polymetric1** [comment]
Good idea. I'll write the scripts. I might try to implement it into `cargo test`, but I'm not experienced with Rust tests or really Rust in general.

**Comment by jackpot51** [comment]
This feature has been added

**Comment by skylerberg** [comment]
Very cool!
