### ISSUE TITLE
Add std::env::home_dir to libredox

### ISSUE THREAD

**Issue by skylerberg** [redox-os/redox#502]
I would like to use `std::env::home_dir` in ion for when the user executes a bare `cd`. Adding this will break compatibility with redox unless we have `home_dir` in libredox.

**Comment by k0pernicus** [comment]
I've create a single function to find the home_dir (which is the basic ```/home/``` directory).
Stay tuned about new version of redox... ;-)

**Comment by jackpot51** [comment]
That's good, we have a ways to get to multi-user :P

**Comment by skylerberg** [comment]
Thanks! Next time I have some time to write some Ion code I will be taking advantage of this change to merge the bare `cd` patch!
