### ISSUE TITLE
How does Redox deal with distributed memory and distributed computing?

### ISSUE THREAD

**Issue by jli05** [redox-os/redox#507]
(From a newbie:) Just wondering what kind of programming model Redox proposes in terms of distributed computing. Thanks,

**Comment by polymetric1** [comment]
I don't think questions should be asked in issues. If you don't want to go through the trouble of joining Mattermost, ask on the #redox channel on the Mozilla IR.

**Comment by Ticki** [comment]
IRC is by far the easiest way for one or just a few questions.

**Comment by Ticki** [comment]
So come visit us at #redox on irc.mozilla.org!
