### ISSUE TITLE
Use cargo

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#51]
We should use cargo especially because of `cargo doc`, which gives a neat overview of the whole codebase. Is something preventing us from this?

**Comment by jackpot51** [comment]
No reason. What would have to be done to get a working Cargo.toml?

**Comment by Ticki** [comment]
I'm working on it. Starting with `libredox`

**Comment by jackpot51** [comment]
Thanks man! Could also add a lib.rs to src for the kernel

**Comment by Ticki** [comment]
It almost compiles: https://github.com/Ticki/redox.

**Comment by Ticki** [comment]
(Compiling via cargo requires src to be cargo based) It still compiles via `make` though. Will send a PR.

**Comment by Ticki** [comment]
PR sent.

**Comment by stratact** [comment]
If were using cargo now, could we pull in some crates from crates.io, like toml-rs, since another goal of this OS is to consistently use TOML configuration?

**Comment by hauleth** [comment]
Not will be possible to use as some of them depends on `std` which Redox doesn't have at low level. But still I think that using Cargo would simplify a lot (like tooling or building whole suite).

**Comment by Ticki** [comment]
On the progress of this:

I've made `common` use cargo, however it's won't compile using cargo (as it depends on non-cargo crates). So yeah... everything is messed up. Checkout https://github.com/Ticki/redox/tree/cargo for WIP.

**Comment by boghison** [comment]
Guys, I'm a bit confused about libstd, AFAIU, there's no libstd here, right? (So then there's no packages). I have 2 questions: what is the reason that libstd hasn't been ported yet? What can I do to help with it?

**Comment by Ticki** [comment]
Right now the `common` module and `libredox` crate contains some of the functionality provided by libstd. However, long-term we want to port libstd.

You can help by adding new stuff to `common` or `libredox`

**Comment by boghison** [comment]
@Ticki Yeah, I got that, but why isn't libstd support a priority (what issues need to be solved etc)

**Comment by Ticki** [comment]
Libstd **is** a high priority! libredox is just a temporary replacement for it.

**Comment by hauleth** [comment]
We should implement some kind of issue marking with priority and area. Just like Rust does. 

--
Łukasz Jan Niemier

Dnia 8 paź 2015 o godz. 14:55 Ticki <notifications@github.com> napisał(a):

**Comment by Ticki** [comment]
I'll close this.
