### ISSUE TITLE
Redox nightly ISO

### ISSUE THREAD

**Issue by bubnenkoff** [redox-os/redox#523]
It would be nice to have auto-generation daily bootable ISO with Redox.

**Comment by Ticki** [comment]
Yeah, that's right. Multiple people have expressed their desire for this.

**Comment by petevine** [comment]
Are there any older images to try out in qemu?

Also, on ARM, is Redox going to suffer from this Linux clock [issue?](https://bugs.launchpad.net/qemu-linaro/+bug/893208) which would make it impossible to boot?

**Comment by Ticki** [comment]
This can be closed. See https://www.redox-os.org
