### ISSUE TITLE
Redox compilation error on a very recent nightly

### ISSUE THREAD

**Issue by pmarcelll** [redox-os/redox#527]
Redox seems to be affected by rust-lang/rust#31362, and since warning are turned into hard errors (if I understand it correctly), compiling Redox fails when the compilation of the kernel starts: ```extern crate `io` is private``` is triggered by ```use drivers::io::Io;```.

**Comment by jackpot51** [comment]
Will fix shortly, thanks

**Comment by jackpot51** [comment]
It is fixed now
