### ISSUE TITLE
Support 64 bit

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#53]
The main change required is rewriting lots of `asm!` macros. (Correct me if im wrong)

**Comment by jackpot51** [comment]
That is part of it. Rewriting all parts that assume 32-bit. I use usize for most pointer operations, and u32 where required to specify size.

The layout of the page tables, GDT, and IDT change as well.

**Comment by hauleth** [comment]
To be honest I think that we should drop 32bit support ASAP and focus on 64bit only.

**Comment by boghison** [comment]
I agree with ^^

**Comment by mgattozzi** [comment]
I agree as well considering all hardware nowadays runs 64bit, unless you were planning to do an embedded os on say like a raspi.

**Comment by hauleth** [comment]
@mgattozzi currently we should target clouds and home PCs. After we establish some base (`fired`, Oxide, etc.) then we should port Redox to ARM also, as RΠ is big market to win.

**Comment by 007lva** [comment]
What do you think about putting the focus on ARM? Because, except for servers, I think x64 and, specially x86,  not have much future compared to ARM.

**Comment by 007lva** [comment]
+1 for RPI

**Comment by hauleth** [comment]
I haven't said anything about focusing on ARM. I told that we should firstly establish x64 codebase and then think about adding support for ARM.
