### ISSUE TITLE
Multirust has new installation script

### ISSUE THREAD

**Issue by jonathanmcelroy** [redox-os/redox#530]
In the README, there is a line to install multirust:

    curl -sf https://raw.githubusercontent.com/brson/multirust/master/blastoff.sh | sh

The blastoff file has been renamed to quick-install in multirust, so the line should show:

    curl -sf https://raw.githubusercontent.com/brson/multirust/master/quick-install.sh | sh

**Comment by jackpot51** [comment]
Would you like to submit a PR?
