### ISSUE TITLE
Multi-seat

### ISSUE THREAD

**Issue by Sherif89** [redox-os/redox#532]
Hi, does Redox support multi-seat? It's a useful feature.

**Comment by Sherif89** [comment]
You'll make Redox a micro-kernel, right? So, will it be the task of something like the display server?

**Comment by stratact** [comment]
The Orbital display server is in user space now. I'm sure it can be implemented to run multiple instances of it like with X11 to support multi-seat configurations.

**Comment by jackpot51** [comment]
Multi-display support is very, very far away. It is highly unlikely that this will be seen for years, so I am closing.
