### ISSUE TITLE
A proposal for Ox

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#54]
Proposal for the `ox` package manager (Redox)
========

This is a proposal for the ox package manager for redox.

## Principles

Ox shall be modular, simple and decentralised. Ox shall both be
capable of compiling from source and installing binaries directly.
Futhermore, Ox shall be secure.

## How Ox works

Ox works over HTTP(S) protocole. Ox is consisting of two types of
data sources:
- Repositories
- Package hosts

### Repositories

In this context, a repository (or repo for short) is a place
storing various information about packages. These includes:
- Where the package can be downloaded (package host)
- What the hashes of the binaries and the source are.
- The hash of the package's public key (which is owned by the
  package developer). This ensures that the user will be able
  to securely get the latest version without worrying about
  the security of the connection/provider.

There is not one central repository. The user adds repositories,
he or she trusts. The repository *X* (name) from *Y* (host) can
be found in http(s)://ox.[*Y*]/*X*.oxr.

This is recommended to be over a HTTPS connection, however this
is not required (although a warning is given if not).

This file is of the format:
```
[name of the package]:[version]:[description of the package]:[hash of the binary]:[hash of the source code]:[hash of the developers public key]
[name of the package]:[version]:[description of the package]:[hash of the binary]:[hash of the source code]:[hash of the developers public key]
[name of the package]:[version]:[description of the package]:[hash of the binary]:[hash of the source code]:[hash of the developers public key]
...
```

### Package hosts

The package *X* of version *V* from *Y* can be found in
`http(s)://ox.[*Y*]/[*V*]-[*X*].oxp`. This is a file of the format

```
name=[name]
author=[author]
description=[description]
version=[version]
bin=[path to binary]
source=[path to source]
compile=[path to compile script]
publickey=[public key of the developer]
signature=[digital signature of the files]
files=[files provided in the package]
dependencies=[list of packages this package depends on (includes versions)]
```

The hash of the binary/source is checked, of course (using the
hash from the repositories). So is the signature.

If the version is set to `_` the latest version of the package
is returned. To make sure that this package is safe, the signature
is checked (using the signature in the repository). If no developer
signature is found in the repository a warning is returned.

## Installation

Installation is done via downloading the binary and running it while
tracking the files it creates. These are stored together with the
`files` parameter given by the package host. These are used if the
user wants to uninstall the package.

### `ox get [package]`

Installs `[package]` using the binary. If multiple packages named
[package] are found in the repositories, the user is asked to
choose the package.

### `ox get -c [package]`

Installs [package] from the source.

### `ox remove [package]`

Remove [package] including files that it has created.

### `ox add [repository name and host]`

Add a new repository.

### `ox clean`

Cleans up all orphaned packages.

### `ox update`

Updates the repositories.

### `ox upgrade`

Install all new upgraded packages.

## Unresolved questions, TODOs etc.

Lots of things. For example:

- How will `ox` manage multiple versions of the same package?
- In what language will compile scripts be written?

**Comment by stratact** [comment]
If we were to use the HTTPS protocol, does that mean we should also implement our own SSL/TLS implementation? For the sake of the security aspect of this project I would prefer to avoid using OpenSSL. Unless we have to use it, use LibreSSL instead since it's (mostly) API compatible and the OpenBSD folks include their own libtls implementation with it as well.

**Comment by hauleth** [comment]
I'm author of [Octavo](https://github.com/libOctavo/octavo). It is still WIP, but it should be usable in month or so.

**Comment by stratact** [comment]
@hauleth awesome :+1:

**Comment by hauleth** [comment]
About design. It seems OK for me.

What I would change:

- no need for signature and checksum - signature contains checksum, so it would duplicate data
- I would use TOML as package description
- I would rethink URL naming (I don't say no, but I need to look into it)
- I would think about using DHT for fetching data about packages

**Comment by jackpot51** [comment]
I really like this, and I think some work should be done to filesystem/apps/ox to flush it out. At the very least convert input commands into what URL they would get data from. Some assumptions could be made:

http://redox-os.org/packages/package_name/version.tar
http://redox-os.org/packages/package_name/version.source.tar

**Comment by tedsta** [comment]
I also like this. Do you think we could squeeze virtualenv-like environments in there too? Sometimes I want different sets of packages installed simultaneously, but I only want to use one set or a few sets at a time. For instance, maybe I have a bunch of stuff installed in a python2 development environment, and a bunch of different stuff installed in a python3 development environment.

This would also solve the unresolved question of how to handle multiple versions of the same package, I think.

**Comment by jackpot51** [comment]
I don't see why not. With the sandboxing I envision, you could have several sandboxed /app directories, each with its own userspace. Each user could have their own userspace, as well

**Comment by Ticki** [comment]
> no need for signature and checksum - signature contains checksum, so it would duplicate data

The reason for this is that the paranoid user could be sure that the package is trusted by the repo.

**Comment by hauleth** [comment]
If he doesn't trust the developer then how the heck he should trust software? Additionally packages should be signed by repo owner. So all packages in official repo should be signed by Us.

Also all packages should be compressed. I think that we should select one compression format as it would simplify whole process. I suggest [LZ4](https://github.com/Cyan4973/lz4) as it provide very fast decompression algorithm with with good compression ratio.

**Comment by Ticki** [comment]
If one trusts v1 does not imply that he or she trusts v2 (for example if the owner sold the package).

**Comment by hauleth** [comment]
But package will be signed by package creator not by author of code. Package author will be the owner of the repository. IMHO it is how it should work. So either you trust package or not. You cannot trust package created by malicious 3rd party even if you trust repository. This could work otherwise, you can trust signed package (if you trust signer) even if you do not trust repository. So package creator signature is enough to be sure about package safety, even if you do not trust repository (repo owner cannot change package without changing signature).

**Comment by Ticki** [comment]
I have a second suggestion which I think is better than the original one:

The user keeps track of two sources of data:

- Indexes: who keeps information about were the package of a given name can be found.
- Trusted keys: Public keys the user trusts.

A package contains the signature of the package developer, which is signed by a number of key providers. Furthermore is the package (of a given version) signed by different key providers.

The user checks if this package is signed by a trusted key. If not, the package isn't trusted.

The indexes does not have to be trusted.

This solution have t

**Comment by hauleth** [comment]
I do not understand what you mean by:

> which is signed by a number of key providers

I was thinking about something like that:

- package is signed by provider
- user keeps trusted GPG signatures on their system
- after fetch he/she check against signature, if it is valid, then it is safe

It is similar way to one that APT is using and I think that this is simplest and safest one. At the same time it provide a lot of flexibility.

**Comment by Ticki** [comment]
@hauleth Im afraid that solution has the problem that one does not necessarily trust a developer, but instead a package.

Suppose I was malicious. I could do the following attack:

1. Program some software which would be well recieved.
2. Get signed and trusted.
3. Publish a new version which is malicious.
4. This is also trusted because my public key is signed.

**Comment by Ticki** [comment]
@hauleth What I mean is that the developers public key (if trusted) is signed by some key providers. This makes the user able to see if the developer is trusted.

**Comment by hauleth** [comment]
@Ticki the same get with the developer or anyone in the chain. If you get binary package then no matter what you have to trust package manager as developer cannot sign all possible binaries. About source packages they should be fetch&build scripts only. You do not provide source but rather you get it from official source (developer one). You do not provide source yourself. Check how AUR packages works. It should work similar way.

PS about language to write build scripts I think we should use LuaJIT as it is fast and easy to write, and can be easily embedded into Ox.

**Comment by Ticki** [comment]
Since I'm already working on an implementation, I'll close this.
