### ISSUE TITLE
System will hang when spawning more software threads than hardware threads available.

### ISSUE THREAD

**Issue by ticki** [redox-os/redox#542]
This a bug in the scheduler introduced after the merge of the `blocking` branch. To reproduce, open Rusthello.

Rusthello spawns 4-10 threads, which results the system to hang, and it will stay unresponsive.

**Comment by NilSet** [comment]
I am not sure it is the number of threads. I changed rusthello to use join instead of channels and it runs to completion with two AI players.

**Comment by EGhiorzi** [comment]
@NilSet that's awesome, please feel free to PR the fix!

**Comment by NilSet** [comment]
So as far as I can tell, preemption is somehow getting turned off (aka hardware interrupts from the PIT are being ignored). When I add a `thread::yield_now()` to the mspc busy wait, it runs fine.

**Comment by ticki** [comment]
Yeah, for some reason PIT interrupts doesn't call. Related to https://github.com/redox-os/redox/issues/575.
