### ISSUE TITLE
Move the file server to userspace

### ISSUE THREAD

**Issue by ticki** [redox-os/redox#544]

**Comment by jackpot51** [comment]
Anyone who wants to help on this can contribute to the redoxfs repository

**Comment by stratact** [comment]
Probably should migrate this issue over there.

**Comment by genodeftest** [comment]
Is redoxfs meant to be a filesystem implementation (like NTFS, ext2/3/4, btrfs, ZFS, …) or a filesystem protocol implementation (more like a namespace)?

**Comment by Ticki** [comment]
@genodeftest It is a simple FS.

**Comment by jackpot51** [comment]
done
