### ISSUE TITLE
Custom lint against slicing and indexing in the kernel

### ISSUE THREAD

**Issue by aochagavia** [redox-os/redox#551]
Hello there! I was wondering if it would make sense to have custom lints in order to enforce [best practices](https://github.com/redox-os/redox/blob/master/CONTRIBUTING.md#best-practices) in the kernel. The main use case I have in mind is preventing slicing and indexing, since they can panic and we don't want that to happen in the kernel.

Is this already implemented? Would you like it to be?

**Comment by aochagavia** [comment]
See https://github.com/Manishearth/rust-clippy/issues/755

**Comment by Ticki** [comment]
That's right, it would certainly make sense to have a no_panic lint. IIRC, Manish is working on it for Clippy.

**Comment by aochagavia** [comment]
Then I think this could be closed in favor of https://github.com/redox-os/redox/issues/351. Thanks for your feedback!
