### ISSUE TITLE
Website renders weird: Chrome on Antergos... Same thing happens to rust-lang website too.

### ISSUE THREAD

**Issue by anicake** [redox-os/redox#557]
![screenshot from 2016-03-17 11-27-47](https://cloud.githubusercontent.com/assets/922486/13837692/d3a6e2dc-ec33-11e5-9dcf-10222f8efb68.png)

**Comment by Ticki** [comment]
Are you sure this is not a bug in the browser? Because, this seems very strange. It seems that it cannot load the font.

**Comment by anicake** [comment]
This only happens on the rust-lang website and the redox-os website. All other websites load normally. I checked the network tab in the dev tools. All seems fine. If it were a browser bug, can you tell me how I would go about debugging it? Also, rest assured I will more than happy to carry out any procedure you might want me to and reply with results.

**Comment by bungcip** [comment]
see this issue for details: https://github.com/rust-lang/rust/issues/24614

**Comment by genodeftest** [comment]
@anicake: It looks like you are using a dark theme for chrome or your desktop environment (Gnome Shell). Can you try again with a light theme?

all: I guess this is happening since non CSS is resetting the font color which defaults to white (or light gray) in some cases when the user has a dark theme with light fonts installed.

**Comment by anicake** [comment]
@genodeftest I tried using the tweak tool that I normally use to toggle all combinations on the desktop theme. It had no effect. Changed Chrome theme to default classic and back, and that also had no effect. On the other rust-lang issue thread a person mentioned replacing google-font-family with the fira sans family... But I'm sure there is something tricky going on here.

**Comment by genodeftest** [comment]
@anicake you need to at least restart chrome after changing the Gnome theme.
Can you use the browser inspector to confirm or disprove that the fonts are rendered in light grey or white?

**Comment by anicake** [comment]
Yes I had read that writing in small... and had duly restarted Chrome after the change. I know that the content is part of the DOM on the website because when I drag across the screen to select text with the mouse, I don't particularly see any highlight, but when I then `Ctrl-C` and `Ctrl-P` somewhere else I find that the text in fact did come onto the clipboard. I'm guessing its rendered in white, but doesn't show any highlights. Note: The screenshot also has the CSS for that selected DOM element open.

![screenshot from 2016-03-22 16-48-17](https://cloud.githubusercontent.com/assets/922486/13949929/f6bc34b6-f04d-11e5-9e70-4d5375a1ece9.png)

**Comment by anicake** [comment]
Also curious to know why only fira fonts work :-)

[https://www.reddit.com/r/archlinux/comments/2gix0k/rust_website_now_with_invisible_fonts/](url)

**Comment by genodeftest** [comment]
So disabling fira fonts makes the site work for you again?

**Comment by jackpot51** [comment]
This seems like an issue in your browser, chrome on elementary OS, ubuntu, mac os x, windows all work fine for me
