### ISSUE TITLE
Termion colors not rendering

### ISSUE THREAD

**Issue by jhod0** [redox-os/redox#561]
Colors do not show properly - see screenshot.

Same with either the minesweeper game or the rusthello example.

![rusthello_redox](https://cloud.githubusercontent.com/assets/8944001/13901920/e167b21e-ee01-11e5-8177-8b4a0d0a4040.png)

Colors, however, do work with the colors.lua script:

![lua_colors](https://cloud.githubusercontent.com/assets/8944001/13901930/42bef612-ee02-11e5-9282-ad8319c4d7d7.png)

My details:

Using Qemu i386 version 2.0.0 from the Ubuntu package manager. 

Running under Linux Mint, on an i5. 
It's an Asus Ultrabook something.

**Comment by jackpot51** [comment]
UTF8 support is missing from the terminal

**Comment by IVaN4B** [comment]
![2016-03-21-182603_1024x768_scrot](https://cloud.githubusercontent.com/assets/1508308/13923756/f2bb048e-ef92-11e5-937c-f8a0f2fbf820.png)
![2016-03-20-182937_1024x768_scrot](https://cloud.githubusercontent.com/assets/1508308/13923757/f2bf7280-ef92-11e5-9d1f-3e0cd167ec42.png)
Similar issue, there should've been minesweeper :)

**Comment by Ticki** [comment]
If you use the systerminal, you get different results, @IVaN4B.

**Comment by Ticki** [comment]
Also, that is not an ANSI problem, but an Unicode problem.

**Comment by IVaN4B** [comment]
Yeah, I've got it, when I saw ansi-test and colors.lua working, that why I posted it here.

**Comment by jackpot51** [comment]
Are things working correctly now?
