### ISSUE TITLE
Example project does not work

### ISSUE THREAD

**Issue by jhod0** [redox-os/redox#562]
In ion, running:

```
# example
```

Results in:

```
called `Result::unwrap()` on an `Err` value: Error { repr: Os(17) } in rust/src/libcore/result.rs:746
```

It looks like `File::create(":example").unwrap()` on line 201 in crates/example/main.rs is what is failing.

Some info:

Running under Qemu on Linux mint 17
```
$ rustc --version
rustc 1.9.0-nightly (b12b4e4e3 2016-03-17)
```

**Comment by jackpot51** [comment]
Example is a scheme, and is started by default (try cat example:)

It can only be run once

**Comment by jhod0** [comment]
Ahh - thanks for the clarification
