### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Stormys** [redox-os/redox#563]
I seem to be having cargo errors but I am unsure how to fix it.

julian@julian-ubuntu:/mnt/TB/Documents/Programming Projects/redox$ make all
#TODO: filesystem/bin/env filesystem/bin/test
#TODO: filesystem/bin/mtxt
CARGO_TARGET_DIR=build RUSTC="./rustc-i386.sh" cargo rustc --manifest-path crates/ion/Cargo.toml --bin ion-shell --verbose --target=i386-unknown-redox.json -- 
   Compiling glob v0.2.11
     Running `./rustc-i386.sh /home/julian/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/glob-0.2.11/src/lib.rs --crate-name glob --crate-type lib -g -C metadata=0ffe4874535835d5 -C extra-filename=-0ffe4874535835d5 --out-dir /mnt/TB/Documents/Programming\ Projects/redox/build/i386-unknown-redox/debug/deps --emit=dep-info,link --target i386-unknown-redox.json -L dependency=/mnt/TB/Documents/Programming\ Projects/redox/build/i386-unknown-redox/debug/deps -L dependency=/mnt/TB/Documents/Programming\ Projects/redox/build/i386-unknown-redox/debug/deps --cap-lints allow`
   Compiling peg v0.3.9 (https://github.com/crazymykl/rust-peg.git?branch=libsyntax-changes-again#1efaca63)
     Running `./rustc-i386.sh /home/julian/.multirust/toolchains/nightly/cargo/git/checkouts/rust-peg-bb4e2b887d852aec/libsyntax-changes-again/src/peg_syntax_ext.rs --crate-name peg_syntax_ext --crate-type dylib -C prefer-dynamic -g -C metadata=f8d111835d3afa96 -C extra-filename=-f8d111835d3afa96 --out-dir /mnt/TB/Documents/Programming\ Projects/redox/build/debug/deps --emit=dep-info,link -L dependency=/mnt/TB/Documents/Programming\ Projects/redox/build/debug/deps -L dependency=/mnt/TB/Documents/Programming\ Projects/redox/build/debug/deps --cap-lints allow`
error: multiple input filenames provided
error: multiple input filenames provided
Build failed, waiting for other jobs to finish...
error: Could not compile `glob`.

Caused by:
  Process didn't exit successfully: `./rustc-i386.sh /home/julian/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/glob-0.2.11/src/lib.rs --crate-name glob --crate-type lib -g -C metadata=0ffe4874535835d5 -C extra-filename=-0ffe4874535835d5 --out-dir /mnt/TB/Documents/Programming Projects/redox/build/i386-unknown-redox/debug/deps --emit=dep-info,link --target i386-unknown-redox.json -L dependency=/mnt/TB/Documents/Programming Projects/redox/build/i386-unknown-redox/debug/deps -L dependency=/mnt/TB/Documents/Programming Projects/redox/build/i386-unknown-redox/debug/deps --cap-lints allow` (exit code: 101)
make: *** [build/i386-unknown-redox/debug/ion-shell.bin] Error 101

**Comment by ca1ek** [comment]
If you ended up fixing it, don't just close the issue but write how you managed to get it to work for other people that hit similar issue.

**Comment by Stormys** [comment]
Sorry about that. My issue was that the folder containing the redox code had a space in its name. The command was failing because of that space.
