### ISSUE TITLE
README: Add information which username to enter

### ISSUE THREAD

**Issue by ERnsTL** [redox-os/redox#581]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]

1. Install dependencies, clone redox repo as per instructions.
2. Start Redox using ```make qemu```.
3. When asked for ```redox login:``` I am not sure what to enter. Which users exist? Is user management even implemented right now? come up in my head.

**Expected behavior**: [describe the behavior you would expect the repro to yield.]

Documentation should contain information what to enter for now. I entered ```root``` and this seems to have worked, but I was not sure what to enter (uncertainty).

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]

```git rev-parse HEAD``` returns d5dbf65cf63ca788f5ab4e27e738ca5d1f77dd6b = revision as of today, 2016-03-23.

**Comment by DomThePorcupine** [comment]
You don't have to enter any name! Just press enter!

**Comment by Ticki** [comment]
Enter enter enter :notes:

**Comment by ERnsTL** [comment]
Ah, thanks for the quick responses :-) Sorry for the dumb question..

For you it seems obvious what that login prompt wants, but maybe others feel uncertain too, so I thought I'd post this here.

**Comment by Ticki** [comment]
> For you it seems obvious what that login prompt wants, but maybe others feel uncertain too, so I thought I'd post this here.

Sure, it can be confusing. It might make sense to add it to the build instructions.

**Comment by jackpot51** [comment]
This has been added to the init
