### ISSUE TITLE
make failing on 4.2.0-27-generic #32-Ubuntu with make qemu kvm=no

### ISSUE THREAD

**Issue by perlhakr** [redox-os/redox#587]
I Pulled latest REDOX from git using:

 git clone https://github.com/redox-os/redox.git && cd redox && git submodule update --init

make qemu kvm=no fails on ubuntu as follows.

Linux pyromodo-VM40B 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
pyromodo@pyromodo-VM40B:~/code/redox$ ^C
pyromodo@pyromodo-VM40B:~/code/redox$ make qemu kvm=no
mkdir -p build/i386-unknown-redox/debug
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead_code -o build/i386-unknown-redox/debug/libcore.rlib rust/src/libcore/lib.rs
rust/src/libcore/num/dec2flt/mod.rs:217:56: 217:57 error: expected one of `,`, `.`, `}`, or an operator, found `?`
rust/src/libcore/num/dec2flt/mod.rs:217         ParseResult::Valid(decimal) => convert(decimal)?,
                                                                                               ^
error: aborting due to previous error
Makefile:404: recipe for target 'build/i386-unknown-redox/debug/libcore.rlib' failed
make: *** [build/i386-unknown-redox/debug/libcore.rlib] Error 101
pyromodo@pyromodo-VM40B:~/code/redox$

**Comment by DomThePorcupine** [comment]
rustc version?

**Comment by perlhakr** [comment]
rustc 1.7.0 (a5d1e7a59 2016-02-29)

**Comment by DomThePorcupine** [comment]
I think your rust version is too old. Can you install the latest nightly and try again?

**Comment by Ticki** [comment]
It is outdated, update it to the latest nightly.

**Comment by Ticki** [comment]
It works with `rustc 1.9.0-nightly (98f0a9128 2016-03-23)`.

**Comment by perlhakr** [comment]
Worked. Thanks.

**Comment by DomThePorcupine** [comment]
@perlhakr Good :) close the issue?
