### ISSUE TITLE
System hangs when attempting to open .bmp and .wav files sometimes

### ISSUE THREAD

**Issue by skylerberg** [redox-os/redox#590]
**Reproduction**:

* Start orbital
* Open the file explorer
* Double click a .bmp file or a .wav file

**Expected behavior**: The viewer or audio player open the file.

**Actual behavior**:

The behavior varies, here are the variations I have observed:

1) The mouse stops moving, nothing appears to happen and nothing works. This is the most common.
2) A window opens for the application that should be launched for the file. However it is all black. Then everything from (1) happens.
3) Same as (2), but I notice that I can move my mouse for about half a second before it hangs.
4) When opening the wav file, two windows open up to play it and everything runs slowly for a little bit. It does not hang.
5) Sometimes (rarely) the file opens as expected.

Note, in no case have a heard any audio, but that could easily be a KVM setting issue.

**Build information**:

Running with qemu. Latest rust nightly. Up-to-date submodules.

**Comment by skylerberg** [comment]
There is not output in the console during this.

**Comment by jackpot51** [comment]
this is a result of https://github.com/redox-os/redox/issues/536
