### ISSUE TITLE
Keyboard and mouse interactions that should not happen.

### ISSUE THREAD

**Issue by skylerberg** [redox-os/redox#593]
**Reproduction**:

Here are two examples that should be easy to repro:
1) Keyboard messing with the mouse
  * Start moving the mouse smoothly from one side of the screen to the other
  * As you move it, spam `asdf` over and over again.
2) Mouse messing with the keyboard
  * Open somewhere you can type characters, e.g., the basic text editor
  * Start spamming `asdf` over and over again.
  * Move the mouse in circles while typing

**Expected behavior**: The keyboard and mouse should not effect each other.

**Actual behavior**:

1) The mouse moves sluggishly and starts jumping backwards to previous positions.
2) Many characters that were not typed start appearing in the text editor.

**Comment by jackpot51** [comment]
I belive that this has been fixed
