### ISSUE TITLE
Shutdown doesn't work

### ISSUE THREAD

**Issue by pmarcelll** [redox-os/redox#600]
**Reproduction**:
Clicking the icon in the bottom right corner or running ```shutdown``` in the shell

**Expected behavior**:
Redox shuts down

**Actual behavior**:
Clicking the icon has no visual effect, the output of ```shutdown``` is:

```
Good bye!
ion:file:/home/# error: No such file or directory
```

**Build information**:
Build: b76ecf3, using VirtualBox

**Comment by pmarcelll** [comment]
Interesting, I just tried Qemu with ```make qemu```, and it works.

**Comment by jackpot51** [comment]
VirtualBox has different ACPI settings for shutdown, it will only work in qemu as it is
