### ISSUE TITLE
Orbital freeze

### ISSUE THREAD

**Issue by DerpyCrabs** [redox-os/redox#603]
**Reproduction**
1. Compile it
2. Run with virtualbox or qemu
3. Run orbital
**Expected behavior**
No freezes.
**Actual behavior**
GUI freezes. Screen updates every 5-10 seconds.
**Build information**
rustc -V: rustc 1.9.0-nightly (5ab11d72c 2016-04-02)
uname -a:
Linux lunarhost 4.4.6-1-MANJARO #1 SMP PREEMPT Sat Mar 19 06:00:37 CET 2016 x86_64 GNU/Linux
qemu-i386 -version: 2.5.0, Copyright (c) 2003-2008 Fabrice Bellard
git rev-parse HEAD: 71915396a2ee99a5aa9f6ddb67fbb1a54e0f1fbb
Virtualbox version: 5.0.16 r105871
DE: xfce4
PC config: pentium e5300, 4gb ddr3-1333 ram, nvidia gts450 (proprietary drivers).

**Comment by nounoursheureux** [comment]
@DerpyCrabs is the issue solved for you ? I have this problem too but I think it is because my computer is not powerful enough
