### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by abbert** [redox-os/redox#604]
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead_code -C ar=i386-elf-ar -C linker=i386-elf-gcc -o build/i386-unknown-redox/debug/libsystem.rlib crates/system/lib.rs
crates/system/externs.rs:2:1: 2:35 error: definition of an unknown language item: `stack_exhausted`. [E0522]
crates/system/externs.rs:2 extern "C" fn stack_exhausted() {}
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
crates/system/externs.rs:2:1: 2:35 help: run `rustc --explain E0522` to see a detailed explanation
error: aborting due to previous error
make: *** [build/i386-unknown-redox/debug/libsystem.rlib] Error 101

**Comment by abbert** [comment]
OSX, rustc 1.9.0 nightly

**Comment by nounoursheureux** [comment]
Your git repo is outdated, this issue was fixed with d8f0d5d145485b3fb2b1ae9d42a9375997431882 :)

**Comment by jackpot51** [comment]
Please update your compiler and the repo, then try again
