### ISSUE TITLE
Follow rust naming convention

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#61]
BMP should be Bmp
WAV shoud be Wav

and so on.

**Comment by hauleth** [comment]
I think that `BMP` and `WAV` are good enough. I think that types should be named `CamelCase` with acronyms in uppercase. So there is `ThatParser` but `HTMLParser`.

**Comment by Ticki** [comment]
Unfortunately, that's not the convention. See https://github.com/rust-lang/rust/blob/master/src/doc/style/style/naming/README.md

> In CamelCase, acronyms count as one word: use Uuid rather than UUID. In snake_case, acronyms are lower-cased: is_xid_start.

**Comment by zonyitoo** [comment]
I agree with @Ticki .

**Comment by zonyitoo** [comment]
@jackpot51 How is this issue going? I think now is a good time to do this thing. When the code base is going larger, it would be much much harder then now.

**Comment by jackpot51** [comment]
We should follor rust convention
