### ISSUE TITLE
Unable to checkout crates/malloc

### ISSUE THREAD

**Issue by Csega** [redox-os/redox#617]
Hi All!

**Reproduction**: Run bootstrap.sh from elementaryOS.

**Expected behavior**: install all the necessary packages.

**Actual behavior**: after a while, it prints the following error message and stops:
"Submodule path 'rust/src/rust-installer/test/rust-installer-v2/test/rust-installer-v1': checked out 'aed73472416064642911af790b25d57c9390b6c7'
Unable to checkout '400cbca439ffd0c2aaa82b159213c607aa261853' in submodule path 'crates/malloc'"

**Build information**: rustc 1.9.0-nightly (2b6020723 2016-04-13), git HEAD: 4102604bc59c625b5a739a1c2bf38296fac6169f,  uname -a: Linux eOS 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

------

So far the bootstrap.sh worked for me just fine. Before every run, I delete the redox directory it creates, so I guess this counts as a "clean" installation. However, it does not work now...

What could be the problem?
Thanks for your help!
Csega

**Comment by pmarcelll** [comment]
Have you tried ```git submodule update --init```?

**Comment by DomThePorcupine** [comment]
`remote: Counting objects: 9, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 9 (delta 6), reused 9 (delta 6), pack-reused 0
Unpacking objects: 100% (9/9), done.
From https://github.com/redox-os/libmalloc
   a17c934..c4f7593  master     -> origin/master
fatal: reference is not a tree: 400cbca439ffd0c2aaa82b159213c607aa261853
Unable to checkout '400cbca439ffd0c2aaa82b159213c607aa261853' in submodule path 'crates/malloc'`

This is what i get after running `git submodule update --init`

**Comment by jackpot51** [comment]
malloc was replaced with ralloc recently

**Comment by Csega** [comment]
Thanks, it seems to work now! :)
