### ISSUE TITLE
Make all command exits (fuse 0.2.7 does not compile)

### ISSUE THREAD

**Issue by Csega** [redox-os/redox#619]
**Reproduction**: run make all command in the redox directory after downloading everything with bootstrap.sh

**Expected behavior**: the compilation finishes without errors.

**Actual behavior**: the following error is printed on the screen:
error: failed to run custom build command for `fuse v0.2.7`
Process didn't exit successfully: `/home/.../redox/crates/redoxfs/target/debug/build/fuse-903ac6b64e7fdf04/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\"` did not exit successfully: exit code: 1\n--- stdout\nPackage fuse was not found in the pkg-config search path.\nPerhaps you should add the directory containing `fuse.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'fuse\' found\n"', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.

make: *** [build/i386-unknown-redox/debug/filesystem.bin] Error 101

**Build information**: rustc 1.10.0-nightly (c2aaad4e2 2016-04-19), git rev-parse: 4848216c9ab5e58019a16af84368f5a489f51faa, Linux eOS 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Please help me guys, I don't know, what could be the problem. Is it the fuse crate itself, or something else? At the fuse repo, the automatic build system said it is building...

**Comment by DomThePorcupine** [comment]
The reason is this project now depends on libfuse. On ubuntu it is libfuse-dev. Right now there is a PR open with an updated bootstrap waiting on confirmation that it works on all systems. Sorry for the inconvenience, try installing that package and recompile

**Comment by Csega** [comment]
Thanks, it works now. However, it only works correctly, if I run make all with sudo. Otherwise it gives the following error:

redoxfs: opened filesystem build/i386-unknown-redox/debug/filesystem.bin
fusermount: failed to open /etc/fuse.conf: Permission denied
cp -rL filesystem/* build/i386-unknown-redox/debug/filesystem/
sync
fusermount -u build/i386-unknown-redox/debug/filesystem/
rm -rf build/i386-unknown-redox/debug/filesystem/
nasm -f bin -o build/i386-unknown-redox/debug/harddrive.bin -l build/i386-unknown-redox/debug/harddrive.list -D ARCH_i386 -D TIME="`date "+%F %T"`" -ibuild/i386-unknown-redox/debug/ -ikernel/ -ifilesystem/ kernel/harddrive.asm

**Comment by jackpot51** [comment]
That is fine, the failure to open /etc/fuse.conf is not important and can be ignored

**Comment by Qartar** [comment]
I'm still seeing this issue with latest on OSX (10.11.4):

> error: failed to run custom build command for `fuse v0.2.7`
> Process didn't exit successfully: `/Users/.../redox/crates/redoxfs/target/debug/build/fuse-903ac6b64e7fdf04/build-script-build` (exit code: 101)
> --- stderr
> thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"osxfuse\"`: No such file or directory (os error 2)"', ../src/libcore/result.rs:785
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by jackpot51** [comment]
You need to install osxfuse with macports or homebrew

**Comment by Qartar** [comment]
I get this error message when trying to install osxfuse with homebrew:

> $ brew install osxfuse
> osxfuse: osxfuse is already installed from the binary distribution and
> conflicts with this formula.
> osxfuse: Building this formula from source isn't possible due to OS X
> Yosemite and above's strict unsigned kext ban.
> 
> You can install with Homebrew Cask:
>   brew install Caskroom/cask/osxfuse
> 
> You can download from:
>   https://sourceforge.net/projects/osxfuse/files/
> Error: Unsatisfied requirements failed this build.

 Installing with Homebrew Cask does not resolve the build failure. I'm not sure how to proceed.

**Comment by jackpot51** [comment]
Do you have pkg-config installed?

**Comment by Qartar** [comment]
I did not, looks like the install has fixed it. Should pkg-config be added to the list of package dependencies? Thanks.

**Comment by jackpot51** [comment]
Yes, it should be. Glad you can compile now

**Comment by DomThePorcupine** [comment]
@jackpot51 should pkg-config be put in bootstrap then?

**Comment by jackpot51** [comment]
Yep

**Comment by xliiv** [comment]
I'm using
- ubuntu 16.04
- installed libfuse-dev
but i still got this error

```
#TODO: filesystem/bin/test
CARGO_TARGET_DIR=build RUSTC="./rustc-i386.sh" cargo rustc --manifest-path crates/ion/Cargo.toml --bin ion-shell --verbose --target=i386-unknown-redox.json -- -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead_code -C lto
       Fresh peg v0.3.11
       Fresh termion v0.1.0 (https://github.com/jackpot51/termion.git#f8c3dd0e)
       Fresh glob v0.2.11
       Fresh ion-shell v0.1.2 (file:///home/xliiv/workspace/redox/redox/crates/ion)
rm -rf build/i386-unknown-redox/debug/filesystem.bin build/i386-unknown-redox/debug/filesystem/
echo exit | cargo run --manifest-path crates/redoxfs/Cargo.toml --bin redoxfs-utility build/i386-unknown-redox/debug/filesystem.bin
   Compiling fuse v0.2.7
error: failed to run custom build command for `fuse v0.2.7`
Process didn't exit successfully: `/home/xliiv/workspace/redox/redox/crates/redoxfs/target/debug/build/fuse-5b87eb71951205b4/build-script-build` (exit code: 101)
```

i ran already "./bootstrap.sh -u"

**Comment by thotheolh** [comment]
I am also seeing this error on Ubuntu 12.04 LTS.

**Comment by thotheolh** [comment]
```
   Compiling fuse v0.2.7
error: failed to run custom build command for `fuse v0.2.7`
Process didn't exit successfully: `/home/thotheolh/Desktop/Redox-OS/redox/crates/redoxfs/target/debug/build/fuse-39a670d2c21026d3/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\"` did not exit successfully: exit code: 1\n--- stdout\nPackage fuse was not found in the pkg-config search path.\nPerhaps you should add the directory containing `fuse.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'fuse\' found\n"', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.

make: *** [build/i386-unknown-redox/debug/filesystem.bin] Error 101
```

How do I know if I am missing anything ?

**Comment by bjorn3** [comment]
Pkg-config says:
```
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
```

**Comment by thotheolh** [comment]
sudo apt-get install libfuse-dev seems to handle this.

**Comment by origel** [comment]
wget https://github.com/libfuse/libfuse/releases/download/fuse_2_9_4/fuse-2.9.4.tar.gz

I fix this error use above fuse. just ./configure, make && make install
