### ISSUE TITLE
Build Fails (Manjaro)

### ISSUE THREAD

**Issue by BunnyApocalypse** [redox-os/redox#620]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]

I attempted to install rust using the auto install script. 

**Expected behavior**: [describe the behavior you would expect the repro to yield.]

It installs properly 

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].

At the end of the install script it returns this before telling me to make make all etc it gives me this error

`
Travis reports that the last build *FAILED* :(
Might want to check out the issues before building
`
Then, when i do cd into the redox directory and make all it returns 
```
mkdir -p build/i386-unknown-redox/debug
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead_code -o build/i386-unknown-redox/debug/libcore.rlib rust/src/libcore/lib.rs
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with RUST_BACKTRACE=1 for a backtrace
thread 'rustc' panicked at 'Field data-layout in target specification is required', ../src/librustc_back/target/mod.rs:370
stack backtrace:
   1:     0x7f162121a9f0 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x7f162122811b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x7f1621227cbc - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x7f16211eccaf - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   5:     0x7f16211eed98 - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
   6:     0x7f161d2800ca - rustc_back::target::Target::from_json::h0865f3d0efe9d5a8
   7:     0x7f161d2822bf - rustc_back::target::Target::search::load_file::h10b754eb1c29e7bb
   8:     0x7f161d2816ba - rustc_back::target::Target::search::h5d24d442a2ed9dcf
   9:     0x7f161db7c471 - rustc::session::config::build_target_config::h59bc6d485b6e9271
  10:     0x7f161db7a6bd - rustc::session::build_session_::h6f9ae75b9cc92e18
  11:     0x7f161db79631 - rustc::session::build_session::h01e19ac98308258a
  12:     0x7f162172af77 - rustc_driver::run_compiler::h8902aebf8b1849a8
  13:     0x7f1621728851 - std::sys_common::unwind::try::try_fn::h4c74456035d0fcc7
  14:     0x7f16212181cb - __rust_try
  15:     0x7f162121815d - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  16:     0x7f162172909a - _<F as std..boxed..FnBox<A>>::call_box::h27f542a39f1d61ef
  17:     0x7f16212262b4 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  18:     0x7f1619043423 - start_thread
  19:     0x7f1620e84cbc - clone
  20:                0x0 - <unknown>

Makefile:424: recipe for target 'build/i386-unknown-redox/debug/libcore.rlib' failed
make: *** [build/i386-unknown-redox/debug/libcore.rlib] Error 101

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]

```
`
[christopher@christopher-Manjaro redox]$ rustc -V
rustc 1.10.0-nightly (a0c325980 2016-04-20)
`
`
[christopher@christopher-Manjaro redox]$ git rev-parse HEAD
f1faf592be62eaa6a48e905e50a0a5ea6daf157b
`
`
[christopher@christopher-Manjaro ~]$ qemu-i386 -version
qemu-i386 version 2.5.0, Copyright (c) 2003-2008 Fabrice Bellard
`
`
[christopher@christopher-Manjaro ~]$ uname -a
Linux christopher-Manjaro 4.4.6-1-MANJARO #1 SMP PREEMPT Sat Mar 19 06:00:37 CET 2016 x86_64 GNU/Linux
`

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by DomThePorcupine** [comment]
Just a heads up, that message from the bootstrap is there for a reason (i.e. that is the expected behavior). To warn you that building won't work! I think in this case bootstrap did it's job correctly, and this issue is simply that something in the latest rust nightly broke building redox.
(If this is not the case and the bootstrap failed to do something please let me know!)

**Comment by nounoursheureux** [comment]
I got the same error on ArchLinux on the latest nightly.

**Comment by pmarcelll** [comment]
There was a breaking change in Rust: https://github.com/rust-lang/rust/pull/32939

**Comment by DomThePorcupine** [comment]
@BunnyApocalypse still getting the error or can this be closed?

**Comment by BunnyApocalypse** [comment]
It now works.
