### ISSUE TITLE
Use 'cake' for building.

### ISSUE THREAD

**Issue by ticki** [redox-os/redox#621]
Currently, we use Make, which is slow and annoying, for that reason, I made [cake](https://github.com/ticki/cake). We now need to rewrite the Makefile to Cake.

**Comment by SJFrK** [comment]
@ticki I started to convert the Makefile to cake at https://github.com/SJFrK/redox-baker

It's currently able to compile libcore.

I don't know if this is what you had in mind, but if it is I'll continue this way.

I didn't really look into macros in Rust yet, but is it somehow possible to add my `cmd()` to cake's `cmd!`? Or another idea how to handle the compiler flags from `v_rustc_flags()` more elegantly? Is there a way to expand a Vec or Array to a parameter list?

**Comment by ticki** [comment]
@SJFrK That's super awesome! I'll go over it and see if it can be added to `cake` itself.

**Comment by jackpot51** [comment]
Not likely to be done
