### ISSUE TITLE
Run Redox on OS X failing.

### ISSUE THREAD

**Issue by Viknet** [redox-os/redox#624]
**Reproduction**:
Build Redox with `make clean && make all`
Try to run `make qemu kvm=no`

**Expected behavior**:
Launching to desktop.

**Actual behavior**:
`init: failed to execute 'init': No such file or directory (os error 2)`

**Build information**:
```
git rev-parse HEAD
f59e32aaed3fba1edc8d8eee14e751515c57ebad
```
```
uname -a
Darwin Viktors-MBP 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```

**Misc**:
Probably error in running scripts (nonstandard "cp" flags on OS X works differently):
```
redoxfs: opened filesystem build/i386-unknown-redox/debug/filesystem.bin
cp -rL filesystem/* build/i386-unknown-redox/debug/filesystem/
cp: the -H, -L, and -P options may not be specified with the -r option.
make: [build/i386-unknown-redox/debug/filesystem.bin] Error 1 (ignored)
```

**Comment by jackpot51** [comment]
This should be fixed now. `-R` is now specified instead of `-r`
