### ISSUE TITLE
[Book] Dead Why MIT link

### ISSUE THREAD

**Issue by aidylewis** [redox-os/redox#628]
On the [Why Redox page](https://doc.redox-os.org/book/introduction/why_redox.html), the link to Why MIT is broken (https://doc.redox-os.org/book/why_mit.html). It should be this (https://doc.redox-os.org/book/introduction/why_mit.html).

**Comment by ca1ek** [comment]
I think that this should be reported here instead: https://github.com/redox-os/book/issues

**Comment by aidylewis** [comment]
Thanks for the heads up. Should I close this and open a book issue?

**Comment by ca1ek** [comment]
It's up to you. I don't rule here.

**Comment by aidylewis** [comment]
Appropriate place for bug report. https://github.com/redox-os/book/issues/46
