### ISSUE TITLE
[Book] Missing words on Microkernels page

### ISSUE THREAD

**Issue by aidylewis** [redox-os/redox#629]
On the [Microkernels page](https://doc.redox-os.org/book/design/kernel/microkernels.html#Microkernels) we currently have:

"""
Redox's kernel is a microkernel. Microkernels stands out in their design by providing minimal abstractions in kernel-space. Microkernels have an emphasis on user space, unlike Monolithic kernels which have an emphasis on .
"""
Do we need to add 'kernel space' at the end of the last sentence?

**Comment by ca1ek** [comment]
Fixed by https://github.com/redox-os/book/pull/45
