### ISSUE TITLE
[help wanted] Build error

### ISSUE THREAD

**Issue by SunyDays** [redox-os/redox#631]
**Reproduction**: make all ([compile-help](https://github.com/redox-os/redox#compile-help) didn't help)

**Expected behavior**: compilation finished without errors

**Actual behavior**: following error:
`RUST_BACKTRACE=1 rustc --target=x86_64-unknown-redox.json -L build/x86_64-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead_code -o build/x86_64-unknown-redox/debug/libcore.rlib rust/src/libcore/lib.rs`
`multirust: no default toolchain configured`
`Makefile:427: recipe for target 'build/x86_64-unknown-redox/debug/libcore.rlib' failed`
`make: *** [build/x86_64-unknown-redox/debug/libcore.rlib] Error 1`

**Build information**:
`$ multirust show-override`
`rustc 1.10.0-nightly (8da2bcac5 2016-04-28)`
`cargo 0.11.0-nightly (afac7fc 2016-04-27)`

`$ uname -a`
`Linux sunydays 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux`

**Comment by pmarcelll** [comment]
What happens when you run ```rustc -Vv```?
There seems to be a problem with your multirust configuration. Have you tried [rustup.rs](https://www.rustup.rs/)?

**Comment by bjorn3** [comment]
Does `multirust default nightly` resolve the issue?

**Comment by SunyDays** [comment]
HI! Remove and set again multirust override helped me.

**Comment by SunyDays** [comment]
@bjorn3, no

**Comment by jackpot51** [comment]
We do not support x86_64 redox at the moment, many pieces of the kernel are not correct for 64-bit. Please set ARCH back to i386 and then run `make clean`

**Comment by SunyDays** [comment]
@jackpot51, thanks, this help me
