### ISSUE TITLE
Mouse disappearance after starting orbital with qemu

### ISSUE THREAD

**Issue by Csega** [redox-os/redox#633]
**Reproduction**: run 'sudo make qemu kvm=no', then start orbital

**Expected behavior**: a working mouse pointer on the screen

**Actual behavior**: the mouse pointer disappears, and sodium starts, when I move the mouse or click (anywhere).

**Build information**: rustc 1.10.0-nightly (8da2bcac5 2016-04-28), d0d84010c9f5bd9f56dbb3dbb6f5b67c6404f39c, qemu-i386 version 2.0.0 (Debian 2.0.0+dfsg-2ubuntu1.22), Copyright (c) 2003-2008 Fabrice Bellard, Linux eOS 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]
---

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by ca1ek** [comment]
Cursor vanishing is a symptom of a page fault.

I also had sodium start up randomly a couple of times, but, it didn't happen every time I ran Redox.

**Comment by jackpot51** [comment]
This has been fixed in the new kernel
