### ISSUE TITLE
Can't `make qemu` the latest commit

### ISSUE THREAD

**Issue by ca1ek** [redox-os/redox#641]
**Reproduction**: Clone redox, then `make qemu`.

**Expected behavior**: Build would start, then qemu would run
**Actual behavior**: I get this error: 

    make: *** No rule to make target `crates/bitflags/src/lib.rs', needed by `build/i386-unknown-redox/debug/libbitflags.rlib'. Stop.

**Build information**: n/a

**Blocking/related**: n/a

**Misc**: terminal commands I ran: https://gist.github.com/ca1ek/2995712dbe335100947328ba3c1f7092

**Comment by jackpot51** [comment]
Did you clone recursively?

If not, you need to run git submodule update --init --recursive

**Comment by ca1ek** [comment]
yeah, I'm just dumb, sorry for that.
