### ISSUE TITLE
Make fails to build on x86

### ISSUE THREAD

**Issue by Dietr1ch** [redox-os/redox#642]
**Reproduction**: `make all`

**Expected behavior**: compiles

**Actual behavior**: `make: *** No rule to make target 'crates/bitflags/src/lib.rs', needed by 'build/i386-unknown-redox/debug/libbitflags.rlib'.  Stop.`

**Build information**:
rustc -V:
```
rustc 1.10.0-nightly (2b79e05a0 2016-05-13)
```
multirust show-override:
```
multirust show-override
multirust: override toolchain: nightly
multirust: override location: ~/.multirust/toolchains/nightly
multirust: override reason: directory override for '~/.../redox'

rustc 1.10.0-nightly (2b79e05a0 2016-05-13)
cargo 0.11.0-nightly (7199e24 2016-05-12)
```

git log:
```8bdff5d - (13 minutes ago)  Remove rust bmp from home directory - Jeremy Soller   (HEAD -> master, origin/master, origin/HEAD)```

qemu-i386 -version:
```qemu-i386 version 2.5.1, Copyright (c) 2003-2008 Fabrice Bellard```
uname -a:
```Linux () 4.6.0-1-MANJARO #1 SMP PREEMPT Mon May 9 19:59:36 UTC 2016 i686 GNU/Linux```

**Comment by jackpot51** [comment]
Please execute `git submodule update --init --recursive`

**Comment by Dietr1ch** [comment]
Apparently it was just that, I forgot to get the submodules on this machine.
I'll close the report if the ongoing build succeeds.

Thanks for the quick response (=

**Comment by jackpot51** [comment]
Ok, thanks

**Comment by Dietr1ch** [comment]
It worked (=

I added a special warning for this error. It may help new guys in the future

**Comment by DomThePorcupine** [comment]
Why not bootstrap? ¯\_(ツ)_/¯

**Comment by Dietr1ch** [comment]
You mean doing the submodule get/update on the default target?

It seems it may bring trouble for devs, and it adds little help to new users

**Comment by DomThePorcupine** [comment]
Having a script to set up a clean dev environment with all proper dependencies installed is bad for new users?

**Comment by Dietr1ch** [comment]
Maybe it can become a new rule, like

```Makefile
init:
  git submodule
  make all
  # ...
```

And make the `%` target suggest running `make init`

**Comment by DomThePorcupine** [comment]
I am talking(joking) about bootstrap.sh which we have that should prevent newbies from having the problem in the first place. Which if you didn't know can be used with -u to update once the initial clone has been done.

**Comment by Dietr1ch** [comment]
Oh, then it might be a better suggestion to run `bootstrap.sh` :P

**Comment by DomThePorcupine** [comment]
Just out of curiosity was this the first time you tried to build Redox?

**Comment by Dietr1ch** [comment]
I think it was the third, I succeed on last night, but today I grabbed an old repo (the one from the first time) and got the error.
After reading the suggestion I realized that I had 2 copies of redox lying around and that the other one was the one that correctly worked just a few commits ago.

**Comment by ca1ek** [comment]
Never knew about it. -u is undocumented

-----Wiadomość oryginalna-----
Od: "DomThePorcupine" <notifications@github.com>
Wysłano: ‎2016-‎05-‎15 21:23
Do: "redox-os/redox" <redox@noreply.github.com>
Temat: Re: [redox-os/redox] Make fails to build on x86 (#642)

I am talking(joking) about bootstrap.sh which we have that should prevent newbies from having the problem in the first place. Which if you didn't know can be used with -u to update once the initial clone has been done.

**Comment by DomThePorcupine** [comment]
Yeah sorry, here is the function inside bootstrap:
```
if [ "$1" == "-u" ]; then
	git pull origin master
	git submodule update --recursive --init
	multirust update nightly
	exit
fi
```
