### ISSUE TITLE
Chat Server not loading properly.

### ISSUE THREAD

**Issue by stratact** [redox-os/redox#649]
@ticki is there something lagging the Mattermost server? I'm not able to get to the login prompt.

**Comment by ca1ek** [comment]
I too got the same issue

**Comment by stratact** [comment]
@ca1ek how long have you been experiencing this issue?

**Comment by ca1ek** [comment]
I got the email about a new issue and went to check it for myself. So, 1 minute after this issue was posted.

**Comment by stratact** [comment]
Thanks for verifying then.

**Comment by ca1ek** [comment]
It's not just Mattermost being broken, the server doesn't respond to pings, but for some reason when attempting to load the webpage it doesn't time out.

**Comment by stratact** [comment]
`traceroute` is also showing packets being dropped continuously with the `* * *` output.

**Comment by stratact** [comment]
Is there a server flood going on?

**Comment by stratact** [comment]
*Tries to summon the Kon-Tiki*
@ticki

**Comment by ticki** [comment]
Damn.

**Comment by ticki** [comment]
I'm investigating.

**Comment by stratact** [comment]
Yeah, it was painful. :smile:

**Comment by ticki** [comment]
Aaand, it's back!

**Comment by stratact** [comment]
There is happiness! :smiley:

**Comment by ticki** [comment]
There be :cake: .

**Comment by stratact** [comment]
@ticki Getting a `502 Bad Gateway` error and can't get back my session.

**Comment by ca1ek** [comment]
Yep, it's broken.

**Comment by stratact** [comment]
@ticki was updating the server, closed.

**Comment by ca1ek** [comment]
@stratact it's broken again, reopen please.

**Comment by ca1ek** [comment]
Seems like SSL certificate is broken, will create new issue
