### ISSUE TITLE
Migrate `common::memory::{alloc, unalloc}` and friends to use the new `Memory` type

### ISSUE THREAD

**Issue by stratact** [redox-os/redox#65]
I don't know how to go about this. So I would like some instructions on what to do in cases like this:
````
% make all
rustc --target=i686-unknown-redox-gnu.json -C no-vectorize-loops -C no-vectorize-slp -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead-code -A deprecated -L build -C lto -o build/kernel.rlib src/kernel.rs
src/audio/ac97.rs:73:23: 73:81 error: non-scalar cast: `common::memory::Memory` as `*mut audio::ac97::BD`
src/audio/ac97.rs:73                 bdl = Memory::new(32 * mem::size_of::<BD>()).unwrap() as *mut BD;
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Makefile:148: recipe for target 'build/kernel.rlib' failed
make: *** [build/kernel.rlib] Error 101
```

**Comment by stratact** [comment]
Also, what to use instead of panicking with `unwrap()`?

**Comment by jackpot51** [comment]
Drivers at this point cannot panic, the kernel cannot panic. You must store the Option<Memory> and match it every time or cascade the option all the way up.

I hope you understand, it would be very bad to panic inside the kernel :-)

**Comment by stratact** [comment]
Yeah I knew panic wasn't the right option, I just did it so I can test the code in a quick manner.

**Comment by stratact** [comment]
@jackpot51 btw, what should do for cases when it hits `Option::None`?

**Comment by jackpot51** [comment]
I'm going in to AC97 to try something, is that ok?

**Comment by stratact** [comment]
Go for it boss

**Comment by stratact** [comment]
Just to show you what I was thinking, I planning on something like this:
````rust
let bdl = memory::alloc(2 * mem::size_of::<BD>()) as *mut BD;
````
to
````rust
let bdl = Memory::<BD>::alloc(2).unwrap_or_else(/* Something goes here for None */);
````

Hope this helps you.

**Comment by jackpot51** [comment]
Well darn, the lifetime can't be tracked because the memory is written into a register.

**Comment by jackpot51** [comment]
The drop could happen at any point after

**Comment by jackpot51** [comment]
This could hypothetically be fixed with a PIOBAR struct, or similar, that makes sure the I/O is set to zero before the memory is dropped

**Comment by jackpot51** [comment]
struct BDBAR {
    memory: Memory<BD>,
    port: PIO32,
}

**Comment by jackpot51** [comment]
I love rust :)

**Comment by stratact** [comment]
I'd say make a trait for PIO that impl for PIO8, PIO16, PIO32, so you can do something like this:
````rust
struct BDBAR<T: PIO> {
    memory: Memory,
    port: T,
}
````

**Comment by jackpot51** [comment]
The thing is, the requirements for driver address registers are very different. Some require extra flags added to the address, or different alignments.

You cannot generalize this, EHCI for example requires 1 to be or'ed with the memory address, AC97 does not
