### ISSUE TITLE
Switch from multirust to rustup

### ISSUE THREAD

**Issue by SJFrK** [redox-os/redox#651]
I'd like to start a motion to move from multirust to [rustup](https://www.rustup.rs/) in bootstrap.sh.

According to the multirust repository it is not maintained anymore and recommends to migrate to rustup, which is an official Rust project.

The change shouldn't be too difficult (at least on Linux and OSX, I don't know how it's handled in Windows), since the syntax is the same as in multirust.

**Comment by DomThePorcupine** [comment]
Not difficult at all, I had no idea it was no longer being maintained. If others agree I'll push the changes today.

**Comment by ca1ek** [comment]
> The change shouldn't be too difficult (at least on Linux and OSX, I don't know how it's handled in Windows)

We don't support Windows at the moment anyways. Or at least I think so.

**Comment by goolic** [comment]
Closed ?

**Comment by DomThePorcupine** [comment]
@goolic not closed. I didn't see all the reactions on my comment, apparently github doesn't send notifications about them. The changes are local on my machine and the pull request will be up later today. I added a couple extras to it as well!
