### ISSUE TITLE
Race conditions in the kernel

### ISSUE THREAD

**Issue by ticki** [redox-os/redox#654]
**Reproduction**: A severe overuse of UnsafeCell results in serious data races.

**Expected behavior**: Use some form of sync primitive, e.g. Mutex.

**Actual behavior**: No form of syncronization primitive.

**Blocking/related**: Related to #652.

**Misc**: I am working on a patch for many of these cases.

**Comment by jackpot51** [comment]
This has been fixed in the new kernel
