### ISSUE TITLE
Boostrap script does not download Redox repositories

### ISSUE THREAD

**Issue by Csega** [redox-os/redox#658]
**Reproduction**: Run bootstrap script: curl -sf https://raw.githubusercontent.com/redox-os/redox/master/bootstrap.sh -o bootstrap.sh && bash -e bootstrap.sh

**Expected behavior**: Download the newest Rust version and download the repositories.

**Actual behavior**: The newest Rust version (changing multirust to rustup) is installed, but the redox repositories are not copied.

**Build information**: rustc 1.11.0-nightly (ad7fe6521 2016-06-23), qemu-i386 version 2.0.0 (Debian 2.0.0+dfsg-2ubuntu1.24), Copyright (c) 2003-2008 Fabrice Bellard, Linux eOS 3.19.0-61-generic #69~14.04.1-Ubuntu SMP Thu Jun 9 09:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by lucarin91** [comment]
same issue here.

**Comment by DomThePorcupine** [comment]
Sorry guys, absolutely 100% my bad. @Csega did it transition you over to rustup okay?

**Comment by Csega** [comment]
Yes, it works, however, the were some minor problems in the .bashrc file. The export PATH="$HOME/.cargo/bin:$PATH" line were present multiple times and the first one was merged together with the last esac keyword. I manually adjusted it and now the PATH is set correctly too.
