### ISSUE TITLE
error: unrecognized intrinsic function: `return_address` [E0093]

### ISSUE THREAD

**Issue by ArrogantWombatics** [redox-os/redox#660]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Did a git pull on the recent tree, and removed the current directory, and git cloned the repo again. Ran make clean ; git clean -X -f -d ; git submodule update --recursive --init ; make all 

**Expected behavior**: [describe the behavior you would expect the repro to yield.]
Would expect for the make all command to produce a working copy of the OS.

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead_code -o build/i386-unknown-redox/debug/libcore.rlib rust/src/libcore/lib.rs
rust/src/libcore/intrinsics.rs:290:5: 290:42 error: unrecognized intrinsic function: `return_address` [E0093]
rust/src/libcore/intrinsics.rs:290     pub fn return_address() -> *const u8;
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust/src/libcore/intrinsics.rs:290:5: 290:42 help: run `rustc --explain E0093` to see a detailed explanation
error: aborting due to previous error

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]
This happens for both x86_64 build and 386 build.
rustc --version
rustc 1.11.0-dev (366de839a 2016-06-28)
cargo --version
cargo 0.12.0-nightly (3323134 2016-06-28)
uname -a
Linux *masked* 4.6.2-1-ARCH #1 SMP PREEMPT Wed Jun 8 08:40:59 CEST 2016 x86_64 GNU/Linux

This also happens on this machine :: 
rustc --version
rustc 1.11.0-dev (366de839a 2016-06-28)
cargo --version
cargo 0.12.0-nightly (50dad37 2016-06-21)
uname -a
Linux *masked* 4.6.0-7-generic #8-Ubuntu SMP Fri Jun 3 15:08:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by lfairy** [comment]
The intrinsic was added back in rust-lang/rust#34580, so it should start working again with the next nightly.

**Comment by ArrogantWombatics** [comment]
This is resolved at this time.

**Comment by pnkfelix** [comment]
Is redox actually using the return_address intrinsic?  Or did you just cooy and paste the full list at some point? 

(I ask because we are still planning to remove that intrinsic eventually;  we didn't think any one but Servo was using it, and MIR makes it more broken than it already is. )

**Comment by lfairy** [comment]
@pnkfelix the error is in an outdated version of libcore. Redox itself doesn't use the intrinsic.

**Comment by eddyb** [comment]
Is Redox compiling a libcore of a different Rust version than the one from the sources for the nightly in use? Because that is not supported and `rustc -vV` should be used instead to determine the right revision to build anything from.

**Comment by ticki** [comment]
> Is Redox compiling a libcore of a different Rust version than the one from the sources for the nightly in use?

We compile directly from source, fetched as a submodule, revision `edb6f83`.

**Comment by eddyb** [comment]
@ticki Then only a nightly with that revision is guaranteed to be able to compile it correctly.

**Comment by jawbonegroove** [comment]
um yes, if anything other than the latest nightly is being used, we need to know or our toolchains break... 

are there other submodules we should be watching for this? I'm assuming it's going to come and go a little, by nature of using a rolling toolchain...perhaps a live list of modules other than latest nightly being used?

**Comment by dcampbell24** [comment]
I think #665 should probably be closed and this ticket reopened. Is the solution to this issue to update libcore? Temporarily, the nightly version could be pinned to a known working version.

**Comment by dcampbell24** [comment]
rust-lang/rust#34648 reverted the revert.

**Comment by eddyb** [comment]
I would *highly* suggest automatically checking out the same git revision as reported by `rustc -vV`, or pinning the supported nightly (like Servo does) if that's not feasible.
You might even be able to integrate with rustup.
