### ISSUE TITLE
No function `return_address` found while compiling 

### ISSUE THREAD

**Issue by girishramnani** [redox-os/redox#665]
**Reproduction**:  get a ubuntu 16.10 server ec2 t2.meduim and run the bootstrap.sh as given in the building portion and then` make all`

**Expected behavior**: the code should compile

**Actual behavior**:  this error shows up
```bash
girish@girish:~/redox/redox$ make all
mkdir -p build/i386-unknown-redox/debug
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=3 -Z no-landing-pads -A dead_code -o build/i386-unknown-redox/debug/libcore.rlib rust/src/libcore/lib.rs
rust/src/libcore/intrinsics.rs:290:5: 290:42 error: unrecognized intrinsic function: `return_address` [E0093]
rust/src/libcore/intrinsics.rs:290     pub fn return_address() -> *const u8;
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust/src/libcore/intrinsics.rs:290:5: 290:42 help: run `rustc --explain E0093` to see a detailed explanation
error: aborting due to previous error
Makefile:474: recipe for target 'build/i386-unknown-redox/debug/libcore.rlib' failed
make: *** [build/i386-unknown-redox/debug/libcore.rlib] Error 101

```
**Build information**: 
```
rustc -V
rustc 1.12.0-nightly (5e18b4bad 2016-07-08)
girish@girish:~$ cargo -V
cargo 0.13.0-nightly (d263690 2016-07-07)
```

**Misc**: i am using a blank ( just spinned up to compile redox) ubuntu 16.10 server on ec2.

---

**Comment by girishramnani** [comment]
Same as #660 , but using nightly build of 07-08

**Comment by marulitua** [comment]
Same here on Arch linux with rustc 1.12.0-nightly (5e18b4bad 2016-07-08)

**Comment by dcampbell24** [comment]
The intrinsic was removed again https://github.com/rust-lang/rust/pull/34648.

**Comment by girishramnani** [comment]
so how to resolve this issue now? use an older build?

**Comment by Zarokka** [comment]
as a workaround for now nightly-2016-07-04 seems to work
e.g. with rustup
```
rustup override set nightly-2016-07-04
```

**Comment by jackpot51** [comment]
I will be updating our Rust fork now, to match rust-lang/rust

**Comment by jackpot51** [comment]
Our Rust has been updated, Redox should build with the newest nightly now
