### ISSUE TITLE
multirust Deprecated

### ISSUE THREAD

**Issue by dteal** [redox-os/redox#667]
**Problem**: [describe the problem you try to solve with this issue.]
README.md recommends [multirust](https://github.com/brson/multirust), whose documentation states it has been deprecated in favor of [rustup.rs](https://github.com/rust-lang-nursery/rustup.rs). This might be worth consideration (though maybe multirust is still preferred and works just fine, IDK).

**Comment by dcampbell24** [comment]
I think we should suggest to people to use rustup.rs.
