### ISSUE TITLE
Cant't Login Into

### ISSUE THREAD

**Issue by Kuchiriel** [redox-os/redox#670]
login:
root/whatever
whatever/root
redox/whatever
whatever/redox
blank/whatever
whatever/blank

None of these seens to work.

Installed from ISO into Virtual Box

**Comment by ca1ek** [comment]
Login prompt is just a decoy as of now. There is no user account system. Just press enter at the prompt.

It should let you trough no matter what you typed in, as long as you pressed enter. I haven't checked the latest builds though. I have to take a look

**Comment by DomThePorcupine** [comment]
Closed?

**Comment by CV001A** [comment]
root/password
