### ISSUE TITLE
fatal: repository 'https://github.com/redox-os/liblibc.git/' not found

### ISSUE THREAD

**Issue by ArrogantWombatics** [redox-os/redox#673]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
git submodule update --recursive --init

**Expected behavior**: [describe the behavior you would expect the repro to yield.]
pull all of the submodules for Redox

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
remote: Repository not found.
fatal: repository 'https://github.com/redox-os/liblibc.git/' not found
fatal: clone of 'https://github.com/redox-os/liblibc.git' into submodule path 'crates/liblibc' failed

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
git rev-parse HEAD
3d384c92cfe3c094fb663ae60974a0824cbdb908
rustc -V
rustc 1.12.0-dev (2c50f4e48 2016-07-23)
uname -a
Linux *masked* 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
qemu-i386 -version
qemu-i386 version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.2), Copyright (c) 2003-2008 Fabrice Bellard

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by jackpot51** [comment]
This error should be fixed now. Please try to git submodule update again.
