### ISSUE TITLE
Installation does not boot

### ISSUE THREAD

**Issue by Qiangong2** [redox-os/redox#674]
I'm trying to install RedoxOS on an HP Elite X2, but when I run the installer, it does not boot.

**Comment by Qiangong2** [comment]
The OS itself. The installer works fine

**Comment by paulmenzel** [comment]
Could you provide more details? What happens after you start Redox? Is there just a black screen? Is there any output?

**Comment by Qiangong2** [comment]
I can't even get into redox. It claims there is no boot device found. When I boot using a Linux live cd, I can see that redox is installed though.

**Comment by jackpot51** [comment]
Redox only supports a small number of machines, it is better to use virtualization to test it for the time being.
