### ISSUE TITLE
What happened to "This Week in Redox"?

### ISSUE THREAD

**Issue by flosse** [redox-os/redox#675]
I'm quite curious how everything is going on :) And I'd love to read a new TWR :)

**Comment by ca1ek** [comment]
summoning @ticki

**Comment by ticki** [comment]
It isn't dead! It's just on summer vacation. I plan to write a "This Summer in Redox".

**Comment by flosse** [comment]
Awesome! I'm looking forward to read the next TWiR :)

**Comment by jackpot51** [comment]
http://www.redox-os.org/news/the-internet-on-redox/
