### ISSUE TITLE
Fetching termion fails

### ISSUE THREAD

**Issue by Powersource** [redox-os/redox#677]
**Reproduction**: Run all the "won't compile" steps (before intending to build) in the readme up to and including the submodule update.

**Expected behavior**: It successfully fetching submodules.

**Actual behavior**:

```
me@pc[rust/redox]% git submodule update --recursive --init
error: no such remote ref 95bce6092a38c443d0b71473d9574ee8bccc8964
Fetched in submodule path 'crates/termion', but it did not contain 95bce6092a38c443d0b71473d9574ee8bccc8964. Direct fetching of that commit failed.
me@pc[rust/redox]%
```

And building fails when it gets to termion related things.

**Build information**: `rustc 1.12.0-nightly (9316ae515 2016-07-24)`, `git rev-parse HEAD` `4153b4ab9f2f67cadc0411fa3af6a0572a4abc9b`, `Linux pc 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux`

**Comment by jackpot51** [comment]
Run `git submodule sync`

**Comment by Powersource** [comment]
Thanks!
