### ISSUE TITLE
Pagefault if system has 4GB RAM or more

### ISSUE THREAD

**Issue by dns2utf8** [redox-os/redox#686]
**Reproduction**: qemu-system-x86_64 -m 4G -s -enable-kvm -hda redox-harddrive.qcow2 -vga std -usb -device usb-tablet

**Expected behavior**: The rest of the RAM should not be used, but cause no harm

**Actual behavior**: Pagefault, PID 1: kidle

**Build information**: the [qcow2](https://static.redox-os.org/redox-harddrive.qcow2.xz) of today

**Blocking/related**: unknown

**Misc**: Base OS is Arch Linux
---

Regards dns2utf8

**Comment by NilSet** [comment]
Only i386 is supported at the moment.

**Comment by jackpot51** [comment]
No longer applies to new kernel
