### ISSUE TITLE
Move crates/orbital to its own repo

### ISSUE THREAD

**Issue by rushsteve1** [redox-os/redox#687]
The contents of `crates/orbital` is the actual orbital display server, and fitting its importance should be moved to its own repository for clarity and ease of future development.
This would of course have to be done by a member of the main team @jackpot51 @ticki and co.

**Comment by rushsteve1** [comment]
Self Bumping and calling @jackpot51 @ticki @stratact or anyone with the permissions to do this. Sorry to be annoying but this is a 5 minute task that would add a lot of clarity.

**Comment by stratact** [comment]
Here you go: https://github.com/redox-os/orbital

**Comment by rushsteve1** [comment]
Can we get this Submoduled in?

**Comment by rushsteve1** [comment]
Alright its done.
