### ISSUE TITLE
No such remote ref crates/ralloc

### ISSUE THREAD

**Issue by et4te** [redox-os/redox#692]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]

curl -sf https://raw.githubusercontent.com/redox-os/redox/master/bootstrap.sh -o bootstrap.sh && bash -e bootstrap.sh

**Expected behavior**: [describe the behavior you would expect the repro to yield.]

I expect this command to bootstrap redox.

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].

error: no such remote ref 470d5810c5f4d0329f666438ee3bdf8d8e4b2913
Fetched in submodule path 'crates/ralloc', but it did not contain 470d5810c5f4d0329f666438ee3bdf8d8e4b2913. Direct fetching of that commit failed.

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]

rustc 1.12.0-nightly (1225e122f 2016-07-30)
qemu-i386 version 2.6.0, Copyright (c) 2003-2008 Fabrice Bellard
Linux nixos 4.6.5 #1-NixOS SMP Wed Jul 27 15:42:34 UTC 2016 x86_64 GNU/Linux

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

N/A

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by ca1ek** [comment]
This commit totally exists: https://github.com/redox-os/ralloc/commit/470d5810c5f4d0329f666438ee3bdf8d8e4b2913

Have you tried running the bootstrap script again?

**Comment by Rostepher** [comment]
I am also experiencing this problem.

**Comment by NilSet** [comment]
I think @ticki rebased and force pushed after the submodule was updated. Github keeps orphaned commits around for a while but I don't think it let's you fetch them without there being a ref.

**Comment by jackpot51** [comment]
Can someone pr a submodule pull?

**Comment by NilSet** [comment]
Submitted
