### ISSUE TITLE
build failed ( recipe for target 'build/i386-unknown-redox/debug/libcore.rlib' failed )

### ISSUE THREAD

**Issue by basiliscos** [redox-os/redox#702]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]

make all

**Expected behavior**: [describe the behavior you would expect the repro to yield.]

compiled redox

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].

```
 make all                        
mkdir -p build/i386-unknown-redox/debug
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json --cfg redox -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=3 -Z no-landing-pads -A dead_cod
e -o build/i386-unknown-redox/debug/libcore.rlib rust/src/libcore/lib.rs
error[E0433]: failed to resolve. Could not find `Carrier` in `ops`
   --> rust/src/libcore/num/dec2flt/mod.rs:217:40
    |
217 |         ParseResult::Valid(decimal) => convert(decimal)?,
    |                                        ^^^^^^^^^^^^^^^^^ Could not find `Carrier` in `ops`

....
error[E0093]: unrecognized intrinsic function: `init_dropped`
   --> rust/src/libcore/intrinsics.rs:258:5
    |
258 |     pub fn init_dropped<T>() -> T;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unrecognized intrinsic

error: aborting due to previous error

Makefile:510: recipe for target 'build/i386-unknown-redox/debug/libcore.rlib' failed
make: *** [build/i386-unknown-redox/debug/libcore.rlib] Error 101
````

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]

rustc -V
rustc 1.13.0-nightly (198713106 2016-08-26)

git rev-parse HEAD
ea5a43e63e5855e06d19f4708f3d4bdca4e91d6b

qemu-i386 -version
zsh: command not found: qemu-i386

uname -a
Linux hydra 4.4.11 #2 SMP Thu Jul 7 13:03:52 MSK 2016 x86_64 Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz GenuineIntel GNU/Linux

rustup --version
rustup 0.6.1 (71f7482 2016-08-24)

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by stratact** [comment]
@jackpot51 the rust submodule needs to be updated.

**Comment by basiliscos** [comment]
I've executed 

```
git submodule update rust 
```

but the result is same

**Comment by stratact** [comment]
You did everything correct. Since our Rust submodule points to a commit from the rust-lang/rust repo 16 days ago, the command is only going to update to that point and it's out of date for rust-nightly.

**Comment by antonycourtney** [comment]
@stratact Thanks for the info. I'm a newcomer to Redox, spent most of yesterday running bootstrap.sh to download everything, and now also hitting this. What needs to be done to bring the rust sub-module up to date with rust-nightly? Is there any workaround or anything relative noobs can do to help resolve this?

**Comment by jeandudey** [comment]
@antonycourtney Yes, just:
```bash
cd rust
git pull origin master
```

**Comment by jeandudey** [comment]
However it leads to a new error:
```
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json --cfg redox -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=3 -Z no-landing-pads -A dead_code -o build/i386-unknown-redox/debug/libstd.rlib libstd/src/lib.rs -L native=libc/lib/
error[E0557]: feature has been removed
  --> libstd/src/lib.rs:43:12
   |
43 | #![feature(unsafe_no_drop_flag)]
   |            ^^^^^^^^^^^^^^^^^^^

error: The attribute `unsafe_no_drop_flag` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> libstd/src/collections/hash_map.rs:79:5
   |
79 |     #[unsafe_no_drop_flag]
   |     ^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: aborting due to previous error
```

**Comment by jackpot51** [comment]
This should be fixed now
