### ISSUE TITLE
Build Error: AssertParamIsEq and AssertParamIsClone are 'undefined or not in scope'

### ISSUE THREAD

**Issue by jeromefroe** [redox-os/redox#709]
Hello, I'm having difficulties building redox. I pulled from master today and am using the nightly version of Rust but am getting an error when compiling rust/src/libcore/lib.rs as described below. I think the error may be related to my linker not being able to find `AssertParamIsEq` and `AssertParamIsClone` in libcore. Has anyone seen an error like this before by chance? Thanks.

**Reproduction**: `make all`, more specifically the following command: 
```
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json --cfg redox -L \
build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C \
opt-level=3 -Z no-landing-pads -A dead_code -C ar=i386-elf-ar -C linker=i386-elf-gcc \
-o build/i386-unknown-redox/debug/libcore.rlib rust/src/libcore/lib.rs
```

**Expected behavior**: redox is built successfully

**Actual behavior**: I see the following errors related to `AssertParamIsEq` and `AssertParamIsClone` being `undefined or not in scope`. From what I can tell both `AssertParamIsEq` and `AssertParamIsClone`are defined in libcore so I believe this may be a problem with my linker. A sample of the output is as follows:

```
error[E0412]: type name `cmp::AssertParamIsEq` is undefined or not in scope
  --> rust/src/libcore/num/mod.rs:46:70
   |
46 | pub struct Wrapping<T>(#[stable(feature = "rust1", since = "1.0.0")] pub T);
   |                                                                      ^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `AssertParamIsEq` found in your project; maybe you misspelled the name or forgot to import an external crate?

error[E0412]: type name `clone::AssertParamIsClone` is undefined or not in scope
  --> rust/src/libcore/num/flt2dec/decoder.rs:27:5
   |
27 |     pub mant: u64,
   |     ^^^^^^^^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `AssertParamIsClone` found in your project; maybe you misspelled the name or forgot to import an external crate?

error[E0412]: type name `clone::AssertParamIsClone` is undefined or not in scope
  --> rust/src/libcore/num/flt2dec/decoder.rs:29:5
   |
29 |     pub minus: u64,
   |     ^^^^^^^^^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `AssertParamIsClone` found in your project; maybe you misspelled the name or forgot to import an external crate?

error[E0412]: type name `clone::AssertParamIsClone` is undefined or not in scope
  --> rust/src/libcore/num/flt2dec/decoder.rs:31:5
   |
31 |     pub plus: u64,
   |     ^^^^^^^^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `AssertParamIsClone` found in your project; maybe you misspelled the name or forgot to import an external crate?
```

The same type of errors appears about forty or so more times.

**Build information**: 

`rustc -V`: rustc 1.13.0-nightly (55bf6a4f8 2016-09-18)

`git rev-parse HEAD`: fdfa25858bae41516ab495a042d8cc8cf0d8c565

`qemu-system-i386 -version`: QEMU emulator version 2.7.0, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers

`uname -a`: Darwin jeromefroe-C02RN36CFVH8 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

**Blocking/related**: N/A

**Misc**: N/A

**Comment by EGhiorzi** [comment]
Confirm the issue, I get the same on macOS (and I tried all troubleshooting procedures multiple times with no result). The only changes I can think of since I last built successfully are

- switching from OSX 10.11 to 10.12
- updating fuse to 3.5.x

**Comment by bjorn3** [comment]
`git submodule update --origin` should work.

Note to redox maintainers (@jackpot51 and others): maybe use xargo to automatically get and compile the right libcore.

**Comment by dingensundso** [comment]
Same errors on my system:
`rustc -V` rustc 1.13.0-nightly (4f9812a59 2016-09-21)
`git rev-parse HEAD` fdfa25858bae41516ab495a042d8cc8cf0d8c565
`uname -a` Linux lokalhorst.lan 4.4.3-300.fc23.x86_64 #1 SMP Fri Feb 26 18:45:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux


@bjorn3 did you mean `git submodule update --remote`?
After doing that I no longer get the errors mentioned above. But building still fails because of unresolved imports in ralloc. 

    error[E0432]: unresolved import `shim::config`
      --> crates/ralloc/src/allocator.rs:12:5
       |
    12 | use shim::config;
       |     ^^^^^^^^^^^^ no `config` in `shim`
 
    error[E0432]: unresolved import `shim::config`
     --> crates/ralloc/src/bookkeeper.rs:8:5
      |
    8 | use shim::config;
      |     ^^^^^^^^^^^^ no `config` in `shim`
 
    error[E0432]: unresolved import `shim::syscalls`
      --> crates/ralloc/src/brk.rs:10:12
       |
    10 | use shim::{syscalls, config};
       |            ^^^^^^^^ no `syscalls` in `shim`
 
    error[E0432]: unresolved import `shim::config`
      --> crates/ralloc/src/brk.rs:10:22
       |
    10 | use shim::{syscalls, config};
       |                      ^^^^^^ no `config` in `shim`
 
    error[E0432]: unresolved import `shim::config`
     --> crates/ralloc/src/fail.rs:8:5
      |
    8 | use shim::config;
      |     ^^^^^^^^^^^^ no `config` in `shim`
 
    error[E0433]: failed to resolve. Could not find `syscalls` in `shim`
      --> crates/ralloc/src/sync.rs:45:13
       |
    45 |             shim::syscalls::sched_yield();
       |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `syscalls` in `shim`

**Comment by EGhiorzi** [comment]
Same here. I would add that `git submodule update --remote --recursive` enters an infinite loop, of which this is an extract:
```
Submodule path 'rust/src/rust-installer/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1': checked out '755bc3db4ff795865ea31b5b4f38ac920d8acacb'
Submodule path 'rust/src/rust-installer/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1': checked out '755bc3db4ff795865ea31b5b4f38ac920d8acacb'
Submodule path 'rust/src/rust-installer/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1': checked out '755bc3db4ff795865ea31b5b4f38ac920d8acacb'
Submodule path 'rust/src/rust-installer/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1': checked out '755bc3db4ff795865ea31b5b4f38ac920d8acacb'
Submodule path 'rust/src/rust-installer/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1': checked out '755bc3db4ff795865ea31b5b4f38ac920d8acacb'
Submodule path 'rust/src/rust-installer/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1': checked out '755bc3db4ff795865ea31b5b4f38ac920d8acacb'
Submodule path 'rust/src/rust-installer/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1': checked out '755bc3db4ff795865ea31b5b4f38ac920d8acacb'
Submodule path 'rust/src/rust-installer/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1': checked out '755bc3db4ff795865ea31b5b4f38ac920d8acacb'
Submodule path 'rust/src/rust-installer/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1': checked out '755bc3db4ff795865ea31b5b4f38ac920d8acacb'
Submodule path 'rust/src/rust-installer/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1': checked out '755bc3db4ff795865ea31b5b4f38ac920d8acacb'
fatal: Not a git repository: /Users/Enrico/projects/redox/rust/src/rust-installer/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/test/rust-installer-v1/../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../.git/modules/rust/modules/src/rust-installer/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1/modules/test/rust-installer-v1
Failed to clone 'test/rust-installer-v1'. Retry scheduled
```

**Comment by jeromefroe** [comment]
I'm seeing the same results as well, running `git submodule update --remote` and then `make all` produces the errors that @dingensundso included above.

**Comment by nixpulvis** [comment]
+1 dingensundso

**Comment by chebykinn** [comment]
Same errors when building new kernel.

**Comment by nixpulvis** [comment]
I fixed this by using a specific toolchain.

```sh
rustup toolchain install nightly-2016-09-01-x86_64-apple-darwin
rustup default nightly-2016-09-01-x86_64-apple-darwin
...
```

**Comment by MarceColl** [comment]
+1 @nixpulvis, the error is gone

**Comment by zethra** [comment]
`rustc -V` rustc 1.14.0-nightly (9c31d76e9 2016-10-03)
`git rev-parse HEAD` `fdfa25858bae41516ab495a042d8cc8cf0d8c565`
`uname -a` Linux zethra-xps 4.7.5-1-ARCH #1 SMP PREEMPT Sat Sep 24 13:04:22 CEST 2016 x86_64 GNU/Linux

I'm having to same errors as @dingensundso

**Comment by jackpot51** [comment]
I updated to newest Rust, 10-03 nightly. Can everyone retry after doing a git pull and git submodule update --recursive?

**Comment by jdloft** [comment]
Seems to be working for me now.

**Comment by chebykinn** [comment]
What about new kernel?

**Comment by zethra** [comment]
That seemed to work for me, thanks.

**Comment by jeromefroe** [comment]
Same here, pulling the latest version of master and updating to the newest Rust nightly worked for me.

**Comment by EGhiorzi** [comment]
I can confirm the issue is fixed here as well.
