### ISSUE TITLE
Page fault at second login

### ISSUE THREAD

**Issue by io12** [redox-os/redox#712]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
1. Boot to shell
2. Run exit
3. Try to login again

**Expected behavior**: [describe the behavior you would expect the repro to yield.]
Login to the shell again.

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
A page fault is triggered.

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]

```
rustc 1.14.0-nightly (a3bc191b5 2016-10-10
git revision cc2e62e56d602e01e43f9c8380b31715bdc3592a
qemu-i386 version 2.7.0, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers
```

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]
---

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by jackpot51** [comment]
No longer applies to new kernel
