### ISSUE TITLE
preparing_the_build on MacOS Sierra 10.12

### ISSUE THREAD

**Issue by novski** [redox-os/redox#717]
**Reproduction**:
I followed this guide:
https://doc.redox-os.org/book/getting_started/preparing_the_build.html

with this command:
$ curl -sf https://raw.githubusercontent.com/redox-os/redox/master/bootstrap.sh -o bootstrap.sh && bash -e bootstrap.sh

**Expected behavior**: 
That i runns through without warnings

**Actual behavior**: 
werkstatt-7:Documents USER$ sh bootstrap.sh
|------------------------------------------|
|----- Welcome to the redox bootstrap -----|
|------------------------------------------|
Detected OSX!
Homebrew detected! Now updating...
Already up-to-date.
QEMU already installed!
Running Redox setup script...
Warning: homebrew/versions/gcc49-4.9.3 already installed
**Warning:** Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/nashenas88/homebrew-gcc_cross_compilers/i386-elf-binutils.rb:6:in `class:I386ElfBinutils'
Please report this to the nashenas88/gcc_cross_compilers tap!

**Warning:** Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/nashenas88/homebrew-gcc_cross_compilers/i386-elf-binutils.rb:6:in `class:I386ElfBinutils'
Please report this to the nashenas88/gcc_cross_compilers tap!

**Warning:** Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/nashenas88/homebrew-gcc_cross_compilers/i386-elf-binutils.rb:6:in `class:I386ElfBinutils'
Please report this to the nashenas88/gcc_cross_compilers tap!

**Warning:** Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/nashenas88/homebrew-gcc_cross_compilers/i386-elf-gcc.rb:7:in `class:I386ElfGcc'
Please report this to the nashenas88/gcc_cross_compilers tap!

**Warning:** Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/nashenas88/homebrew-gcc_cross_compilers/i386-elf-gcc.rb:7:in `class:I386ElfGcc'
Please report this to the nashenas88/gcc_cross_compilers tap!

**Warning:** Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/nashenas88/homebrew-gcc_cross_compilers/i386-elf-gcc.rb:7:in `class:I386ElfGcc'
Please report this to the nashenas88/gcc_cross_compilers tap!

Warning: nashenas88/gcc_cross_compilers/i386-elf-binutils-2.23 already installed
Warning: nashenas88/gcc_cross_compilers/i386-elf-gcc-4.9.3_1 already installed
Warning: nasm-2.12.02 already installed
Warning: pkg-config-0.29.1_2 already installed
==> brew cask install Caskroom/cask/osxfuse
Warning: A Cask for osxfuse is already installed.

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

---

Also to do:
$ brew install formulae.sha256 
does not work.

whats the problem here?

A build with:
make all
mkdir -p build/i386-unknown-redox/debug
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json --cfg redox -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=3 -Z no-landing-pads -A dead_code -C ar=i386-elf-ar -C linker=i386-elf-gcc -o build/i386-unknown-redox/debug/libcore.rlib rust/src/libcore/lib.rs
/bin/sh: rustc: command not found
make: **\* [build/i386-unknown-redox/debug/libcore.rlib] Error 127

does not work ether...

**Comment by bjorn3** [comment]
It seems like rust is not installed.

**Comment by novski** [comment]
does the bootstrap not install rust?

i see 
rustInstall() 
in the bootstrap.sh skript...

and i get
Your rust install looks good!
in the end...

**Comment by DomThePorcupine** [comment]
So I believe the issue here is that cargo and rustc are not in your `$PATH`.

@novski try running `source $HOME/.cargo/env` and then `make all`.

bootstrap tries to mitigate this by adding a line to your bashrc but this seems like this is not working.

**Comment by jackpot51** [comment]
This was probably fixed by installing rust - please reopen if it was not
