### ISSUE TITLE
`question_mark` attribute is now stable and `#![feature(question_mark)]` breaks build with rust 1.14

### ISSUE THREAD

**Issue by EGhiorzi** [redox-os/redox#718]
**Reproduction**: Update Rust to 1.14, then build Redox

**Expected behavior**: Build should go smooth

**Actual behavior**: Get this error:
```
error: this feature has been stable since 1.14.0. Attribute no longer needed
  --> rust/src/libcore/lib.rs:92:12
   |
92 | #![feature(question_mark)]
   |            ^^^^^^^^^^^^^
   |
note: lint level defined here
  --> rust/src/libcore/lib.rs:68:31
   |
68 | #![cfg_attr(not(stage0), deny(warnings))]
   |                               ^^^^^^^^
```
repeated for every occurrence of `#![feature(question_mark)]` in the codebase.

**Misc**: Looks like just removing the `question_mark` feature as suggested by cargo fixes everything. Should I do that? Also, what to do when the issue occours in an external crate (e.g. `rust`)?

**Comment by jackpot51** [comment]
This has now been fixed.
