### ISSUE TITLE
Support MacPorts in bootstrap.sh

### ISSUE THREAD

**Issue by Yoric** [redox-os/redox#720]
For the moment, on Mac, bootstrap.sh assumes that the user uses Brew. Ideally, it should also support MacPorts.

**Comment by Yoric** [comment]
Documenting the list of ports that I have installed so far:

- gmake
- qemu
- nasm
- osxfuse
- gcc49

**Comment by Yoric** [comment]
The above list seems to do the trick.

**Comment by DomThePorcupine** [comment]
@Yoric are you proposing one of us do this, or would you like to work on it?

**Comment by Yoric** [comment]
Well, I admit I hoped that someone else would do it :)

But if needed, I guess I can do it. It's a bit tricky to test, though.

**Comment by DomThePorcupine** [comment]
That's fine, I'll start working on it. When I am done maybe you can help test it.

**Comment by Yoric** [comment]
Apparently, with the new kernel, we also need `x86_64-elf-gcc` (probably instead of `i386-elf-gcc`).

**Comment by GlenDC** [comment]
@DomThePorcupine are you still working on this task?

Otherwise I might want take it over. As I also just updated the documentation regarding this (more or less) in the redox-os/redox/README.md file and redox-os/book.

@Yoric I think it could be useful to allow the user to JUST install the dependencies, and skip the entire boot part. Would it be fine if I provide a CL_OPT that allows you to skip the boot process?

**Comment by Yoric** [comment]
@GlenDC Yes, I personally haven't used bootstrap.sh at all, as it didn't work for MacPorts. I think it would be a good idea to let users skip it if dependencies are installed. Perhaps it should only print the list of dependencies?

**Comment by DomThePorcupine** [comment]
@GlenDC if you want go for it i won't get to it for a while

**Comment by GlenDC** [comment]
Ok today I was away all day, but tomorrow I'll work on a solution and reference this issue so you can give your input on my proposed PR regarding this issue.

**Comment by GlenDC** [comment]
@Yoric and @DomThePorcupine the PR mentioned yesterday has been opened, feel free to give your input at PR #753

**Comment by jackpot51** [comment]
Looks good to me, it would be good to have some OS X users with different setups test it.

**Comment by GlenDC** [comment]
I tested it both with `MacPorts` and `Homebrew`, but you're right @jackpot51 , probably better if some more MacOS people (with different setups) can confirm.

**Comment by meiyopeng** [comment]
@GlenDC 
1. Please fix this:
`install_macports_pkg "pkg-config"`  (line 98 in bootstrap.sh)
Package "**pkg-config**" is named "**pkgconfig**" in MacPorts.
So the right code is:
`install_macports_pkg "pkgconfig" "pkg-config"`

   reference: https://www.macports.org/ports.php?by=name&substr=pkgconfig

2. My host OS is macOS Sierra 10.12. I tried Homebrew first. It failed to
compile Redox. Then I tried MacPorts, but MacPorts failed to install
**x64-elf-gcc**. Is macOS Sierra officially supported?

**Comment by meiyopeng** [comment]
Google told me that gcc v4.9 has fatal compatibility issue with macOS. I think
Homebrew/MacPorts maintainers haven't updated the gcc49 brew/port file for macOS
Sierra yet. I know Redox is written in pure rust language. Why does Redox
project depend on gcc?

**Comment by GlenDC** [comment]
@meiyopeng I'll fix macports support in the bootstrap script in a second.

Could you please open another issue for your second point, as it is unrelated to this issue. Please also attach your build logs and any other information that could help others to help you out as part of this issue. Thank you.

> Why does Redox project depend on gcc?

If we check out the root [Makefile](https://github.com/redox-os/redox/blob/master/Makefile) as a starting point we can see that:

+ On all platforms _gcc_ (_elf-gcc_ on Darwin) is used as the `CROSSCC` compiler/linker for `./libstd/openlibm`;
+ For Darwin _elf-gcc_ is also used as the `-C linker` for all rust compilations that require a C Linker for some native code they might depend upon;

That's my understanding of it. Others such as @jackpot51 have probably a much better understanding of it than me.

**Comment by jackpot51** [comment]
It looks like this has been fixed.
