### ISSUE TITLE
So... Red Hat opened a patent on batching OS calls

### ISSUE THREAD

**Issue by bjadamson** [redox-os/redox#724]
So according to the last blog post, you implemented batched system calls.
https://www.redox-os.org/news/this-summer-in-redox-15/

Does this affect you?

https://www.reddit.com/r/systems/comments/58x28c/batch_execution_of_system_calls_in_an_operating/

**Comment by hauleth** [comment]
Prior art. That should be sent to whatever institution is responsible for that patent.

BTW software patents are still shit.

**Comment by ticki** [comment]
What the actual fuck. The idea is pretty damn simple.

Seriously, wtf

**Comment by ticki** [comment]
I'm still not sure if it actually applies to us, but it's far too general to be patented. This is just getting ridiculous.

gay space communism, gay space communism now.

**Comment by ticki** [comment]
I'm so fucking angry. I'm going to write this fucker a letter to tell him to be ashamed. Stealing ideas and pretending to have invented it is something that really upsets me.

**Comment by hauleth** [comment]
@ticki big companies like Google sometimes patent shit like this to avoid patent troll who would fuck with them not to fuck others. Let's hope that is the case.

**Comment by ticki** [comment]
@hauleth The fact that they _could_ require us to pay, or that we have to ask them to use basic stuff like this is so dumb.

Secondly, I really doubt that they'll give it to us for free. They have no reason to do so.

Shame on Google.

**Comment by juxtaposition-rocks** [comment]
fwiw if i am reading it right, the patent is actually owned by Red Hat, Inc., not Google (it's just on google.com because Google is providing a service for searching patents)

**Comment by leeoniya** [comment]
You can always file to have the patent invalidated on the basis of prior art, no? Newegg/EFF might help :) Also, to infringe the patent i believe you must infringe every claim; the abstract alone is insufficient. There may be enough wiggle room [for improvement?] to avoid issues here anyways.

**Comment by ticki** [comment]
@ambaxter 

You work at RedHat, do you think you can try to get this patent either public-domain'd or invalidated. The OSDev post (https://archive.fo/gPs4U) provides a strong case for theft of ideas (in particular, it uses the exact same terminology which seems highly unlikely to happen naturally).

> fwiw if i am reading it right, the patent is actually owned by Red Hat, Inc., not Google (it's just on google.com because Google is providing a service for searching patents)

**Comment by ambaxter** [comment]
I'll ask around and see what I can find out.

**Comment by ambaxter** [comment]
As per our patent promise: https://www.redhat.com/en/about/patent-promise

In short: Red Hat patents are primarily defensive. As long as Redox remains both Open Source and does not sue Red Hat, Red Hat will not initiate patent litigation against the Redox project.

**Comment by strangelittlemonkey** [comment]
I still don't trust them on this.

**Comment by StefanoD** [comment]
This is why I sad in the Redox forum, Apache 2 is more suitable:

http://en.swpat.org/wiki/Patent_clauses_in_software_licences#Apache_License_2.0

**Comment by StefanoD** [comment]
Well, to make an example:
TFS will probably work on Linux, too. If Red Hat is using TFS on Linux and TFS would have been licenced with Apache 2 ( @ticki ), then Red Hat couldn't sue you.

**Comment by bonzini** [comment]
This is the legalese: http://www.redhat.com/legal/patent_policy.html

**Comment by jackpot51** [comment]
Because the MIT and Apache 2 licenses are not listed explicitly as *Approved Licenses*, I recommend that we stay away from batched syscalls as described by the patent https://www.google.com/patents/US9038075.

As of now, we have not run into use cases that require them, and they would add implementation to the kernel, which is not desired.

**Comment by stavpup** [comment]
Doing what libreoffice did maybe the way to go
https://www.libreoffice.org/about-us/licenses/

"but we do ask that you license your code to us jointly under both the Mozilla Public License v2 and the GNU Lesser GPL v3+ licenses."

and
https://wiki.documentfoundation.org/Development/Re-Basing

**Comment by ambaxter** [comment]
Red Hat updated its patent promise today. It now includes MIT 

https://www.redhat.com/en/about/patent-promise
