### ISSUE TITLE
Cd into files

### ISSUE THREAD

**Issue by chebykinn** [redox-os/redox#725]
**Reproduction**: Try to cd to any regular file either on `redoxfs` or on `initfs`.
Like:
```
$ cd LICENSE
$ echo test > file
$ cat file
test
$ echo $PWD
file:root/LICENSE
```

**Expected behavior**:  `cd: not a directory: LICENSE`

**Actual behavior**: Can, in fact, `cd` to any file and create directories or files inside of it.

**Build information**:
rustc -V: `rustc 1.14.0-nightly (e0111758e 2016-10-17)`
git rev-parse HEAD: `104102777285c9e5573c0389ea8041fc57b380b8`
qemu: `version 2.7.0`
uname -a: `4.7.6-1-ARCH #1 SMP PREEMPT x86_64`

**Comment by jackpot51** [comment]
interesting, it should be easy to fix

**Comment by chebykinn** [comment]
I thought so, but why and where files are being created?

**Comment by bjorn3** [comment]
I call it a feature. It could be used for xattrs for example. But file managers should clearly show that there are files inside the file and allow you to go into the file 'dir'.

**Comment by chebykinn** [comment]
This problem is still persist, actually:

**Comment by chebykinn** [comment]
Oh, it's even simplier:
$ echo test > LICENSE/file
$ cat LICENSE/file
test

**Comment by jackpot51** [comment]
This is very interesting, I think I can fix it permanently

**Comment by jackpot51** [comment]
Fixed in newest redoxfs
