### ISSUE TITLE
Catch build errors in Travis

### ISSUE THREAD

**Issue by Yoric** [redox-os/redox#727]
So far, every time I have pulled `redox` or `kernel`, I have encountered build errors.

Travis should be able to catch these. Strike that: at this instant, Travis shows that the build is broken. We need a workflow that makes sure that we don't push broken builds.

**Comment by genodeftest** [comment]
Currently, travis doesn't work because they compile their kernels without FUSE support (see travis-ci/travis-ci#1100). This report contains some workarounds and a fix.

**Comment by jackpot51** [comment]
Working on this

**Comment by jackpot51** [comment]
Here is my new travis file: https://github.com/redox-os/redox/blob/master/.travis.yml

**Comment by genodeftest** [comment]
Oh, thanks. You probably can do better than me.

**Comment by jackpot51** [comment]
This is implemented now
