### ISSUE TITLE
Move kernel to a submodule

### ISSUE THREAD

**Issue by ticki** [redox-os/redox#731]
It really should be a submodule:

1. Having it as a submodule would allow people to design their own distributions: One could create a repo with all the submodules they want and then build from that. This is possible, but more annoying with the kernel in the main repository, since you have to fork this repository instead of making a new one.

2. This repository could hold issues, so every team member could get rights to close and label issues without concerns for lack of review etc..

3. Activity is easier to get right: When you see the number of lines written in the commit project, you would assume that it's Redox itself, but it isn't, it's really only the kernel. If this repo is unmodified for some time, Redox can still be very much alive. The stats give a wrong image of activity.

4. More seperatable commit history: You are able to distinguish between commits to the kernel and commits for updating submodules.

**Comment by jackpot51** [comment]
Done
