### ISSUE TITLE
Make pid type-safe

### ISSUE THREAD

**Issue by Yoric** [redox-os/redox#736]
For the moment, pids are represented as `usize`.

We would certainly save ourselves lots of pain by rather defining

```
pub struct Pid(pub usize);
```

somewhere central and using it wherever we currently use pid.

**Comment by NilSet** [comment]
We could get halfway there with a `type Pid = usize` and not need to do any destructuring to use it as a usize.

**Comment by joehillen** [comment]
@NilSet Using a type alias doesn't make it type-safe. You need the destructor so that you are explicit about when you intent to use a `Pid` as a `usize`, which should only be internal to `Pid` related functions.

**Comment by ticki** [comment]
[Newtype everything!](https://github.com/redox-os/ralloc/blob/skiplist/src/derive.rs)

**Comment by bjorn3** [comment]
Duplicate Sub impl including one which has mul as fn in the file you linked @ticki.

**Comment by Yoric** [comment]
Covered in https://github.com/redox-os/redox/pull/754.
