### ISSUE TITLE
Book 3.1: "Cloning the repository"

### ISSUE THREAD

**Issue by duesee** [redox-os/redox#743]
Executing `git clone https://github.com/redox-os/redox.git && cd redox && git submodule update init` does not work for me: `error: pathspec 'init' did not match any file(s) known to git.`

Executing `git submodule update --init --recursive` did the trick.

Next issue with `make all`:

```
error[E0523]: found two different crates with name `syscall` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
 --> programs/orbutils/src/terminal/main.rs:6:1
  |
6 | extern crate syscall;
  | ^^^^^^^^^^^^^^^^^^^^^

error: Could not compile `orbutils`.
```

In `programs/orbutils/src/terminal/main.rs` the external crate is `syscall`. Shouldn't it be `redox_syscall` as defined in `programs/orbutils/Cargo.toml`?

**Comment by genodeftest** [comment]
I had the same issue before. I chose using the bootstrap file for the first part of your issue.

The second one is gone after running `./bootstrap.sh -u` which expands to 
```
git pull upstream master
git submodule update --recursive --init
rustup update nightly
```

**Comment by duesee** [comment]
Now it works, thanks! But what was the error? I did `git submodule update --recursive --init` before and I am pretty sure I had a reletively recent nightly...

**Comment by genodeftest** [comment]
I don't know either. Some of the travis builds failed due to the same issue.

**Comment by duesee** [comment]
Okay, so I will close this issue. Maybe the book should mention the "Help! Redox won't compile" section in the Readme :-)
