### ISSUE TITLE
Archlinux dependencies

### ISSUE THREAD

**Issue by Yamakaky** [redox-os/redox#758]
- `qemu-system-i386` doesn't exist on x86_64 (https://wiki.archlinux.org/index.php/QEMU#Running_virtualized_system)
- you could simplify if to
```
deps=(git nasm fuse)
if [ "$1" == "qemu" ]; then
	deps+=(qemu)
fi
sudo pacman -S --needed $deps
```
We already know `pacman` is for installing packages, no need to say it.

**Comment by ids1024** [comment]
> qemu-system-i386 doesn't exist on x86_64

Actually, Redox has gone from i386 only to x86_64 only (arm may be added later), so all references to i386 should be changed.

**Comment by ids1024** [comment]
Oh, and `qemu-system-i386` is included in the `qemu-arch-extra` package, for what it's worth (as are various other architectures).

**Comment by jackpot51** [comment]
This should be taken care of. If it is not, please reopen
