### ISSUE TITLE
Virtualbox can not boot, got black screen

### ISSUE THREAD

**Issue by mzji** [redox-os/redox#766]
**Reproduction**:
This is the configuration of my RedoxOS test virtual machine:
![VM config](https://cloud.githubusercontent.com/assets/23279426/20788495/020333ee-b77f-11e6-9624-6887a87ceb19.PNG)
Host: Windows 10 Version 1607 (build 10.0.14393) x64 Education edition
Virtualbox version: 5.1.10

**Expected behavior**:
System boots up, after pressing F4 I will get a working desktop.

**Actual behavior**:
System boots up, scrolls a lot of hex numbers (un-gzipping?), then I got a black screen.
I tried F1 ~ F4, but none of these keys works. I tried ALL of them.
The disk/network indicator in the guest virtual machine window didn't blink, that means no disk/network activities.

**Build information**:
0.0.3 (Pre-released version)

**Comment by rushmorem** [comment]
Same here. I tried both `Other/Unknown` and `Other/Unknown (64-bit)`. My host is a 64bit Linux distro (NixOS).

**Comment by mzji** [comment]
@rushmorem A reddit user said he/she can boot up the VM, I followed that config but no luck.

**Comment by jackpot51** [comment]
Config looks correct - what CPU do you have?

**Comment by jackpot51** [comment]
Also, does it boot if you give it 1024 MB of memory?

**Comment by matuschewski-schulze** [comment]
@jackpot51 
I had the blank screen as well with 512MB memory.
I just switched to 4096MB and it works. Might also work with less of course :)

Thanks!

**Comment by matt-porter** [comment]
@jackpot51 I had this same issue; changing to 1024MB did fix it for me.

**Comment by jackpot51** [comment]
Usage is 520 MB after boot

**Comment by rushmorem** [comment]
Increasing the memory did work for me too but now I'm running into https://github.com/redox-os/redox/issues/767#issuecomment-264234299.

**Comment by mzji** [comment]
Increasing memory to 1024MB doesn't work for me.

**Comment by jackpot51** [comment]
For reference, here is my configuration:

![screenshot from 2016-12-01 18-59-12](https://cloud.githubusercontent.com/assets/7741236/20820410/46e5e136-b7f8-11e6-96db-3c87e4440a46.png)

**Comment by mzji** [comment]
@jackpot51 Great! I got it works!
Maybe a example VirtualBox VM config could be placed in the release note of the next pre-release version.
This config works for most RedoxOS users:
```
General:
OS: Other/Unknown (64-bit)

System:
Base Memory: 1024 (not less than 512)
Acceleration: VT-x/AMD-V, Nested Paging, PAE/NX, KVM Paravirtualization
Chipset: ICH9
Pointing Device: PS/2 Mouse
Extended Features: Enable I/O APIC

Display:
Video Memory: 32MB
Remote Desktop Server: Disabled
Video Capture: Disabled

Storage:
Controller: SATA
  SATA Port 0: [Optical Drive] with the LiveCD ISO file

Audio:
Host Driver: DirectSound (on Windows), PulseAudio (on Linux), ??? (on MacOS)
Controller: ICH AC97

Network:
Adapter 1: Intel PRO/1000 MT Desktop (NAT) (82540EM)

USB:
Disabled
```

**Comment by jackpot51** [comment]
@mzji What did you change?

**Comment by jackpot51** [comment]
I added that to the release notes - thanks

**Comment by mzji** [comment]
@jackpot51 Disabled the USB controller, Changed Boot Order, Increased Video Memory.

**Comment by mzji** [comment]
I thought this issue could be marked as "closed".

**Comment by Lewiscowles1986** [comment]
I knew when I reported it that it works with the specified hardware, but a kernel panic with no hardware?
