### ISSUE TITLE
Host OS kernel panic when running 0.0.3 in VirtualBox

### ISSUE THREAD

**Issue by msikma** [redox-os/redox#768]
**Reproduction**:

* Start VirtualBox 5.0.26 for Mac OS X 10.12.1.
* Create a new virtual machine set to Unknown Linux 64-bit, with 1024 MB RAM; [everything else default.](https://gist.github.com/msikma/b2d3ea03d49c68ef4e72a16285f36394)
* Start the virtual machine with the 0.0.3 iso as boot media.

**Expected behavior**:

Expect the ISO to boot into the Redox system.

**Actual behavior**:

[Host OS kernel panic](https://gist.github.com/msikma/ac688246fef0868a711778dc9a0cfa39), causing an immediate reboot.

**Build information**:

No build, since this was the 0.0.3 ISO.

* `uname -a`: `Darwin Vesuvius.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64`
* `sysctl -n machdep.cpu.brand_string`: `Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz`

**Comment by jackpot51** [comment]
What is `sysctl -n machdep.cpu.brand_string` ?

**Comment by msikma** [comment]
Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz. I'll add to the report.

**Comment by bjorn3** [comment]
Please file a issue at https://www.virtualbox.org/newticket.

**Comment by msikma** [comment]
Good call, since I see many others can run 0.0.3 in VirtualBox just fine it's probably something specific to my setup. I've made a ticket [here.](https://www.virtualbox.org/ticket/16256)

**Comment by jackpot51** [comment]
Could everyone still running into problems try the newest release? https://github.com/redox-os/redox/releases/tag/0.0.4

**Comment by FaraoneLele** [comment]
I still have this problem with 0.0.5

**Comment by jackpot51** [comment]
Please try the latest release: https://github.com/redox-os/redox/releases/tag/0.0.8

**Comment by msikma** [comment]
I'm happy to report that it now boots just fine using the same settings and VirtualBox version as I mentioned earlier.

<img width="647" alt="screen shot 2017-02-08 at 16 03 27" src="https://cloud.githubusercontent.com/assets/1507745/22742872/9f43ea16-ee18-11e6-95f8-e94f041dce32.png">

**Comment by jackpot51** [comment]
Awesome!
