### ISSUE TITLE
ISO 0.0.3 fails to boot in VirtualBox

### ISSUE THREAD

**Issue by mattico** [redox-os/redox#770]
`ahcid: failed to create disk scheme: file exists`

Host: Windows 10 x64 Build 14965
i5-4690K

Virtualbox: v5.1.10
![image](https://cloud.githubusercontent.com/assets/853158/20815552/f8c4bb4e-b7e3-11e6-9ba5-3449b2e5fede.png)

![image](https://cloud.githubusercontent.com/assets/853158/20815572/0c87c05e-b7e4-11e6-8d02-a75da2d89c5b.png)

**Comment by mattico** [comment]
Closing because the ahcid panic isn't an issue as mentioned in https://www.reddit.com/r/rust/comments/5fuwo2/first_redox_iso_release/danliww/

The real issue is covered in #764

**Comment by jackpot51** [comment]
Thanks for merging with #764!
