### ISSUE TITLE
[Virtualbox] Disk scheme creation error

### ISSUE THREAD

**Issue by Yamakaky** [redox-os/redox#772]
```
thread unnamed panicked at 'ahcid: failed to create disk scheme: File exists'
0: redoxfs: mounted filesystem disk:0 on file:
```
Virtualbox config: https://lut.im/hmaAK2qjUk/cLueTWPpGnI89Lwz.png

**Comment by rburlette** [comment]
I had this issue until I enabled Network as a boot device, and put it before the optical disk in the boot order:
<img width="413" alt="bootorder" src="https://cloud.githubusercontent.com/assets/1919183/20861036/04c8bb0e-b954-11e6-9fb7-44ec8ce999c2.png">

**Comment by jackpot51** [comment]
Could everyone still running into problems try the newest release? https://github.com/redox-os/redox/releases/tag/0.0.4

**Comment by Yamakaky** [comment]
It works!
