### ISSUE TITLE
VirtualBox+LiveISO on macOS Sierra: Only can boot with Null Audi Driver

### ISSUE THREAD

**Issue by johalun** [redox-os/redox#780]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Select CoreAudio audio driver.

**Expected behavior**: [describe the behavior you would expect the repro to yield.]
Boot to login prompt.

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
Freeze during boot in console mode

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
Using VirtualBox with liveiso

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]
Freezes seem rather random. Either at console or at GUI before login prompt is visible.
Running single core in VirtualBox seem to have the best change of successful boot. Even with Null Audio Driver and single core, it freezes sometimes during boot. Keep on resetting the VM and eventually boot is successful. 

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by muellermartin** [comment]
I'm using the settings in the release description and so far I can boot Redox and use some programs in Oribital even having CoreAudio selected as audio host driver.

Software versions:

- macOS: 10.12.1
- VirtualBox: 5.1.8 r111374 (Qt5.5.1)
- Redox livedisk.iso: 0.0.3

**Comment by jackpot51** [comment]
@yohanesu75 could you see if this release fixes the freezes? https://github.com/redox-os/redox/releases/tag/0.0.4

**Comment by jackpot51** [comment]
Please try the latest release: https://github.com/redox-os/redox/releases/tag/0.0.8
