### ISSUE TITLE
Snake Game crashes Redox

### ISSUE THREAD

**Issue by StefanoD** [redox-os/redox#781]
i've never tested this, but [this](http://www.golem.de/news/redox-os-wer-nicht-rustet-rostet-1612-124867.html) article says, if you loose a game in snacke, the game and the whole system crashes.

**Reproduction**: Start snake and loose the game

**Expected behavior**: Redox shouldn't crash.

**Actual behavior**: The game and the system crashes.

**Comment by xTibor** [comment]
I tested it and it's reproducible on my machine with the latest ISO (0.0.4). I don't even need to lose, just running the game crashes my system. The kernel produces no visible panics or errors to share.

The flappy bird game also misbehaves the same way.

* VirtualBox 5.0.24 on Kubuntu 16.04
* Intel i5-2410M
* Live ISO, games obtained with pkg

**Comment by cactorium** [comment]
Same happens with me, QEMU on ArchLinux, i5-3320M. It appears to be hitting some sort of infinite loop, just starting snake causes the CPU usage to max out and the system freezes. What would help with debugging?

**Comment by xTibor** [comment]
I did some debugging and these are the two places where it freezes for me: [game_start_prompt](https://github.com/redox-os/games/blob/9f6ac795c4099e304203d3930b1a18c539fd942f/src/snake/main.rs#L314-L321), [game_over](https://github.com/redox-os/games/blob/9f6ac795c4099e304203d3930b1a18c539fd942f/src/snake/main.rs#L330-L340)

In both cases the game tries to read the keyboard input from stdin. However I have no idea why it freezes the whole system.

**Comment by jackpot51** [comment]
This is due to the pit interrupt not triggering context switches. It should be easy to fix

**Comment by DaanHoogland** [comment]
@xTibor I have a hanging terminal when starting rusthello. Could that be the same issue? (it is only the terminal in which I started rusthello, which is hanging)

**Comment by xTibor** [comment]
I don't think it's the same issue, there seems to be something different going on. It only hangs on the GUI terminal, on the non-GUI terminal it works for me.

**Comment by DaanHoogland** [comment]
ok, for me the non-gui terminal hangs as well. Or rusthello in it at least
