### ISSUE TITLE
Cannot compile Redox on Ubuntu Host

### ISSUE THREAD

**Issue by sanjaybharadwaj** [redox-os/redox#782]
Hi,

I am building the Redox on a Ubuntu host 16.04LTS system, Although I tried the section "Can't compile Help", I still am not able to build the executable / OS.

I get the error "Can't find crate for `std` 
note: the `x86_64-unknown-none.json` target may not be installed."

I use the nightly build of rust 1.15.0 version using the rustup installation.

Does anyone faced a similar problem? please give me some directions.

Thanks and Best Regards,

**Comment by origel** [comment]
Are the network is OK? and try "sudo make" .

**Comment by sanjaybharadwaj** [comment]
Hi Origel, 

Yes the Network is OK and the whole operation is using Root.

Thank you, Sanjay
