### ISSUE TITLE
Streamline pull + rebuild

### ISSUE THREAD

**Issue by Yoric** [redox-os/redox#784]
So far, I haven't been able to come up with a reproducible workflow to pull and rebuild. All my attempts involve sequences of:

- `git pull --rebase --recurse-submodules`;
- `git clean -X -f -d`;
- `git submodule update --recursive --init`;
- `make clean`;
- `make all`;
- `cargo update` in some subdirectories;
- head-scratching;
- rinse and repeat.

I am sure that there must be a good way to handle this that does not involve spending 1h each time I pull. We should:

1. find such a workflow;
2. turn it into a single command `make pull`.

**Comment by jackpot51** [comment]
Thanks, I will see what can be done.

**Comment by jackpot51** [comment]
@Yoric does this work for you? https://github.com/redox-os/redox/commit/090168e0ea2956eaca5e8d2397f2a15415df4cf1

**Comment by NilSet** [comment]
Sometimes a `git submodule sync` is also needed

**Comment by jackpot51** [comment]
Added that here: https://github.com/redox-os/redox/commit/e8dc85169c7e5e1b9b6f1a129b8370f173389dce
