### ISSUE TITLE
Factor length function calls out of loop test clauses

### ISSUE THREAD

**Issue by yawaramin** [redox-os/redox#799]
**Reproduction**: see e.g. https://github.com/redox-os/redox/search?utf8=%E2%9C%93&q=while+len

**Expected behavior**: collection length calculations should be done once before iteration loops start, e.g.

```rust
let buf_len = buf.len();
while i < buf_len { ... }
```

**Actual behavior**: length calculations are repeated in every loop iteration, e.g.

```rust
while i < buf.len() { ... }
```

**Build information**: as of current `master`, i.e. https://github.com/redox-os/redox/commit/45ad8047a4e756c54e25d9094f45815acc452557

**Comment by bjorn3** [comment]
.len() is just a field accessor which will be inlined. No calculations are done. This should be no difference between your two snippets at assembly level if the length doesnt chamge during the lopp

**Comment by jackpot51** [comment]
To add to what @bjorn3 said, if the length does change in the loop, it is safer to use .len().

If it does not, it is easier to write and easier to read, as there is no extra line storing length into an arbitrary variable.
