### ISSUE TITLE
File Browser sqaushes itself when there are no real files

### ISSUE THREAD

**Issue by PeterJCLaw** [redox-os/redox#808]
**Reproduction**:
* Boot the 0.0.5 iso image
* Log in as either user
* Click the file browser from the task bar at the bottom
* Navigate to `/tmp`

**Expected behavior**:
The file browser should correctly show the empty directory.

**Actual behavior**:
The file browser looks weird:

![file-browser-tmp](https://cloud.githubusercontent.com/assets/336212/21595070/c801cb8a-d121-11e6-9e2d-157fa52d54fe.png)

Oddly, it remains functional and clicking the single entry for the parent works as expected. The window then resizes and correctly shows the parent folder.

**Comment by xTibor** [comment]
Fixed by redox-os/orbutils#14.
