### ISSUE TITLE
Mousing over the File Browser is slow when there are lots of files

### ISSUE THREAD

**Issue by PeterJCLaw** [redox-os/redox#809]
**Reproduction**:
* Boot the 0.0.5 iso image
* Log in as either user
* Click the file browser from the task bar at the bottom
* Navigate to `/` and experiment to get a feel for how quickly moving the mouse up and down over the window works
* Now navigate to `/bin` which has _many_ files and move the mouse up and down over the file browser
 * This is noticeably slower than when the browser only shows a small number of items
 * It is also slower than moving the mouse up and down over areas of the screen where the file browser is not shown (i.e: being just off to one side)

**Expected behavior**:
The number of items should not result in a noticeable difference.

**Actual behavior**:
Moving the mouse over the file browser when it has many items makes the mouse cursor lag.

**Comment by jackpot51** [comment]
This issue will be fixed when https://github.com/redox-os/orbutils/issues/16 is merged

**Comment by jackpot51** [comment]
This should be fixed in master
