### ISSUE TITLE
filesystem.bin will not compile on OS X

### ISSUE THREAD

**Issue by gjf2a** [redox-os/redox#812]
**Reproduction**: run make all command in the redox directory after downloading everything with bootstrap.sh

**Expected behavior**: the compilation finishes without errors.

**Actual behavior**: The compilation fails with the following error message:

[gabriel on Gabriels-MacBook-Pro-2]:/Users/gabriel/redox
<?> make all
#filesystem/bin/shutdown filesystem/bin/test
sudo umount build/filesystem/
Password:
umount: build/filesystem/: not currently mounted
make: [build/filesystem.bin] Error 1 (ignored)
rm -rf build/filesystem.bin build/filesystem/
dd if=/dev/zero of=build/filesystem.bin bs=1048576 count=64
64+0 records in
64+0 records out
67108864 bytes transferred in 0.040793 secs (1645100069 bytes/sec)
cargo run --manifest-path schemes/redoxfs/Cargo.toml --release --bin redoxfs-mkfs build/filesystem.bin
    Finished release [optimized] target(s) in 0.0 secs
     Running `schemes/redoxfs/target/release/redoxfs-mkfs build/filesystem.bin`
redoxfs: created filesystem on build/filesystem.bin, size 64 MB
mkdir -p build/filesystem/
cargo build --manifest-path schemes/redoxfs/Cargo.toml --release --bin redoxfs
    Finished release [optimized] target(s) in 0.0 secs
schemes/redoxfs/target/release/redoxfs build/filesystem.bin build/filesystem/
redoxfs: opened filesystem build/filesystem.bin
sleep 2
pgrep redoxfs
95719
cp -RL filesystem/* build/filesystem/
chown -R 0:0 build/filesystem
chown -R 1000:1000 build/filesystem/home/user
chmod -R uog+rX build/filesystem
chmod -R u+w build/filesystem
chmod -R og-w build/filesystem
chmod -R 755 build/filesystem/bin
chmod -R u+rwX build/filesystem/root
chmod -R og-rwx build/filesystem/root
chmod -R u+rwX build/filesystem/home/user
chmod -R og-rwx build/filesystem/home/user
chmod +s build/filesystem/bin/passwd
chmod +s build/filesystem/bin/su
chmod +s build/filesystem/bin/sudo
mkdir build/filesystem/tmp
chmod 1777 build/filesystem/tmp
sync
sudo umount build/filesystem/
rm -rf build/filesystem/
nasm -f bin -o build/harddrive.bin -D ARCH_x86_64 -ibootloader/x86_64/ bootloader/x86_64/harddrive.asm
startup-x86_64.asm:125: warning: numeric constant 0xFFFFFF000009F000 does not fit in 32 bits
bootsector.asm:184: error: integer supplied to a DQ instruction
startup-x86_64.asm:2: error: integer supplied to a DQ instruction
startup-x86_64.asm:3: error: integer supplied to a DQ instruction
startup-x86_64.asm:4: error: integer supplied to a DQ instruction
startup-x86_64.asm:5: error: integer supplied to a DQ instruction
startup-x86_64.asm:6: error: integer supplied to a DQ instruction
startup-x86_64.asm:7: error: integer supplied to a DQ instruction
unreal.asm:44: error: integer supplied to a DQ instruction
startup-x86_64.asm:118: error: symbol `rax' undefined
startup-x86_64.asm:119: error: symbol `rax' undefined
startup-x86_64.asm:120: error: symbol `rax' undefined
startup-x86_64.asm:121: error: symbol `rax' undefined
startup-x86_64.asm:122: error: symbol `rax' undefined
startup-x86_64.asm:123: error: symbol `rax' undefined
startup-x86_64.asm:125: error: symbol `rsp' undefined
startup-x86_64.asm:128: error: symbol `rax' undefined
startup-x86_64.asm:129: error: symbol `rax' undefined
startup-x86_64.asm:132: error: symbol `rax' undefined
startup-x86_64.asm:133: error: symbol `rax' undefined
startup-x86_64.asm:134: error: symbol `rax' undefined
startup-x86_64.asm:135: error: symbol `rax' undefined
startup-x86_64.asm:136: error: symbol `rax' undefined
startup-x86_64.asm:137: error: symbol `rax' undefined
startup-x86_64.asm:139: error: symbol `rdi' undefined
startup-x86_64.asm:140: error: symbol `rsi' undefined
startup-x86_64.asm:141: error: symbol `rdx' undefined
startup-x86_64.asm:142: error: symbol `rcx' undefined
startup-x86_64.asm:144: error: symbol `rsp' undefined
startup-x86_64.asm:146: error: symbol `rax' undefined
startup-x86_64.asm:147: error: operation size not specified
startup-x86_64.asm:148: error: symbol `rax' undefined
startup-x86_64.asm:152: error: integer supplied to a DQ instruction
startup-x86_64.asm:156: error: integer supplied to a DQ instruction
bootloader/x86_64/harddrive.asm:21: error: phase error detected at end of assembly.
make: *** [build/harddrive.bin] Error 

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
rustc -V
rustc 1.16.0-nightly (4ecc85beb 2016-12-28)

uname -a
Darwin Gabriels-MacBook-Pro-2.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Aug 29 21:14:16 PDT 2016; root:xnu-2782.50.6~1/RELEASE_X86_64 x86_64

**Misc**: I've followed the directions at https://doc.redox-os.org/book/getting_started/preparing_the_build.html with no trouble up to here. I cloned the git repository, and I'm installing dependencies using homebrew. I had to install pkg-config as referenced in Issue 619 (https://github.com/redox-os/redox/issues/619) to get as far as I did.

Thanks for any help you can offer.

------

**Comment by DomThePorcupine** [comment]
@jackpot51 i think the change to support macports has broken homebrew in bootstrap. On line 129 of bootstrap it is clearly _trying_ to install pkg-config but @gjf2a had to do it manually. Do we have a new list of homebrew packages necessary for compiling on OSX? If we do then we need to stop using the `install_macos_pkg()` function and simply test for and then install the packages like we do with everything else directly in the `osx_homebrew()` function.

**Comment by jackpot51** [comment]
@DomThePorcupine nasm needs to be installed to fix this issue.

**Comment by jackpot51** [comment]
@gjf2a do you have `brew install nasm` ?

**Comment by DomThePorcupine** [comment]
Yes on line 128 it should be installing nasm

**Comment by jackpot51** [comment]
This issue only happens if the system default nasm is being used. Perhaps do a `which nasm`?

**Comment by gjf2a** [comment]
nasm was already installed, but I did a brew install asm anyway which upgraded it to 2.12.02. That fixed this problem, and make all completes without any further errors. Thanks for your prompt feedback! I really appreciate it!

**Comment by jackpot51** [comment]
Brew is complicated - without having a clean system I am not sure exactly what packages must be installed and in what order.

Perhaps someone can clarify a working set of packages? Which x86_64-elf-gcc package did you install @gjf2a ?

**Comment by gjf2a** [comment]
Here's a list of all my brew package versions:
x64-elf-gcc: stable 4.9.3
nasm: stable 2.12.02
make: I'm not using a homebrew package. It's GNU Make 3.81.
qemu: stable 2.7.0
gcc49: stable 4.9.3
pkg-config: stable 0.29.1

**Comment by jackpot51** [comment]
Thanks. Where did x64-elf-gcc come from? Which source was tapped?

**Comment by gjf2a** [comment]
The tapped source is:

 https://github.com/glendc/homebrew-gcc_cross_compilers/blob/master/x64-elf-gcc.rb

**Comment by DomThePorcupine** [comment]
@jackpot51 I'm starting work on updating the bootstrap and I was thinking that maybe redox should fork the brew tap so we do not rely on other people's forks being maintained. This would avoid all the issues we've had of new OSX versions breaking the taps and thus bootstrap/compiling on OSX. What do you think?

**Comment by jackpot51** [comment]
@DomThePorcupine That is a good idea
