### ISSUE TITLE
Mice and Keyboard are not working

### ISSUE THREAD

**Issue by StefanoD** [redox-os/redox#818]
**Reproduction**:
- Use Virtual Machine Manager with QEMU/KVM.
- Mouse setup: PS 2
- Keyboard setup: PS 2
- Boot Redox 0.0.6
- Select arbitrary resolution
- You'll enter into login prompt 
- Click into Redox windows for focus
- You won't be able to move the mouse cursor or type something into the login prompt

**Build information**:
Virtual Machine Manager 1.4.0 with Fedora 25
Kernel version: 4.8.15-300.fc25.x86_64

**Comment by PureTryOut** [comment]
Can reproduce on Qemu/KVM (Qemu 2.8.0), kernel 4.9.0 on Gentoo.

**Comment by jackpot51** [comment]
Please try the latest release: https://github.com/redox-os/redox/releases/tag/0.0.8

**Comment by StefanoD** [comment]
Works.
