### ISSUE TITLE
make all Could not compile 'x86'

### ISSUE THREAD

**Issue by E-R-C** [redox-os/redox#828]
**Reproduction**: I followed the quick setup guide up to the "make all" command. 

**Expected behavior**: Compile without errors

**Actual behavior**: It says Could not Compile 'x86' and I receive an output of the following [here]( http://pastebin.com/24KsDxgm) which is pasted on pastebin because the output is quite large. 

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
rustc -V: rustc 1.16.0-nightly (ff591b6dc 2017-01-15)
git rev-parse HEAD: 58f02984ca6ec0821906eb53f5edc9756b508f7d
qemu-i386 -version: qemu-i386 version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.6), Copyright (c) 2003-2008 Fabrice Bellard
uname: Linux 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Other notes**
I have followed the Redox Won't Compile things to do as well and have reproduced the same error.

**Comment by jackpot51** [comment]
You will have to backtrack your rustc using `rustup override set nightly-2017-01-14`

This issue will need to be fixed: https://github.com/rust-lang/rust/issues/39083

**Comment by jackpot51** [comment]
You should be able to use latest nightly - x86 crate has been fixed
