### ISSUE TITLE
Redox hard-codes `errno` as 0, which means "no error".

### ISSUE THREAD

**Issue by briansmith** [redox-os/redox#830]
```rust
pub fn errno() -> i32 {
    0
}
```

0 means "no error," so always returning 0 seems unfortunate and potentially dangerous. I suggest you hard-code `EIO` instead of `0` instead. It's only valid to check errno if a function failed, and `EIO` is a reasonable, if vague, value for `errno` when a function fails.

**Comment by jackpot51** [comment]
I think we can reference the "real" errno now that we are linking with newlib
