### ISSUE TITLE
`getpid` & co don't need syscalls

### ISSUE THREAD

**Issue by Yoric** [redox-os/redox#840]
We could introduce a scheme `proc:` and read `proc:pid`, `proc:ppid`, `proc:uid`, ... instead of syscalls `SYS_GETPID`, `SYS_GETUID`, ...

It's trading a set of syscalls for an in-kernel scheme, so we need to decide whether this is useful.

**Comment by jackpot51** [comment]
We could, but it would probably have to be done in-kernel and would likely increase the LoC

**Comment by Yoric** [comment]
Fair enough.

**Comment by Yoric** [comment]
As a side-note, we could also collapse `getpid`, `getppid`, `getuid`, ... into a single call `SYS_GETPROCESSINFO`.

**Comment by jackpot51** [comment]
@yoric - yes, that is possible
