### ISSUE TITLE
Does not boot anymore after a git pull

### ISSUE THREAD

**Issue by aurelien-git** [redox-os/redox#848]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]

> $ git pull
> remote: Counting objects: 30, done.
> remote: Compressing objects: 100% (13/13), done.
> remote: Total 30 (delta 16), reused 10 (delta 10), pack-reused 7
> Unpacking objects: 100% (30/30), done.
> From https://github.com/redox-os/redox
>    52d640b..11bc60d  master     -> upstream/master
>  * [new branch]      arc        -> upstream/arc
> Fetching submodule drivers
> From https://github.com/redox-os/drivers
>    5b223c0..63dd228  master     -> origin/master
> Fetching submodule programs/netutils
> From https://github.com/redox-os/netutils
>    852d860..09214cc  master     -> origin/master
> Fetching submodule programs/orbutils
> From https://github.com/redox-os/orbutils
>  * [new branch]      arc        -> origin/arc
>    297f39a..6d6690d  master     -> origin/master
> Fetching submodule schemes/orbital
> From https://github.com/redox-os/orbital
>  * [new branch]      arc        -> origin/arc
>    c70e11f..0bcc947  master     -> origin/master
> Updating 52d640b..11bc60d
> Fast-forward
>  Cargo.toml           | 1 +
>  drivers              | 2 +-
>  initfs/etc/pcid.toml | 6 ++++++
>  kernel               | 2 +-
>  mk/initfs.mk         | 1 +
>  mk/qemu.mk           | 2 +-
>  programs/coreutils   | 2 +-
>  programs/netutils    | 2 +-
>  programs/orbutils    | 2 +-
>  schemes/orbital      | 2 +-
>  schemes/redoxfs      | 2 +-
>  11 files changed, 16 insertions(+), 8 deletions(-)
> aurelien@icebreaker:~/redox/redox$ git pull
> 
> $ make qemu kvm=no vga=no display=no
> make: *** No rule to make target 'initfs/bin/nvmed', needed by 'build/userspace/initfs.rs'.  Stop.

**Expected behavior**: [describe the behavior you would expect the repro to yield.]

Just to run as it should

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].

> $ make qemu kvm=no vga=no display=no
> make: *** No rule to make target 'initfs/bin/nvmed', needed by 'build/userspace/initfs.rs'.  Stop.

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]

> $ rustc -V
> rustc 1.17.0-nightly (62eb6056d 2017-02-15)

> $ git rev-parse HEAD
> 11bc60d3ca2cd9214a0b6e03e1727251f297f15f

> $ qemu-i386 -version
> qemu-i386 version 2.8.0
> Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers

> uname -a
> Linux icebreaker 4.4.50-1-lts #1 SMP Sat Feb 18 17:14:48 CET 2017 x86_64 GNU/Linux

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

Stop ... impossible to run as is

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by bjorn3** [comment]
Please put program output in code blocks for clarity. (3x backtick around it)

**Comment by aurelien-git** [comment]
done

**Comment by jackpot51** [comment]
Can you `git submodule update --init --recursive`, then `make clean` and `make update` ?

**Comment by aurelien-git** [comment]
too late ... I have rm -rf and git clone .

**Comment by aurelien-git** [comment]
for information, Yes your tips solved the trouble.
I have reproduce the error and it works like a charm.
thanks once again. @jackpot51
