### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by adrianN** [redox-os/redox#850]
**Reproduction**: Follow the instructions in the book to build redox

**Expected behavior**: Redox is built.

**Actual behavior**: Make fails. See https://gist.github.com/adrianN/2b1c09d83bae4b88acf82a25f8856a0f

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
MacBook:redox aneumann$ rustc -V
rustc 1.17.0-nightly (306035c21 2017-02-18)
MacBook:redox aneumann$ git rev-parse HEAD
11bc60d3ca2cd9214a0b6e03e1727251f297f15f
MacBook:redox aneumann$ uname -a
Darwin MacBook 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64

**Comment by bjorn3** [comment]
`x86_64-elf-gcc: command not found`

**Comment by adrianN** [comment]
So it looks like the bootstrap script quit after trying to install git 

~~~~~
Installing missing packages...
git already exists at /usr/bin/git, no need to install git...
MacBook:~ aneumann$
~~~~~

and didn't install all the other packages

**Comment by bjorn3** [comment]
brew exits with non zero error code when program is already installed. there is a redox issue for this.

**Comment by jackpot51** [comment]
If this is fixed by your PR @adrianN, can you close?
