### ISSUE TITLE
Empty history after a pkill and boot from make qemu

### ISSUE THREAD

**Issue by aurelien-git** [redox-os/redox#853]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Start with `make qemu kvm=no vga=no display=no` then connect with user and load `history` command
**Expected behavior**: [describe the behavior you would expect the repro to yield.]
have a list of history load during other use
**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
no history
**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
> rustc 1.17.0-nightly (62eb6056d 2017-02-15)
> f143a66845f5be300cd4c58dd89a60473461e7f5
> qemu-i386 version 2.8.0
> Linux icebreaker 4.4.50-1-lts #1 SMP Sat Feb 18 17:14:48 CET 2017 x86_64 GNU/Linux
**Blocking/related**: [issues or PRs blocking or being related to this issue.]
no history
**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by jackpot51** [comment]
`make qemu` completely wipes the filesystem. `make qemu_no_build` will keep it intact
