### ISSUE TITLE
On VirtualBox (Mac) I can't open the Browser

### ISSUE THREAD

**Issue by FaraoneLele** [redox-os/redox#860]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Press the browser's icon
**Expected behavior**: [describe the behavior you would expect the repro to yield.]
the browser opens
**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
the browser crashes
**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
Mac OS 10.12, VirtualBox, Redox OS 0.1.0
**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by polymetric1** [comment]
you didn't do `rustc -V` or `git rev-parse HEAD`

**Comment by jackpot51** [comment]
@FaraoneLele You must use the Intel ethernet card in VirtualBox

**Comment by FaraoneLele** [comment]
Ok thanks. This bug was resolved with 0.1.2.
