### ISSUE TITLE
0.1.1 source tarball & zip don't seem to contain any source code

### ISSUE THREAD

**Issue by complaining-user-engine** [redox-os/redox#864]
**Reproduction**: 

Download redox-0.1.1.tar.gz or the zip under the source code section of the release page and note the unusually small filesize and lack of any rust source code in any of the directories

**Expected behavior**: 

source archive should correspond to the binaries found on iso

**Misc**:

Is a result of your packaging method being unable to handle git submodules.

**Comment by polymetric1** [comment]
This isn't our packaging method, this is entirely GitHub's fault. The site generates them automatically and doesn't allow you to replace them. AFAIK there's nothing we can do about it.

**Comment by russmack** [comment]
Closed?

**Comment by jackpot51** [comment]
The release happened when S3 was down - a new release will be done soon
