### ISSUE TITLE
Suggestion: Factor out a Unikernel Framework out of Redox

### ISSUE THREAD

**Issue by yazaddaruvala** [redox-os/redox#874]
Saw some [interest in Rust unikernels](https://www.reddit.com/r/rust/comments/5z8dd0/redoxos_microkernel_os_written_in_rust_lunduke/dexnv5j/), and as a result felt it might be useful to start a conversation about it.

Similar projects:
- https://mirage.io/
- http://www.includeos.org/
- https://github.com/rumpkernel/rumprun (maybe?)

Reasons to built yet another unikernel framework:
- All the benefits associated with Rust
- None of the other unikernel projects have (to my knowledge) been used to build a microkernel at the scale of Redox
- The Redox ecosystem is already pretty organized and split into separate projects. I imagine this may bring in one more avenue for abstraction and project organization. i.e. The unikernel framework goes into its own package, and the Redox specific parts stay in Redox code.

**Comment by jackpot51** [comment]
This is not possible due to the way drivers have to be written
