### ISSUE TITLE
rustc no longer supports $(ARCH)-unknown-none as known target

### ISSUE THREAD

**Issue by Dragonrun1** [redox-os/redox#877]
Among other issues I've been noticing when manually running some of the build commands to figure needed changes to make stuff build under MS Windows I've ran into this one which I sure isn't just a Windows only issue. For example when trying to run:
`bash
 CARGO_INCREMENTAL=1 cargo rustc --manifest-path rust/src/libcollections/Carg
o.toml --target x86_64-unknown-none --release --verbose -- -C soft-float -o bui
ld/kernel/libcollections.rlib
`
I get
`bash
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --target x86_64-unknown-none` (exit code: 101)
--- stderr
error: Error loading target specification: Could not find specification for target "x86_64-unknown-none"
  |
  = help: Use `--print target-list` for a list of built-in targets
`
and when I run:
`bash
$ rustc --print target-list
`
It no longer list any `-unknown-none` targets. I'm not sure when rust made the change but the KTARGET of the mk/config.mk file needs to be updated. My suggestion would be something like `$(ARCH)-unknown-linux-gnu`. I didn't check but I'm pretty sure those are what the old `-none` targets have been renamed too and at least in some limited testing seem to work.  I noticed this as well in the build history which shows the error I get without the `--verbose` option added.
https://travis-ci.org/redox-os/redox/builds/211931652

**Comment by jackpot51** [comment]
Now this issue appears on Linux too.

**Comment by ocschwar** [comment]
MacOS, same problem.

**Comment by jackpot51** [comment]
Which can now be ld! Awesome!

**Comment by jackpot51** [comment]
This should be fixed now.
