### ISSUE TITLE
dea4ec0 currently failing to compile vboxd

### ISSUE THREAD

**Issue by DoublePlusGood23** [redox-os/redox#881]
**Reproduction**: checkout the current HEAD (dea4ec0) and run `make all`

**Expected behavior**: `make all` to build correctly,

**Actual behavior**: `make all` fails to compile with error: 

`make: *** No rule to make target 'initfs/bin/vboxd', needed by 'build/kernel/initfs.tag'.  Stop.`

**Program Versions:**

git branch: `dea4ec095320c6b6c1199b85528f9cce392e661a`

rustc: `rustc 1.17.0-nightly (6eb9960d3 2017-03-19)`

qemu: `QEMU emulator version 2.8.0(Debian 1:2.8+dfsg-3ubuntu2)`

uname: `Linux yayoi 4.10.0-13-generic #15-Ubuntu SMP Thu Mar 9 20:28:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

lsb_release -r: `Release:	17.04`

**Misc**: Reverting to f37f4bb fixes the error and compiles fine; dea4ec0 also appears to be failing on Travis.

**Comment by jackpot51** [comment]
This should be fixed with master
