### ISSUE TITLE
Compilation failure with ahcid driver

### ISSUE THREAD

**Issue by ThomasPassmore** [redox-os/redox#883]
Hi, I'm trying to compile Redox by following [this](https://github.com/redox-os/redox#cloning-building-running) page.

[This](https://github.com/redox-os/drivers/compare/060934a77df3850693778800deadcb5be1c3fb3b...beef16096fb37b31b171f0f44b596c4a6019117d#diff-d44f26e07d0c9d5fb8f19f4ad7679faa) commit introduced a compilation error in the ahcid driver on my machine, adding `use std::thread;` to the use statements at the top of  drivers/ahcid/src/ahci/hba.rs
 solves this issue for me.

I apologize I can't make this isn't a pull request, I'm not familiar enough with the process to do this.

**Comment by jackpot51** [comment]
This issue has been fixed
