### ISSUE TITLE
Compile redox OS

### ISSUE THREAD

**Issue by mauriceAlthoff** [redox-os/redox#884]
hey, I just downloaded and currently try to compile redox, bud the compilation stops compiling std with the error:

error: this feature has been stable since 1.17.0. Attribute no longer needed
   --> rust/src/libstd/lib.rs:286:12
    |
286 | #![feature(pub_restricted)]
    |            ^^^^^^^^^^^^^^
    |
    = note: #[deny(stable_features)] implied by #[deny(warnings)]
note: lint level defined here
   --> rust/src/libstd/lib.rs:229:9
    |
229 | #![deny(warnings)]
    |         ^^^^^^^^

error: aborting due to previous error

error: Could not compile `std`.

I followed the redox os book description for manual setup and I use the nightly build rust.

**Comment by NickeZ** [comment]
I had some issue with todays nightly. Find another nightly on http://rusty-dash.com/nightlies and install it.

In the redox repository, run:
```
$ rustup toolchain install nightly-YYYY-MM-DD
$ rustup override set nightly-YYYY-MM-DD
```

I'm currently trying to find a version that compiles also..

**Comment by jackpot51** [comment]
I will update the Rust repo so the latest nightly can compile.

**Comment by NickeZ** [comment]
@jackpot51 will that fix the issue with libcore as well?

```
$ make
mkdir -p build/kernel
RUSTC="./krustc.sh" RUSTDOC="./krustdoc.sh" CARGO_INCREMENTAL=1 cargo rustc --manifest-path rust/src/libcollections/Cargo.toml --target x86_64-unknown-none --release -- -C soft-float -o build/kernel/libcollections.rlib
   Compiling core v0.0.0 (file:///home/niklas/src/redoxos/redox/rust/src/libcore)
error: requires `drop_in_place` lang_item
error: Could not compile `core`.
```

**Comment by jackpot51** [comment]
yes

**Comment by NickeZ** [comment]
For future reference. This could work if redox/rust gets out of synch:

```
rustup install nightly-$(GIT_DIR=rust/.git git log -1 --format="%ci" | awk '{print $1}')
rustup override set nightly-$(GIT_DIR=rust/.git git log -1 --format="%ci" | awk '{print $1}')
```

It didn't for me though:

```
   Compiling ps2d v0.1.0 (file:///home/niklas/src/redoxos/redox/drivers/ps2d)
warning: ignoring --out-dir flag due to -o flag.
error[E0560]: struct `orbclient::MouseEvent` has no field named `left_button`
   --> drivers/ps2d/src/main.rs:113:25
    |
113 |                         left_button: flags.contains(LEFT_BUTTON),
    |                         ^^^^^^^^^^^^ `orbclient::MouseEvent` does not have this field
error[E0560]: struct `orbclient::MouseEvent` has no field named `middle_button`
   --> drivers/ps2d/src/main.rs:114:25
    |
114 |                         middle_button: flags.contains(MIDDLE_BUTTON),
    |                         ^^^^^^^^^^^^^^ `orbclient::MouseEvent` does not have this field
error[E0560]: struct `orbclient::MouseEvent` has no field named `right_button`
   --> drivers/ps2d/src/main.rs:115:25
    |
115 |                         right_button: flags.contains(RIGHT_BUTTON)
    |                         ^^^^^^^^^^^^^ `orbclient::MouseEvent` does not have this field
error: aborting due to 3 previous errors
error: Could not compile `ps2d`.
```

**Comment by jackpot51** [comment]
did you run `make update`?

**Comment by NickeZ** [comment]
No, i did `git submodule update --recursive --init` like it says in the readme. Does it need to be updated?

Anyway, I now it fails at ahcid https://github.com/redox-os/redox/issues/883

**Comment by scottc** [comment]
I had rust `nightly-2017-03-22` installed, downgrading to `nightly-2017-03-21` aka `1.17.0-nightly (134c4a0f0 2017-03-20)` resolved this issue for me.

`make all` compiles without errors, after you pulling the fix for #883 in addition to downgrading.

**Comment by NickeZ** [comment]
I got a new error after upgrading to latest nightly:

```
error: this feature has been stable since 1.17.0. Attribute no longer needed
   --> rust/src/libstd/lib.rs:286:12
    |
286 | #![feature(pub_restricted)]
    |            ^^^^^^^^^^^^^^
    |
    = note: #[deny(stable_features)] implied by #[deny(warnings)]
note: lint level defined here
   --> rust/src/libstd/lib.rs:229:9
    |
229 | #![deny(warnings)]
    |         ^^^^^^^^
error: aborting due to previous error
error: Could not compile `std`.

```

**Comment by NickeZ** [comment]
Maybe redox needs something like `mach` in servo. I've never had any issues compiling servo with simply `git pull && /mach build --release`.

**Comment by NickeZ** [comment]
One possible improvement would be to fix the nightly version in travis and then update the rust submodule and the travis file in sync. Would that be feasible?

**Comment by jackpot51** [comment]
It is probably possible to improve the build process stability.

**Comment by NickeZ** [comment]
The easy solution right now seems to be to pick the latest build that worked on jenkins and then override to the same rustc version that jenkins used.

```
git checkout 9abf484
git submodule update --init --recursive
rustup install nightly-2017-03-21
rustup override set nightly-2017-03-21
make clean
make
```

**Comment by mauriceAlthoff** [comment]
solved it for me, thanks

**Comment by jackpot51** [comment]
Working on latest nightly support

**Comment by jackpot51** [comment]
This should be fixed now
