### ISSUE TITLE
New redox commit doesn't compile

### ISSUE THREAD

**Issue by jsalzbergedu** [redox-os/redox#891]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.] On arch linux (Antergos) x86_64, with rust version `rustc 1.17.0-nightly (134c4a0f0 2017-03-20)`, using the manual setup / the instructions in `Help! Redox won't compile` (including `$ rustup set override nightly`) results in redox not compiling when running `$ make all`

**Expected behavior**: [describe the behavior you would expect the repro to yield.] Redox compiling successfully.

**Actual behavior**: [describe the actual behavior, which is presented through the repro.]. Redox does not compile with the error:
error: `pub(restricted)` syntax is experimental (see issue #32409)
   --> rust/src/libstd/thread/mod.rs:748:9
    |
748 |     pub(crate) fn new(name: Option<String>) -> Thread {
    |         ^^^^^
    |
    = help: add #![feature(pub_restricted)] to the crate attributes to enable

error: `pub(restricted)` syntax is experimental (see issue #32409)
    --> rust/src/libstd/collections/hash/map.rs:1372:9
     |
1372 |     pub(super) inner: table::IntoIter<K, V>,
     |         ^^^^^
     |
     = help: add #![feature(pub_restricted)] to the crate attributes to enable

error: `pub(restricted)` syntax is experimental (see issue #32409)
    --> rust/src/libstd/collections/hash/map.rs:1424:9
     |
1424 |     pub(super) inner: table::Drain<'a, K, V>,
     |         ^^^^^
     |
     = help: add #![feature(pub_restricted)] to the crate attributes to enable

error: aborting due to 3 previous errors

error: Could not compile `std`.

However if I rollback using git checkout to the commit `007603a53c81092d5ca5bcb5d4155e64ce97b94c`, `$ make all` and `$make qemu` work fine.

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.] `rustc -V`: rustc 1.17.0-nightly (134c4a0f0 2017-03-20), `git rev-parse HEAD`: `c01c1082f4dea109752866e8a92d3421fbbed529`, `uname -a`: `Linux jacobs-pc 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux`

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.] Thanks for reading!

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by jackpot51** [comment]
I believe you need to update your rustc to at least 2017-03-23

**Comment by jsalzbergedu** [comment]
That did it, sorry if I wasted your time.
