### ISSUE TITLE
Any string containing "password" works for login

### ISSUE THREAD

**Issue by komawoyo** [redox-os/redox#892]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Release: 0.1.4 livedisk
Any string containing "password" works for login - this is not the same for username

user: `user`
password: `*password*`

Examlple: `4029340329password4093204klasfdslaj`

**Comment by jackpot51** [comment]
The `user` user has no password assigned, see filesystem/etc/passwd
