### ISSUE TITLE
Redox compilation error: vesad and orbutils

### ISSUE THREAD

**Issue by gjf2a** [redox-os/redox#899]
**Reproduction**: I downloaded the latest update to Redox on March 27. I then attempted to compile it with "make all".

**Expected behavior**: I expected the system to compile without errors.

**Actual behavior**: I encountered two compilation errors. 

   Compiling orbutils v0.1.14 (file:///Users/gabriel/redox/programs/orbutils)
warning: ignoring --out-dir flag due to -o flag.

error[E0004]: non-exhaustive patterns: `Input { .. }` and `ScreenBuffer { .. }` not covered
   --> programs/orbutils/src/terminal/console.rs:211:23
    |
211 |                 match event {
    |                       ^^^^^ patterns `Input { .. }` and `ScreenBuffer { .. }` not covered

error: aborting due to previous error

error: Could not compile `orbutils`.

To learn more, run the command again with --verbose.
make: *** [filesystem/ui/bin/terminal] Error 101

AND:

   Compiling vesad v0.1.0 (file:///Users/gabriel/redox/drivers/vesad)
warning: ignoring --out-dir flag due to -o flag.

error[E0004]: non-exhaustive patterns: `Input { .. }` and `ScreenBuffer { .. }` not covered
   --> drivers/vesad/src/screen/text.rs:180:23
    |
180 |                 match event {
    |                       ^^^^^ patterns `Input { .. }` and `ScreenBuffer { .. }` not covered

error: aborting due to previous error

error: Could not compile `vesad`.

To learn more, run the command again with --verbose.
make: *** [initfs/bin/vesad] Error 101
------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by gjf2a** [comment]
Also, I should add that I got it to compile as follows:

Added line 198 to drivers/vesad/src/screen/text.rs

_ => (),

Added line 249 to programs/orbutils/src/terminal/console.rs

_ => {}

I can't imagine that either of these band-aids is what is needed, but it was enough to compile and run it from qemu.

**Comment by jackpot51** [comment]
I hope this is fixed in the latest master

**Comment by InsidiousMind** [comment]
Had this exact issue, fetching/updating the submodules to master fixed it
