### ISSUE TITLE
Doesn't boot with qemu

### ISSUE THREAD

**Issue by bjorn3** [redox-os/redox#901]
**Reproduction**: Run `qemu-system-x86_64 -m 1024 -hda livedisk.iso` or `qemu-system-x86_64 -m 1024 -cdrom livedisk.iso`

**Expected behavior**: Redox boots

**Actual behavior**:
Shows
![schermafdruk van 2017-03-28 19 47 03_crop](https://cloud.githubusercontent.com/assets/17426603/24419631/1b005caa-13f0-11e7-8947-e3749c2dd583.png)
Then stops doing anything.

**Redox release**: 0.1.4

**Comment by ncarter100** [comment]
try adding -vga std, this works for me, without this option i see same as you....
qemu-system-x86_64 -m 1024 -cdrom livedisk.iso -vga std

**Comment by bjorn3** [comment]
`-vga std` works.
