### ISSUE TITLE
Exit command doesn't work

### ISSUE THREAD

**Issue by mnbvcxzlkjhgfdsapoiu** [redox-os/redox#916]

**Comment by xTibor** [comment]
Could you provide more information about how it doesn't work and some steps to reproduce your issue?

**Comment by polymetric1** [comment]
yeah, we're gonna need a bit more to go on than _No description provided._ Please fill out the issue template if possible

**Comment by mnbvcxzlkjhgfdsapoiu** [comment]
I'v booted livedisk.iso of redox 0.1.5 on virtualbox and I can't close shell using exit

![2017-04-13-103100_1600x900_scrot](https://cloud.githubusercontent.com/assets/27356266/24996924/09752d66-2035-11e7-8867-e4c66d97f4e6.png)

**Comment by jackpot51** [comment]
This is fixed in the latest git master
