### ISSUE TITLE
Submodule 'ui' reference is broken in 'programs/orbutils'

### ISSUE THREAD

**Issue by JonRinger** [redox-os/redox#917]
While trying to build Redox, I ran into the following issue:

**Reproduction**:
$ git clone https://github.com/redox-os/redox.git
$ cd redox/
$ git submodule update --recursive --init

**Expected behavior**:
update all linked repositories with no issues

**Actual behavior**: 
`Submodule path 'programs/orbutils': checked out '8d50cb7324238e5c1a3ab9c377f71332e958e61a'`
`fatal: no submodule mapping found in .gitmodules for path 'ui'`
`Failed to recurse into submodule path 'programs/orbutils'`

**Build information**: 
**rustc -V** rustc 1.18.0-nightly (c58c928e6 2017-04-11)
**git rev-parse HEAD** c1e014112272a39fe703caaec22118752600b7e7
**uname -rv** 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017

**Misc**: 
Github is also unable to follow the submodule if you visit redox-os/orbutils

**Comment by jackpot51** [comment]
Should be fixed now - thanks for filing a bug!

**Comment by ocschwar** [comment]
Fix confirmed.

**Comment by JonRinger** [comment]
Looks good! Awesome response time
