### ISSUE TITLE
Support for snap packages

### ISSUE THREAD

**Issue by pharaone** [redox-os/redox#918]
I know that this would be a very difficult thing to implement in redox, but supporting Snappy packets (those of canonical) you could use the same package on both linux on both redox. Their are also planning to support Windows and MacOS.

**Comment by Thetoxicarcade** [comment]
I would hope that it doesn't pin us down for too much of an interface.. would we have to be 1:1 compatible, or would we work with the snappy-dev team to address their upstream with the correct landing-pad on our upstream?

**Comment by Pharaone** [comment]
i think we have to be 1:1 compatible

**Comment by Thetoxicarcade** [comment]
filesystem wise? aaaagh
package layout wise? okay then
dynamic library wise? aaaaagggh
compiling wise? well... kinda?
ABI? aaaaaagggghhhhh

**Comment by annaleaser** [comment]
https://youtu.be/9Jala4vqYPw?t=5m21s

**Comment by pharaone** [comment]
I think that sandboxed apps are better for security, and redox aims to be protected

**Comment by jackpot51** [comment]
We have a method for containment. Feature requests should be put at https://github.com/redox-os/contain
