### ISSUE TITLE
Remove the `//` in URLs

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#92]
jkleo1 brings up a good note
> On a side note, it seems that double slash is required as part of the scheme in Redox while it is not actually a mandatory part in other URl usages. E.g. when specifing which application should open link for particular URI scheme it is not required.

**Comment by Ticki** [comment]
I suggest that we remove them. This will also give a cleaner interface.

**Comment by leodasvacas** [comment]
Tim Berners-Lee would :+1:  this. http://news.bbc.co.uk/2/hi/technology/8306631.stm

**Comment by jackpot51** [comment]
Sure, let's do it!

**Comment by mgattozzi** [comment]
Yes this will be much cleaner.
```
apps:// 
```
is not as nice looking as 
```
apps:
```

While were at it we'll want to consider some document describing exactly why we use URL, the standards for it etc.

**Comment by arzeth** [comment]
:+1: I wanted to suggest the same. *Personally*, I think // is a relic.

**Comment by Ticki** [comment]
I'll write a PR.

**Comment by ambaxter** [comment]
If we remove the // we're not really following the URL standard anymore. I imagine this might be confusing in the future for anyone expecting Redox URLs to follow the regular syntax. Perhaps we can find another syntax to fit our needs better?

**Comment by stratact** [comment]
@ambaxter we can support both. Either `scheme://host/path` or `scheme:host/path` would be accepted forms that do the same thing.

**Comment by hauleth** [comment]
@ambaxter yesterday it was discussed and we came to solution that kernel will give no damn interest in parsing URLs other than splitting scheme from description. It will be role of scheme consumer to validate and parse URL, so some of URLs could enforce slashes like `file`  would require `//` and `input` will not.

**Comment by ambaxter** [comment]
@hauleth That's workable. Could we signal that it's a different scheme by using a different struct or trait?

**Comment by jackpot51** [comment]
We agreed to leave this to each scheme

**Comment by Ticki** [comment]
#200 makes this up to the scheme.
