### ISSUE TITLE
Unable to make changes to Kernel code

### ISSUE THREAD

**Issue by kvgarimella** [redox-os/redox#933]
Hello, I'm working on a project in which I have to make some changes to the kernel code. Specifically, I'm making changes to kernel/src/scheme/sys/context.rs.  After I "make all" and run ps (which looks into this file) from ion, I do not see any of the changes I made to the above file.

Furthermore, I also called "cargo build" from within the kernel to recompile the kernel code, and I still do not see the changes I made.  Could someone point me in the right direction? 

Thanks!

**Comment by jackpot51** [comment]
`rm build/kernel/libkernel.a` and `make all` will do it

**Comment by kvgarimella** [comment]
Thanks, jackpot51!
