### ISSUE TITLE
redox setup: path to cargo is not automatically set and is not indicated what it should be

### ISSUE THREAD

**Issue by andrewufrank** [redox-os/redox#936]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
following the manual setup instruction:
    rustup override set nightly
**Expected behavior**: [describe the behavior you would expect the repro to yield.]
success
**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
rustup: command not found
**Build information**: [only when using a self build version: output of `rustc -V`, `git rev-parse HEAD` `qemu-i386 -version`, `uname -a`, etc.]
**Redox release**: [only when using a prebuild version: redox version]

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]
when I was installing rustup i had to `export RUSTUP_USE_HYPER=1` (issue 935) and got at the end the message that the $PATH to cargo would be set outomatically when I would login the next time. i did a reboot and then logged in. the path to cargo is not set and i cannot find out, what it should be.  (it would be save when the message would inform about the automatic setup which is a good thing, but still state which path to set to which value in case something goes wrong).
Help appreciated!

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by bjorn3** [comment]
Add `source $HOME/.cargo/bin/env` to the end of your `.bashrc`.

**Comment by andrewufrank** [comment]
thank you - i figured it out in the end and i am happy to see that nothing else is intended.

it would be nice to state in the output:
"the path to .cargo will be added to your PATH automatically when you open a new terminal window - if, for some reasons, this is not happening add "PATH=$HOME/.cargo/bin/env:$PATH" to the end of your .bashrc".
