### ISSUE TITLE
MIT Licence doesn't suit OS Development

### ISSUE THREAD

**Issue by anon8000** [redox-os/redox#958]
Here the Redox Founder says he doesn't care about Licence:
https://youtu.be/eH5JgMlNE8o?t=2681
While he does make other nonsense comments about Free Software Projects and why he thinks they are in a bad shape and such, he obviously has no Idea or is "paid" to not care.

That's a very bad move. Nobody in their right mind will join a OS Project after all what People have seen happening in with Free Software and everything surrounding it, unless they are to young to know or are misinformed.

I suggest changing to GPL3. It's litterally a Licence made for OS Development.
GPL Version 3 Background to Adoption: https://www.fsf.org/news/gpl3.html
A Quick Guide: http://www.gnu.org/licenses/quick-guide-gplv3.en.html

Here are some Videos about Free Software you have to watch:
https://www.youtube.com/watch?v=b3uX5XwdN_8
https://www.youtube.com/watch?v=POexV1k62_Y

That said, even if your one and only purpose for this Project is to advertise the Rust Language it's still a very bad move with the MIT Licence. Those who know how things go won't ever invest development time into this because they'd be just wasting it. I myself would start learning the Rust Language if Redox had a GPL3 complete Licence. At the moment it's basically the only interessting Project that uses that Language but it just doesn't make sense learning it for something that's broken because of licensing.

**Comment by le-jzr** [comment]
GPL is a crackpot licence that has nothing to do with software freedom, it's just about forcing people to do as you say. If you don't like MIT, you can always start your own project.

**Comment by anon8000** [comment]
@le-jzr 
> nothing to do with software freedom
It's the very definition of software freedom for developer and the user of the software. It not forcing people to do anything but prevent people from doing harm to developers of a project or to the users. That's a difference. Please gain some Knowledge about this before posting things that are plain wrong.

**Comment by bjorn3** [comment]
@anon8000 quote longer than expected. Maybe you forgot a newline between the quote and your own text.

**Comment by anon8000** [comment]
@bjorn3
yes, fixed it.

**Comment by atenie** [comment]
@anon8000 
Please tell us how systemd (a GPL project, mind you) doesn't harm people through its potential lack of security.

Or how forcing people to use one particular license would suddenly stop the potential of that project being corrupted by external, potentially harmful sources.

**Comment by anon8000** [comment]
@atenie 
There is bad Software with good Licensing and there is good Software with bad Licensing. The GPL was designed to prevent 3rd Parties to do harm against developers and it users and not to magically make developers write good Software. Does this answer your question?

**Comment by atenie** [comment]
@anon8000 then how do 3rd parties harm developers or users through the MIT License?

**Comment by Krakn** [comment]
https://doc.redox-os.org/book/introduction/why_free_software.html

Locked in 3... 2... 1...

**Comment by anon8000** [comment]
@atenie 
The most obvious thing would be someone takes the code and makes it closed source. While this doesn't do much to the developer who doesn't care, it harms the user as it could contain malicious software and he can't modify the source for his needs. It hurts the Project and it's Developer still because "new Developer" rather not join a Project that could become a closed source something any day completly wasting their time for someone else profit. Because it scares away new developers the project will stagnate and die once the main developer burns out, gives up or has an acccident. 

@Krakn 
Let's say, Redox OS becomes successfull for some reason. A big company will ship it pre-installed and advertises it with it being "Free Software". Customers buy it, only to find out there is no source code. It's actually very different from Redox OS and you can only compile source written in Apple Swift Language and Java. They even locked the bootloader to prevent users from installing a different OS. Even if they manage to break through that lock the source pieces needed to make another OS run on that System aren't open. People find it crappy and rate "Redox OS" very bad everywhere. Redox OS and Rust Language become a synoym for bad software. Companies won't employ Developers with "Redox OS" in their Resume because of that. (Many things in this already happend a few times with other "Free Software Project")

**Comment by FSMaxB** [comment]
The MIT license doesn't allow the use of trademarks, just the code! So a proprietary fork can't badmouth Redox OS!

**Comment by anon8000** [comment]
@FSMaxB 
They can still say it's based on Redox OS and Free Software an have the same Effect. While this is also true with GPL3 based Software, they can't lock out users or prevent Developers to provide a better Version and expirence like they could with MIT License.

**Comment by FSMaxB** [comment]
While the MIT might keep developers like you away, it will attract developers working for companies that use the software. And most developers that work on free software in their free time won't have any issues with the MIT license, so it won't scare them away either.

I doubt that the GPL has any positive impact in terms of attracting new developers.

While copyleft can be a nice thing, it definitely has it's downsides and it is a valid decision to choose to make free software without it.

**Comment by Coder206** [comment]
After reading some of the posts and based on past research I found that according to (https://www.gnu.org/licenses/license-list.en.html#X11License) both MIT and GPL3 are compatible with one another. Could this help make a compromise for everyone's​ views?

**Comment by anon8000** [comment]
@Coder206 
"Compatible" only means they can work together and can be distributed. This completly misses the point of the main Licence being a bad choice for an OS.

**Comment by Coder206** [comment]
@anon8000 I see, if you have some time do you mind elaborating on what you mean by:

> "Compatible" only means they can work together and can be distributed

Wouldn't it be good to harness the positives of both licenses?

**Comment by anon8000** [comment]
@FSMaxB 
>it will attract developers working for companies
I doubt that. First you need to have something to get them interessted and for this you need developers to participate. Since you probably can't pay them to develop for you, you probably want free Software Developers that work out of self interesst because they want to use it themselves for example. Now, you see where this is going..... For many years many have been burned and simply won't touch Project they know arent doing it right.

@Coder206 
I don't see your point. Why would anyone even use MIT Licence for something other then "I don't care about this".

**Comment by atenie** [comment]
@anon8000 you're still trying to argue that license influences code quality. It doesn't.

But a more permissive license does attract companies, like it or not. They can use it to their like, without having their hands tied. And for either good, or bad. As for malware, people do already use free software for malware, no matter what license. I haven't seen an army of GNU lawyers, either.

**Comment by FSMaxB** [comment]
@anon8000 I myself have been working on free software for companies. And it wouldn't have happened with copyleft!

And when I was writing GPL'ed software myself, I was constantly concerned about license compatibility. If you want all GPL software out there to benefit, you need to use GPLv2 or later. But then you can't depend on GPLv3 anymore and not on GPLv2 either if it doesn't have the "or later clause". It's just a mess. If you were to depend on GPLv3 software, your software would become GPLv3 as well. So the only choice that you have in that case is either to depend on stuff with GPLv3 or later or in liberally licensed software without copyleft.

At one point I decided to use ISC for all of my software.

**Comment by FSMaxB** [comment]
And if you use the "Or later" clause, the free software foundation still has the right to turn your license in a license without copyleft (that's rather theoretical, but still kindof funny).

**Comment by anon8000** [comment]
@atenie 
@FSMaxB 
If Redox OS is only for internal use for companies it's actually quite bad too. So you basically say you want Developers lose their jobs because someone provides companies with Software that doesn't cost them anything and it just doesn't make sense to still employ your own developers. Who wants to contribute code to project that made them lose their jobs and they can't even use privately?

**Comment by Coder206** [comment]
@anon8000 It would be interesting to hear about a real world example where developers have lost their jobs to open and free projects? Also, I think there are a few examples of companies that utilize free software, build upon it and give back to the community. (Red Hat and Fedora)

**Comment by le-jzr** [comment]
@anon8000 As I said, nobody prevents you writing your own GPL-licenced OS from scratch, and seeing which one wins out in the end. It seems to me you just can't bear solid projects that don't follow your particular ideology. That, and the arguments are getting more ridiculous each time you comment. Unsubscribing.

**Comment by anon8000** [comment]
@Coder206 
Nah, that's not internal use anymore. Red Hat is a company providing "service" around Free Software and they basically exist because of GPL Licenced Software and them contributing back is also because of Copy-Left in the GPL. If you have a wet dream about becoming a Service Provider around Redox OS you still need a critical mass to get adopted by companies in the first place and what can you even provide better than Linux or SEL4? Remeber why Plan9 didn't take off in the first place? Companies said Unix was good enough. So, how to make Redox OS a success you can open a company listed in the stock exchange? How about adopting the right licence so Developers actually feel like doing something "for free" because they know when their code is used it destined to get improved on and they get something back in return.

**Comment by jdanford** [comment]
> How about adopting the right licence so Developers actually feel like doing something "for free"

I'm quite happy doing work "for free" on MIT-licensed projects, and you're getting a lot of pushback in this thread, so what if you reconsidered trying to speak for "developers" in general?

**Comment by jackpot51** [comment]
:rofl:

**Comment by anon8000** [comment]
@Jdanford
I doubt you work for free and if you actually do it for a MIT-Licenced project, sorry you basically said you don't need food and want others to lose their means to get food too.

@jackpot51
>does suit
 
Nope, it isn't. If the Project decides to keep that Licence there is obviously nothing I can do about it. I've opened this ticked an did my part. However "I don't care about Licencing so I use MIT" doesn't make it suitable it simply shows you don't care. So don't cry when people don't care enough to use it.

**Comment by jackpot51** [comment]
@anon8000 You are in the significant minority that demand GPLv3 and will not work on an MIT project. Also, you hide behind an anonymous, brand new user account where the only original work linked to it is your icon and this text:

```
Just found you're not using GPL3 in a Software Project. I'll tell you it's retarded because it is.
```

Kindly leave, and come back when you are ready to be an adult.

**Comment by anon8000** [comment]
>You are in the significant minority that demand GPLv3 and will not work on an MIT project. Also, you hide behind an anonymous, brand new user account where the only original work linked to it is your icon and this text:

Minority it is, eh? Well, you might be right about this. Well, I said what I had to say. You could have listened but you choosed otherwise. For the rest of your post, it's not an argument.

**Comment by jackpot51** [comment]
http://imgur.com/1ctjRGZ

**Comment by jackpot51** [comment]
Source of trolls: https://8ch.net/tech/res/756210.html
