### ISSUE TITLE
cook drivers version for webpki ^0.8.0 cannot find 0.13.0, 0.12.0

### ISSUE THREAD

**Issue by Thetoxicarcade** [redox-os/redox#960]
When cook tries to get the drivers updated for webpki, it fails. (see actual behavior)
**Reproduction**:
`make clean && make all`
git version: #0ef251d

**Expected behavior**: I knew that my latest build on rust nightly from yesterday didn't work, so I didn't expect it to get far, just error at some point, really.

**Actual behavior**:

```
copy from `../stage/bin/vesad' [elf64-x86-64] to `../stage/bin/stCTCOOs' [elf64-x86-64]
cook - drivers tar
cook - drivers version
'stage.toml' -> 'stage/pkg/drivers.toml'
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/libOctavo/octavo.git`
    Updating git repository `https://github.com/redox-os/tar-rs`
error: no matching version `^0.8.0` found for package `webpki` (required by `webpki-roots`)
location searched: registry https://github.com/rust-lang/crates.io-index
versions found: 0.13.0, 0.12.1
./repo.sh failed.mk/initfs.mk:2: recipe for target 'build/initfs.tag' failed
make: *** [build/initfs.tag] Error 1
```

**Build information**:
- rustc 1.19.0-nightly (148e91714 2017-06-08)
- 0ef251dce41d1b27ab8354eb71c938b044a58f1b
- not relevant but: qemu-i386 version 2.7.1(qemu-2.7.1-6.fc25), Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers
- Linux localhost.localdomain 4.11.3-200.fc25.x86_64 #1 SMP Thu May 25 19:03:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (Korora, Fedora Derivative)

Do you need longer logs? See Attached.
[longredoxlog.txt](https://github.com/redox-os/redox/files/1065564/longredoxlog.txt)

**Comment by jackpot51** [comment]
Can you:
```
git pull
git submodule update --recursive --init
cd cookbook
./clean.sh
cd ..
make
```

**Comment by Thetoxicarcade** [comment]
running now.

**Comment by Thetoxicarcade** [comment]
* git pull
> already up to date
* git submodule update --recursive --init
> got mad on these, so I added --force:
```
Unable to checkout '1ef3b9128e1baaed61b42d5b0de79dee100acf17' in submodule path 'rust/src/llvm'
Unable to checkout 'da282f1bb7277b4d30fa1599ee29ad8eb4dd2a92' in submodule path 'rust/src/rt/hoedown'
Unable to checkout 'bbfe9b3a9d64aa8698b18cbb3803b3fa00ee3f44' in submodule path 'rust/src/tools/cargo'
Unable to checkout 'bfe80cfa8db75500e67ca8762465d27662674637' in submodule path 'rust/src/tools/rls'

```
* clean.sh
> no errors
* fetch.sh
> uuuuuugggghhhhh network speed
* make
> pending. Lots of unused, unreachable, or unnecessary unsafes, but that's okay
> cook contain `version` : no such subcommand config (non-critical error) (happened twice)
> goodness this stuff takes a long time.

> still pending, but I'll save here.

so we just need to run `./clean.sh && ./fetch.sh` from now on if the build fails? Just a readme update?

**Comment by Thetoxicarcade** [comment]
Cool, that worked. Aside from the login window saying:
```
`user`
`root`: `password`
```
everything else is good.

**Comment by jackpot51** [comment]
Usually, just a ./fetch.sh is required. I am still working on the build system, it has been rewritten to use the cookbook and is not as predictable as the previous one.
