### ISSUE TITLE
Redox OS fails to build on Ubuntu

### ISSUE THREAD

**Issue by Csega** [redox-os/redox#964]
**Reproduction**: use the latest master with bootstrap.sh, then cd redox and make all.

**Expected behavior**: compile Redox OS.

**Actual behavior**: the build fails.

**Build information**: rustc 1.19.0-nightly (03abb1bd7 2017-06-13), git HEAD: b808f501b93edb4893849399245ad767afdae203, qemu-i386 version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.14), Copyright (c) 2003-2008 Fabrice Bellard, Linux csega-eos-loki 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux.

**Misc**: I got the following error message:

Running `installer/target/debug/redox_installer --cookbook=cookbook initfs.toml`
Install Config {
    general: GeneralConfig {
        prompt: false,
        sysroot: Some(
            "build/initfs"
        )
    },
    packages: {
        "drivers": PackageConfig {
            version: None,
            git: None,
            path: None
        },
        "init": PackageConfig {
            version: None,
            git: None,
            path: None
        },
        "redoxfs": PackageConfig {
            version: None,
            git: None,
            path: None
        }
    },
    files: [
        FileConfig {
            path: "/etc/init.rc",
            data: "export PATH initfs:/bin\nvesad T T G\nstdio display:1\nps2d\npcid /etc/pcid.toml\nredoxfs disk:0 file\ncd file:\nexport PATH file:/bin\nrun.d /etc/init.d\n"
        }
    ],
    users: {}
}
Create directory /home/csega/redox/build/initfs/
repo - fetching drivers
cook - drivers fetch
Cloning into 'source'...
remote: Counting objects: 1139, done.
remote: Total 1139 (delta 0), reused 0 (delta 0), pack-reused 1139
Receiving objects: 100% (1139/1139), 208.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (488/488), done.
Checking connectivity... done.
Already up-to-date.
repo - preparing drivers
cook - drivers prepare
repo - building drivers
cook - drivers update
./cook.sh: line 131: xargo: command not found
./repo.sh failed.mk/initfs.mk:2: recipe for target 'build/initfs.tag' failed
make: *** [build/initfs.tag] Error 1

**Comment by mortonar** [comment]
Is this perhaps a duplicate of #954?

**Comment by Csega** [comment]
Oops, sorry. Yes, it seems so. I tried to look for it in amongst the issues, but I did not find this one.

**Comment by mortonar** [comment]
No worries.

Would you mind closing this since we have visibility on this already? Should be able to install xargo manually as a workaround:
```
➜  redox git:(master) cargo install xargo 
```

**Comment by Csega** [comment]
Thanks, the workaround works, issue closed. :)

**Comment by mortonar** [comment]
Thanks!
