### ISSUE TITLE
Bootstrap doesn't install xargo

### ISSUE THREAD

**Issue by jmikkola** [redox-os/redox#967]
**Reproduction**: 

- Clone the repo
- Init submodules
- Run the bootstrap script
- Run `make all`

**Expected behavior**: it compiles

**Actual behavior**: 

```
./cook.sh: line 131: xargo: command not found
./repo.sh failed.mk/initfs.mk:2: recipe for target 'build/initfs.tag' failed
make: *** [build/initfs.tag] Error 1
```

**Build information**:

- rustc 1.19.0-nightly (fe7227f6c 2017-06-16)
- HEAD = 56504fc8b179eeed0ae6001e01e9f923ae28526e
- uname -a: `Linux firefly 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

I fixed this by running

    cargo install xargo

**Comment by bjorn3** [comment]
Dup of #954
