### ISSUE TITLE
dockerfile misses README how to use it

### ISSUE THREAD

**Issue by jinnzest** [redox-os/redox#975]
Dockerfile and entrypoint.sh is added but there is no README file how to use it. 

@batonius could You add README?

**Comment by batonius** [comment]
I'm not sure if Dockerfile is supposed to be used directly, the idea was to have an official image on dockerhub and then integrate everything into Makefile. 

For now, you can check out #973 for a quick how-to, but it's kinda messy. I think I can flesh it out into a proper readme if @jackpot51 isn't ready to bless docker as the default toolchain distribution mechanism yet.
