### ISSUE TITLE
Build fails, alloc::vec unresolved import 

### ISSUE THREAD

**Issue by gjsieben** [redox-os/redox#976]
**Expected behavior**:
Expect the thing to build, obviously.

**Actual behavior**:
Despite making sure to put all dependencies in (and use nightly), I get:
```
Compiling orbclient v0.3.8
   Compiling bgad v0.1.0 (file:///home/gabriel/redox/cookbook/recipes/drivers/build/bgad)
error[E0432]: unresolved import `alloc::Vec`
 --> /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/orbclient-0.3.8/src/graphicspath.rs:1:5
  |
1 | use alloc::Vec;
  |     ^^^^^^^^^^ no `Vec` in the root

error: aborting due to previous error(s)

error: Could not compile `orbclient`.
warning: build failed, waiting for other jobs to finish...
error: build failed
./repo.sh failed.mk/initfs.mk:2: recipe for target 'build/initfs.tag' failed
make: *** [build/initfs.tag] Error 1

```

**Build information**: 
rustc 1.20.0-nightly (ab5bec255 2017-06-22)
Linux ubuntu 4.10.0-24-generic #28-Ubuntu SMP Wed Jun 14 08:14:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Redox release**: master

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by ids1024** [comment]
I think a `git pull; git submodule update --recursive --init` should fix this, now that the rust submodule has been updated (since this issue was submitted).

If it still fails, try doing `make clean` as well.

**Comment by gjsieben** [comment]
I did `make clean` after the suggested commands, and I didn't run into this issue. Thanks for the help!
