### ISSUE TITLE
Is `x86_64-elf-redox-gcc` not installed?

### ISSUE THREAD

**Issue by Olivered** [redox-os/redox#977]
**Reproduction**: 
make all
**Expected behavior**: 
build succeeds
**Actual behavior**: 
running: "x86_64-elf-redox-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffreestanding" "-m64" "-fno-builtin" "-fvisibility=hidden" "-fomit-frame-pointer" "-ffreestanding" "-DVISIBILITY_HIDDEN" "-o" "/var/folders/w2/4xzz78pd24sb2mmssx4_d3tw0000gp/T/xargo.xTq7FE6PUvQ7/target/x86_64-unknown-redox/release/build/compiler_builtins-5e8895d281cea536/out/compiler-rt/../compiler-rt/lib/builtins/absvdi2.o" "-c" "../compiler-rt/lib/builtins/absvdi2.c"

failed to execute command: No such file or directory (os error 2)
Is `x86_64-elf-redox-gcc` not installed?

**Build information**: 
rustc 1.20.0-nightly (229d0d326 2017-06-23)
git rev 12f419e6d26a3444a5b0de3fa9566e305003372e
Darwin Macbook-Pro 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64 i386 MacBookPro12,1 Darwin
xcode, redox-os/x86_64-elf packages installed

**Comment by BearzRobotics** [comment]
Both of these issues have to same problem.
#970 #974 

Your going to have to clone redox libc repo and build their toolchain. https://github.com/redox-os/libc and run ./setup.sh all. If your on Solus their automake is to new, and another library will have to be down graded.

git clone https://github.com/redox-os/libc/
cd libc
git submodule update --init
./setup.sh all
export PATH=$PWD/build/prefix/bin:$PATH

I hope this helps.

**Comment by Olivered** [comment]
Lol not only that. building redox is a monster.

git clone https://github.com/redox-os/libc/
cd libc
git submodule update --init
git pull --rebase --recurse-submodules
git submodule sync
git submodule update --recursive --init
//recursive submodule update because some of the folders dont even download!
git clean -X -f -d
git -C newlib pull origin redox
Also you need to manually comment out two lines in setup.sh:
replace "aclocal-1.11 -I ../.." with "#aclocal-1.11 -I ../.."
replace " automake-1.11 --cygnus Makefile" with " automake-1.11 --cygnus Makefile"
brew install autoconf automake libtool
brew install autoconf@2.64
sudo ln -s /usr/local/bin/autoconf264 /usr/local/bin/autoconf2.64
//link the brew binary to a shortcut the files understand
./setup.sh all
export PATH=$PWD/build/prefix/bin:$PATH

**Comment by Olivered** [comment]
/Users/user/Redox/libc/build/cross/gcc/gcc/include-fixed/limits.h:34:10: fatal error: syslimits.h: No such file or directory

**Comment by Olivered** [comment]
/Users/user/Redox/libc/build/cross/gcc/./gcc/xgcc -B/Users/user/Redox/libc/build/cross/gcc/./gcc/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/bin/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/lib/ -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/include -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/sys-include    -g -O2 -O2  -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fpic -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fpic -I. -I. -I../.././gcc -I/Users/user/Redox/libc/gcc/libgcc -I/Users/user/Redox/libc/gcc/libgcc/. -I/Users/user/Redox/libc/gcc/libgcc/../gcc -I/Users/user/Redox/libc/gcc/libgcc/../include  -DHAVE_CC_TLS  -o _muldi3.o -MT _muldi3.o -MD -MP -MF _muldi3.dep -DL_muldi3 -c /Users/user/Redox/libc/gcc/libgcc/libgcc2.c -fvisibility=hidden -DHIDE_EXPORTS
/Users/user/Redox/libc/build/cross/gcc/./gcc/xgcc -B/Users/user/Redox/libc/build/cross/gcc/./gcc/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/bin/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/lib/ -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/include -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/sys-include    -g -O2 -O2  -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fpic -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fpic -I. -I. -I../.././gcc -I/Users/user/Redox/libc/gcc/libgcc -I/Users/user/Redox/libc/gcc/libgcc/. -I/Users/user/Redox/libc/gcc/libgcc/../gcc -I/Users/user/Redox/libc/gcc/libgcc/../include  -DHAVE_CC_TLS  -o _negdi2.o -MT _negdi2.o -MD -MP -MF _negdi2.dep -DL_negdi2 -c /Users/user/Redox/libc/gcc/libgcc/libgcc2.c -fvisibility=hidden -DHIDE_EXPORTS
/Users/user/Redox/libc/build/cross/gcc/./gcc/xgcc -B/Users/user/Redox/libc/build/cross/gcc/./gcc/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/bin/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/lib/ -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/include -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/sys-include    -g -O2 -O2  -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fpic -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fpic -I. -I. -I../.././gcc -I/Users/user/Redox/libc/gcc/libgcc -I/Users/user/Redox/libc/gcc/libgcc/. -I/Users/user/Redox/libc/gcc/libgcc/../gcc -I/Users/user/Redox/libc/gcc/libgcc/../include  -DHAVE_CC_TLS  -o _lshrdi3.o -MT _lshrdi3.o -MD -MP -MF _lshrdi3.dep -DL_lshrdi3 -c /Users/user/Redox/libc/gcc/libgcc/libgcc2.c -fvisibility=hidden -DHIDE_EXPORTS
if [ -z "" ]; then \
	  true; \
	else \
	  rootpre=`${PWDCMD-pwd}`/; export rootpre; \
	  srcrootpre=`cd /Users/user/Redox/libc/gcc/libgcc; ${PWDCMD-pwd}`/; export srcrootpre; \
	  lib=`echo "${rootpre}" | sed -e 's,^.*/\([^/][^/]*\)/$,\1,'`; \
	  compiler="/Users/user/Redox/libc/build/cross/gcc/./gcc/xgcc -B/Users/user/Redox/libc/build/cross/gcc/./gcc/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/bin/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/lib/ -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/include -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/sys-include   "; \
	  for i in `${compiler} --print-multi-lib 2>/dev/null`; do \
	    dir=`echo $i | sed -e 's/;.*$//'`; \
	    if [ "${dir}" = "." ]; then \
	      true; \
	    else \
	      if [ -d ../${dir}/${lib} ]; then \
		flags=`echo $i | sed -e 's/^[^;]*;//' -e 's/@/ -/g'`; \
		if (cd ../${dir}/${lib}; /Applications/Xcode.app/Contents/Developer/usr/bin/make "AR=/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/bin/ar" "AR_FLAGS=rc" "CC=/Users/user/Redox/libc/build/cross/gcc/./gcc/xgcc -B/Users/user/Redox/libc/build/cross/gcc/./gcc/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/bin/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/lib/ -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/include -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/sys-include   " "CFLAGS=-g -O2" "DESTDIR=" "EXTRA_OFILES=" "HDEFINES=" "INSTALL=/usr/local/opt/coreutils/libexec/gnubin/install -c" "INSTALL_DATA=/usr/local/opt/coreutils/libexec/gnubin/install -c -m 644" "INSTALL_PROGRAM=/usr/local/opt/coreutils/libexec/gnubin/install -c" "LDFLAGS=" "LOADLIBES=" "RANLIB=/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/bin/ranlib" "SHELL=/bin/sh" "prefix=/Users/user/Redox/libc/build/prefix" "exec_prefix=/Users/user/Redox/libc/build/prefix" "libdir=/Users/user/Redox/libc/build/prefix/lib" "libsubdir=/Users/user/Redox/libc/build/prefix/lib/gcc/x86_64-elf-redox/7.0.1" "tooldir=/Users/user/Redox/libc/build/prefix/x86_64-elf-redox" \
				CFLAGS="-g -O2 ${flags}" \
				CCASFLAGS=" ${flags}" \
				FCFLAGS=" ${flags}" \
				FFLAGS=" ${flags}" \
				ADAFLAGS=" ${flags}" \
				prefix="/Users/user/Redox/libc/build/prefix" \
				exec_prefix="/Users/user/Redox/libc/build/prefix" \
				GOCFLAGS="-O2 -g ${flags}" \
				CXXFLAGS="-g -O2 ${flags}" \
				LIBCFLAGS="-g -O2 ${flags}" \
				LIBCXXFLAGS="-g -O2 -fno-implicit-templates ${flags}" \
				LDFLAGS=" ${flags}" \
				MULTIFLAGS="${flags}" \
				DESTDIR="" \
				INSTALL="/usr/local/opt/coreutils/libexec/gnubin/install -c" \
				INSTALL_DATA="/usr/local/opt/coreutils/libexec/gnubin/install -c -m 644" \
				INSTALL_PROGRAM="/usr/local/opt/coreutils/libexec/gnubin/install -c" \
				INSTALL_SCRIPT="/usr/local/opt/coreutils/libexec/gnubin/install -c" \
				all); then \
		  true; \
		else \
		  exit 1; \
		fi; \
	      else true; \
	      fi; \
	    fi; \
	  done; \
	fi
/Users/user/Redox/libc/build/cross/gcc/./gcc/xgcc -B/Users/user/Redox/libc/build/cross/gcc/./gcc/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/bin/ -B/Users/user/Redox/libc/build/prefix/x86_64-elf-redox/lib/ -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/include -isystem /Users/user/Redox/libc/build/prefix/x86_64-elf-redox/sys-include    -g -O2 -O2  -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fpic -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fpic -I. -I. -I../.././gcc -I/Users/user/Redox/libc/gcc/libgcc -I/Users/user/Redox/libc/gcc/libgcc/. -I/Users/user/Redox/libc/gcc/libgcc/../gcc -I/Users/user/Redox/libc/gcc/libgcc/../include  -DHAVE_CC_TLS  -o _ashldi3.o -MT _ashldi3.o -MD -MP -MF _ashldi3.dep -DL_ashldi3 -c /Users/user/Redox/libc/gcc/libgcc/libgcc2.c -fvisibility=hidden -DHIDE_EXPORTS
In file included from /Users/user/Redox/libc/gcc/libgcc/../gcc/tsystem.h:105:0,
                 from /Users/user/Redox/libc/gcc/libgcc/libgcc2.c:27:
/Users/user/Redox/libc/build/cross/gcc/gcc/include-fixed/limits.h:34:10: fatal error: syslimits.h: No such file or directory
 #include "syslimits.h"

**Comment by bjorn3** [comment]
Please put the text in your previous comment between triple backticks (`\``)

**Comment by Olivered** [comment]
https://github.com/redox-os/redox/blob/master/docker/README.md
Requires : brew install docker docker-machine && brew cask docker
then you gotta run the graphical docker app and give it permissions

Gets to ion-shell and stops- but I consider this a lot simpler and faster than trying a native compile.

**Comment by Olivered** [comment]
*build* it in docker. I mean, why go to the hassle of setting up a cross-platform gcc toolchain so you .can compile elf while you compile your elf dawg
