### ISSUE TITLE
user: pkg failed to unpack message

### ISSUE THREAD

**Issue by aspera-non-spernit** [redox-os/redox#982]
**Reproduction**:

    # pkg install <PACKAGE>
 
**Actual behavior**: 
    Redox lets user download pkg to /tmp but message doesn't quiet tell that user isn't allowed to install.

    * Requesting https://static.redox-os.org/pkg/x86_64-unknown-redox/games.sig
    124 B / 124 B [===========================================] 100.00 % 5.38 KB/s  
    * Already downloaded games
    pkg: install: games: failed: failed to unpack `/pkg/games.toml`

**Expected Behaviour**

    A message that user cannot install packages, before download of package. Refer to fetch

**Comment by ids1024** [comment]
> Redox lets user download pkg to /tmp but message doesn't quiet tell that user isn't allowed to install.

I presume you've figured it out from this comment, but in case you haven't, the command requires `sudo`.

The error message should be clearer though.
