### ISSUE TITLE
can't build redux using docker

### ISSUE THREAD

**Issue by jinnzest** [redox-os/redox#983]
**Reproduction**: 
Following instructions described here https://github.com/redox-os/redox/blob/master/docker/README.md

**Expected behavior**: running redux in qemu

**Actual behavior**: 
Step 3 of the instruction is completed successfully. 
But step 4 is failed:
 `docker run --cap-add MKNOD --cap-add SYS_ADMIN     --device /dev/fuse -e LOCAL_USER_ID="$(id -u)"     -v "$(pwd):/src" --rm redox make all`
returned: 
`Starting with UID : 502 `
`CARGO_HOME is /cargo`
`RUSTUP_HOME is /rustup`
`make: *** No rule to make target 'all'.  Stop.`

**Redox release**:  last master commit

**Misc**: I tried to run it on macos sierra

**Comment by bjorn3** [comment]
Redox doesnt build on macos currently.

**Comment by jinnzest** [comment]
@bjorn3
For sure it doesn't. But I thought that using docker makes it possible to build redox on macos. 
After all, VM is invented to be able to run a system inside another one. 

Could you provide me a hint in what direction to dig to make it able to run docker based compilation on mac?

**Comment by batonius** [comment]
@jinnzest That means there is no `Makefile` in your current directory, are you running the command in the `redox` dir?

@bjorn3 The docker method works fine on macOs, according to the reports I've seen.

**Comment by jinnzest** [comment]
@batonius 
Looks like `-v "$(pwd):/src"` doesn't work in my case. I have remotely logined to the docker vm and found that /src is empty. So it is related to docker on macos only.
