### ISSUE TITLE
error: Could not compile `untrusted'

### ISSUE THREAD

**Issue by gnfrazier** [redox-os/redox#984]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Ubuntu 17.10
$ curl -sf https://raw.githubusercontent.com/redox-os/redox/master/bootstrap.sh -o bootstrap.sh && bash -e bootstrap.sh
Completes
cd redox
make all

begins to compile 
fails on untrusted

error: Could not compile `untrusted'

Terminal output: https://gist.github.com/gnfrazier/e377e2bfec85b83cc49c495a1cdf654d

**Expected behavior**: [describe the behavior you would expect the repro to yield.]
Completed compile
**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
Failed complile
https://gist.github.com/gnfrazier/e377e2bfec85b83cc49c495a1cdf654d

**Build information**: [only when using a self build version: output of `rustc -V`, `git rev-parse HEAD` `qemu-i386 -version`, `uname -a`, etc.]
rustc 1.16.0
cargo-0.17.0 (built 2017-03-24)

**Redox release**: [only when using a prebuild version: redox version]
Command not found
**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by bjorn3** [comment]
You need to use a nightly rustc to compile redox. Maybe try the docker build env (https://github.com/redox-os/redox/blob/master/docker/README.md)

**Comment by gnfrazier** [comment]
Updating rustc worked. Had to uninstall rustc, then install rustup, then rustup update. 

OK to close.
