### ISSUE TITLE
qemu does not work with the newest revision

### ISSUE THREAD

**Issue by Csega** [redox-os/redox#991]
Hi guys,

I got the following problem with the last few version (including the latest master revision).

**Reproduction**: make a clean installation using the newest bootstrap.sh, then cd redox, then make all, then make qemu kvm=no

**Expected behavior**: Successful build and a working system.

**Actual behavior**: the build is successful, however, the make qemu kvm=no has the following output:

make qemu kvm=no
SDL_VIDEO_X11_DGAMOUSE=0 qemu-system-x86_64 -serial mon:stdio -d cpu_reset -d guest_errors -smp 4 -m 2048 -machine q35 -device ich9-intel-hda -device hda-duplex -net nic,model=e1000 -net user -net dump,file=build/network.pcap -device nec-usb-xhci,id=xhci -device usb-tablet,bus=xhci.0 \
	-drive file=build/harddrive.bin,format=raw \
	-drive file=build/extra.qcow2
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory
mk/qemu.mk:38: recipe for target 'qemu' failed
make: *** [qemu] Error 1

**Build information**: `rustc -V`: rustc 1.20.0-nightly (d84693b93 2017-07-09)
                                   `git rev-parse HEAD`: ca4159b1eca9173d13c5c626ac2ec0b6087bfd7f
                                   `qemu-i386 -version`: qemu-i386 version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.14), Copyright (c) 2003-2008 Fabrice Bellard
                                   `uname -a`: Linux csega-eos-loki 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

What could be the problem?

Cheers,
Csega

**Comment by xTibor** [comment]
Do you have enough free memory in your system? "Cannot allocate memory" suggests your system might have run out of memory. At least 2 gigabytes of free RAM needed to run `make qemu` by default.

I can reproduce this error on my machine by increasing `-m 2048` in `/mk/qemu.mk` to an unreasonably high value.

**Comment by Csega** [comment]
So far it worked. But I try to increase the allocated memory (I run redox on a virtual machine).

**Comment by Csega** [comment]
Sorry, my bad, this was the problem. I just double the amount of RAM (from 1 GB to 2 GB) for the virtual machine, and it worked again. But so far it went with 1 GB too. Does this mean, that Redox requirements for RAM increased?
