### ISSUE TITLE
It still can't run in VMware(Windows 10)

### ISSUE THREAD

**Issue by 3442853561** [redox-os/redox#999]
like https://github.com/redox-os/redox/issues/821

**Comment by xTibor** [comment]
Could you fill out the [issue template](https://github.com/redox-os/redox/blob/master/.github/ISSUE_TEMPLATE) and include your system specs with your VMware config? That would greatly help diagnosing your problem.

**Comment by lilianmoraru** [comment]
For me, it doesn't start in Windows 7(VMWare).
After I select the desired resolution at startup, it just shows a blank screen(completely black screen).

**Comment by jackpot51** [comment]
Can you please try using VirtualBox? I have no method of testing VMWare, and do not expect to support it when there are cross-platform, open source alternatives

**Comment by MarcusE1W** [comment]
Hi I am using VirtualBox and face a very similar problem. The Configuration of the box is the same that I used for 0.2 where is worked. After booting the prompt for the display size comes up, and after selecting one the display adjusts to the selected size and then stays blank. No further reaction.

**Comment by jackpot51** [comment]
@MarcusE1W are you using 0.3.1? How much memory did you give the machine?

**Comment by MarcusE1W** [comment]
I was not, but have tried 0.3.1 now. I am afraid it's the same. It adjusts the screen size to the selection and then nothing more happens. My memory is 1G. I have only one IDE drive attached for the iso file, can that be a problem ?

**Comment by MarcusE1W** [comment]
I noticed that this issue moved a bit target from VMware and Windows 10 to Virtualbox and Windows 7, should I open a new issue ?

**Comment by jackpot51** [comment]
@MarcusE1W You must give the virtual machine at least 2 GB of memory.

**Comment by MarcusE1W** [comment]
Oh, that did it.
